Repository codesquad-members-2022/airbnb, pull requests merged in 2022-05, with the labels that each got.

#47 [Team 30] [Dott, Geon] 1주차 1번째 PR
  airbnb/.eslintignore
  airbnb/.eslintrc.js
  airbnb/.gitignore
  airbnb/.prettierrc
  airbnb/craco.config.js
  airbnb/package-lock.json
  airbnb/package.json
  airbnb/public/index.html
  airbnb/src/App.tsx
  airbnb/src/Component/GNB/AccountMenu.jsx
  airbnb/src/Component/GNB/GNB.tsx
  airbnb/src/Component/GNB/GNBstyle.tsx
  airbnb/src/Component/GNB/Menus.jsx
  airbnb/src/Component/GNB/index.ts
  airbnb/src/Component/SearchBar/Item.tsx
  airbnb/src/Component/SearchBar/SearchBar.tsx
  airbnb/src/Component/SearchBar/SearchBarStyle.tsx
  airbnb/src/Component/SearchBar/SearchButton.jsx
  airbnb/src/Component/SearchBar/index.ts
  airbnb/src/Context/Searching/index.tsx
  airbnb/src/Pages/Home.tsx
  airbnb/src/index.tsx
  airbnb/src/styles/ColorTheme.jsx
  airbnb/src/styles/GlobalStyle.tsx
  airbnb/src/styles/index.ts
  airbnb/tsconfig.eslint.json
  airbnb/tsconfig.json
  airbnb/tsconfig.paths.json
Labels: review-FE

#8 [Team-16][BE][Yanse] AirBnB 프로젝트 1주차 PR#1
  Android/README.md
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/yanse/airbnb/AirbnbApplication.java
  BE/src/main/java/yanse/airbnb/domain/hotel/Address.java
  BE/src/main/java/yanse/airbnb/domain/hotel/Room.java
  BE/src/main/java/yanse/airbnb/domain/hotel/RoomInfo.java
  BE/src/main/java/yanse/airbnb/domain/main/MainAroundImage.java
  BE/src/main/java/yanse/airbnb/domain/main/MainImage.java
  BE/src/main/java/yanse/airbnb/domain/main/MainRecommendationImage.java
  BE/src/main/java/yanse/airbnb/domain/member/Member.java
  BE/src/main/java/yanse/airbnb/domain/reservation/Reservation.java
  BE/src/main/java/yanse/airbnb/domain/wish/WishList.java
  BE/src/main/resources/application.yml
  BE/src/test/java/yanse/airbnb/AirbnbApplicationTests.java
Labels: review-BE

#31 [Team-15][BE] 포키&나단의 airbnb 프로젝트 PR #1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  android/.keep
  backend/.gitignore
  backend/HELP.md
  backend/airbnb.iml
  backend/build.gradle
  backend/docker/README.md
  backend/docker/database-local.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/team15/airbnb/AirbnbApplication.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/team15/airbnb/AirbnbApplicationTests.java
Labels: review-BE

#45 [TEAM-25] Airbnb 1주차 1번째 PR Nick + Benny
  .eslintrc.js
  .gitignore
  .prettierrc.js
  package-lock.json
  package.json
  public/assets/images/hero-img.png
  public/index.html
  src/App.tsx
  src/common/global.js
  src/common/theme.js
  src/common/utils.js
  src/components/GNB/GNB.styeld.js
  src/components/GNB/GNB.tsx
  src/components/Hero/Hero.styled.js
  src/components/Hero/Hero.tsx
  src/constant/constant.js
  src/index.tsx
  src/pages/Home/Home.styled.js
  src/pages/Home/Home.tsx
  src/pages/Rooms/Rooms.styled.js
  src/pages/Rooms/Rooms.tsx
  src/react-app-env.d.ts
  tsconfig.json
Labels: review-FE

#53 [team-2][BB] Airbnb 1주차 PR - 1
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  frontend/.gitignore
  frontend/README.md
  frontend/package.json
  frontend/public/index.html
  frontend/src/@types/index.d.ts
  frontend/src/App.tsx
  frontend/src/assets/hero-img.png
  frontend/src/components/Header/GNB/GNB.tsx
  frontend/src/components/Header/GNB/NavItem.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/UserMenu/UserMenu.tsx
  frontend/src/index.tsx
  frontend/src/styles/theme.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: review-FE

#15 [team04][iOS] 메인 화면 구현
  .github/ISSUE_TEMPLATE/--------.md
  .gitignore
  .gitmessage.txt
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/org/team4/airbnb/AirbnbApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/org/team4/airbnb/AirbnbApplicationTests.java
  iOS/.swiftlint.yml
  iOS/Podfile
  iOS/Podfile.lock
  iOS/airbnb.xcodeproj/project.pbxproj
  iOS/airbnb.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/airbnb.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/airbnb.xcworkspace/contents.xcworkspacedata
  iOS/airbnb.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/airbnb/AppDelegate.swift
  iOS/airbnb/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/airbnb/Assets.xcassets/Contents.json
  iOS/airbnb/Assets.xcassets/color/Contents.json
  iOS/airbnb/Assets.xcassets/color/Gray1.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/color/Gray3.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/color/Gray5.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/color/black.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/color/blue.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/color/gray2.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/color/gray4.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/color/gray6.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/color/primary.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/color/secondary.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/color/white.colorset/Contents.json
  iOS/airbnb/Assets.xcassets/images/Contents.json
  iOS/airbnb/Assets.xcassets/images/img_hero.imageset/Contents.json
  iOS/airbnb/Assets.xcassets/images/img_hero.imageset/img_hero.png
  iOS/airbnb/Base.lproj/LaunchScreen.storyboard
  iOS/airbnb/Common/Extension/UIColor+Extension.swift
  iOS/airbnb/Info.plist
  iOS/airbnb/Present/MainTabBarViewController.swift
  iOS/airbnb/Present/MainViewController.swift
  iOS/airbnb/Present/ReservationViewController.swift
  iOS/airbnb/Present/WishListViewController.swift
  iOS/airbnb/SceneDelegate.swift
  iOS/airbnbTests/airbnbTests.swift
  iOS/airbnbUITests/airbnbUITests.swift
  iOS/airbnbUITests/airbnbUITestsLaunchTests.swift
Labels: review-iOS

#57 [Team23 땃쥐] airbnb 1차 PR
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/codesquad/airbnb/AirbnbApplication.java
  BE/src/test/java/codesquad/airbnb/AirbnbApplicationTests.java
  README.md
  labels.json
Labels: review-BE

#43 [Team-22][BE][Lee&벅픽] - 프로젝트 초기 설정 및 Mockup API 제공, 숙소 검색 기능
  .github/ISSUE_TEMPLATE.md
  README.md
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/kr/codesquad/airbnb/AirbnbApplication.java
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/domain/PeopleConstraint.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveFormResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
  be/src/main/resources/application.properties
  be/src/test/java/kr/codesquad/airbnb/AirbnbApplicationTests.java
Labels: review-BE

#19 [Team-19][BE][Jun&Hwi] - 요구사항 분석, Mockup API, ERD 설계
  README.md
Labels: review-BE

#34 [Team-20 BE] Airbnb 프로젝트 1주차(수요일) 리뷰 요청
  .gitignore
  be/.gitignore
  be/README.md
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/codesquad/airbnb/AirbnbApplication.java
  be/src/main/java/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/codesquad/airbnb/domain/Facility.java
  be/src/main/java/codesquad/airbnb/domain/Member.java
  be/src/main/java/codesquad/airbnb/domain/Reservation.java
  be/src/main/resources/application.yml
  be/src/test/java/codesquad/airbnb/AirbnbApplicationTests.java
  fe/.gitignore
  fe/README.md
Labels: review-BE

#51 [Team-34] 베르&쥬 1주차 수요일 PR - 프로젝트 개발환경 세팅
  .eslintignore
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  .prettierrc
  craco.config.js
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/GNB/GNB.tsx
  src/constants/data.js
  src/constants/number.js
  src/custom.d.ts
  src/index.tsx
  tsconfig.json
  tsconfig.paths.json
Labels: review-FE

#22 [Team 26-FE] 1주차 01 PR요청 (이든, 도리)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  FE/.eslintrc.json
  FE/.gitignore
  FE/.prettierrc
  FE/README.md
  FE/babel.config.json
  FE/config/webpack.common.js
  FE/config/webpack.development.js
  FE/config/webpack.production.js
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/Card.tsx
  FE/src/index.tsx
  FE/tsconfig.json
Labels: review-FE

#33 [Team-12][BE][동기&루이] - 요구사항 분석, API 설계, 프로젝트 초기 세팅
  .gitignore
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/docs/asciidoc/index.adoc
  BE/src/main/java/louie/dong/airbnb/AirbnbApplication.java
  BE/src/main/java/louie/dong/airbnb/controller/AccommodationController.java
  BE/src/main/java/louie/dong/airbnb/controller/MainController.java
  BE/src/main/java/louie/dong/airbnb/controller/PopularDestinationController.java
  BE/src/main/java/louie/dong/airbnb/dto/PopularDestinationResponse.java
  BE/src/main/java/louie/dong/airbnb/dto/SearchCountryResponse.java
  BE/src/main/java/louie/dong/airbnb/service/MockAccommodationService.java
  BE/src/main/java/louie/dong/airbnb/service/MockPopularDestinationService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/static/docs/index.html
  BE/src/test/java/louie/dong/airbnb/AirbnbApplicationTests.java
  BE/src/test/java/louie/dong/airbnb/integration/AccommodationIntegrationTest.java
  BE/src/test/java/louie/dong/airbnb/integration/MainIntegrationTest.java
  BE/src/test/java/louie/dong/airbnb/integration/PopularDestinationIntegrationTest.java
  README.md
Labels: review-BE

#52 [Team-03] 프로젝트 설정
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  README.md
  be/README.md
  fe/README.md
  ios/AirBnb/.gitignore
  ios/AirBnb/.swiftformat
  ios/AirBnb/.swiftlint
  ios/AirBnb/.swiftlint.yml
  ios/AirBnb/AirBnb.xcodeproj/project.pbxproj
  ios/AirBnb/AirBnb.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/AirBnb/AirBnb.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/AirBnb/AirBnb.xcodeproj/xcshareddata/xcschemes/Debug.xcscheme
  ios/AirBnb/AirBnb.xcodeproj/xcshareddata/xcschemes/Release.xcscheme
  ios/AirBnb/AirBnb.xcodeproj/xcuserdata/song.xcuserdatad/xcschemes/xcschememanagement.plist
  ios/AirBnb/AirBnb/Application/AppDelegate.swift
  ios/AirBnb/AirBnb/Application/SceneDelegate.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/HomeController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Reservation/ReservationViewController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/WishList/WishListViewController.swift
  ios/AirBnb/AirBnb/Presentation/Utils/Extensions/UIColor+Extensions.swift
  ios/AirBnb/AirBnb/Presentation/Utils/Extensions/UIImage+Extensions.swift
  ios/AirBnb/AirBnb/Presentation/View/ScrollableView.swift
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray1.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray2.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray3.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray4.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray5.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray6.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/primary.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/secondary.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Base.lproj/LaunchScreen.storyboard
  ios/AirBnb/AirBnb/Resources/Info.plist
  ios/AirBnb/Gemfile
  ios/AirBnb/Gemfile.lock
  ios/AirBnb/Toolbox/.gitignore
  ios/AirBnb/Toolbox/Empty.swift
  ios/AirBnb/Toolbox/Package.swift
  ios/AirBnb/Toolbox/README.md
  ios/AirBnb/Toolbox/Sources/Toolbox/Toolbox.swift
  ios/AirBnb/Toolbox/Tests/ToolboxTests/ToolboxTests.swift
  ios/AirBnb/debug.xcconfig
  ios/AirBnb/fastlane/Appfile
  ios/AirBnb/fastlane/Fastfile
  ios/AirBnb/fastlane/README.md
  ios/AirBnb/release.xcconfig
  ios/README.md
Labels: review-iOS

#40 [Team - 06][BE] 에어비앤비 프로젝트 1주차 1회차 PR
  .github/ISSUE_TEMPLATE/-be--feature-request.md
  .github/ISSUE_TEMPLATE/-ios--feture-request.md
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/airbnb/AirbnbApplication.java
  BE/src/main/java/com/airbnb/api/search/SearchController.java
  BE/src/main/java/com/airbnb/api/search/dto/HouseListResponse.java
  BE/src/main/java/com/airbnb/api/search/dto/SearchConditionRequest.java
  BE/src/main/java/com/airbnb/domain/DetailInfo.java
  BE/src/main/java/com/airbnb/domain/DiscountPolicy.java
  BE/src/main/java/com/airbnb/domain/House.java
  BE/src/main/java/com/airbnb/domain/HouseDiscountPolicy.java
  BE/src/main/java/com/airbnb/domain/Image.java
  BE/src/main/java/com/airbnb/domain/Position.java
  BE/src/main/java/com/airbnb/domain/Reservation.java
  BE/src/main/java/com/airbnb/domain/Role.java
  BE/src/main/java/com/airbnb/domain/User.java
  BE/src/main/java/com/airbnb/domain/WishList.java
  BE/src/main/java/com/airbnb/repository/HouseRepository.java
  BE/src/main/java/com/airbnb/service/HouseService.java
  BE/src/main/resources/application.yml
  BE/src/test/java/com/airbnb/AirbnbApplicationTests.java
  BE/src/test/java/com/airbnb/repository/HouseRepositoryTest.java
  BE/src/test/resources/application.yml
  README.md
Labels: review-BE

#59 [Team-03] 1주차 첫번째 PR
  fe/.eslintignore
  fe/.eslintrc
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/README.old.md
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.tsx
  fe/src/components/GNB/AccountMenu/AccountMenu.tsx
  fe/src/components/GNB/GNB.styled.tsx
  fe/src/components/GNB/GNB.tsx
  fe/src/components/GNB/Logo/Logo.tsx
  fe/src/components/GNB/Menu/Menu.styled.tsx
  fe/src/components/GNB/Menu/Menu.tsx
  fe/src/components/Routers/Routers.tsx
  fe/src/custom.d.ts
  fe/src/img/png/hero-img.png
  fe/src/img/svg/accomodation.svg
  fe/src/img/svg/experience.svg
  fe/src/img/svg/login.svg
  fe/src/img/svg/logo.svg
  fe/src/img/svg/online-experience.svg
  fe/src/index.tsx
  fe/src/pages/Main/Main.tsx
  fe/src/pages/NotFound.tsx
  fe/src/pages/Search/Search.tsx
  fe/src/pages/index.tsx
  fe/tsconfig.json
  fe/yarn.lock
Labels: review-FE

#50 [Team-33][bangtae & 포키] 1주차 수요일 PR
  .github/ISSUE_TEMPLATE/bug_issue_template.md
  .github/ISSUE_TEMPLATE/feature_issue_template.md
  .gitignore
  README.md
  airbnb-app/.gitignore
  airbnb-app/.prettierrc
  airbnb-app/package-lock.json
  airbnb-app/package.json
  airbnb-app/public/index.html
  airbnb-app/src/App.js
  airbnb-app/src/common/globalStyle.js
  airbnb-app/src/common/theme.js
  airbnb-app/src/component/AccountMenu.jsx
  airbnb-app/src/component/GNB.jsx
  airbnb-app/src/component/Logo.jsx
  airbnb-app/src/component/MenuTabs.jsx
  airbnb-app/src/component/search-bar/ResetButton.jsx
  airbnb-app/src/component/search-bar/SearchBar.jsx
  airbnb-app/src/component/search-bar/SearchInput.jsx
  airbnb-app/src/constants/searchBarText.js
  airbnb-app/src/custom-styled-component/CustomThemeProvider.jsx
  airbnb-app/src/custom-styled-component/customStyled.js
  airbnb-app/src/custom-styled-component/domElements.js
  airbnb-app/src/custom-styled-component/useTheme.jsx
  airbnb-app/src/index.js
Labels: review-FE

#14 [Team 32] [J, 럼카] 1주차 1번째 PR 요청드립니다.
  .gitignore
  .prettierrc
  README.md
  jsconfig.json
  package-lock.json
  package.json
  public/index.html
  src/components/App.jsx
  src/components/modal/ReservationModal.jsx
  src/components/modal/SearchBarModal.jsx
  src/index.jsx
  src/styles/GlobalStyles.js
  src/styles/colors.js
  src/styles/utils.js
Labels: review-FE

#58 [Team-24][FE] Jinnie & Jamie 1주차 첫번째 PR
  .github/ISSUE_TEMPLATE/default_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  FE/.eslintrc
  FE/.gitignore
  FE/.prettierrc
  FE/.storybook/main.js
  FE/.storybook/preview.js
  FE/README.md
  FE/craco.config.js
  FE/package-lock.json
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/public/logo192.png
  FE/public/logo512.png
  FE/public/manifest.json
  FE/public/robots.txt
  FE/src/App.tsx
  FE/src/assets/icons/index.ts
  FE/src/assets/icons/menu.svg
  FE/src/assets/icons/user.svg
  FE/src/assets/styles/GlobalStyle.tsx
  FE/src/assets/styles/styled.d.ts
  FE/src/assets/styles/theme.ts
  FE/src/components/Header/Header.stories.tsx
  FE/src/components/Header/Header.style.js
  FE/src/components/Header/Logo.tsx
  FE/src/components/Header/MyPageButton.tsx
  FE/src/components/Header/Navigation.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/common/Icon/Icon.stories.tsx
  FE/src/components/common/Icon/Icon.style.ts
  FE/src/components/common/Icon/index.tsx
  FE/src/constants/index.js
  FE/src/constants/nav.js
  FE/src/custom.d.ts
  FE/src/index.tsx
  FE/tsconfig.json
  FE/tsconfig.path.json
Labels: review-FE

#11 [Team-01/BE] 숙소예약 서비스 프로젝트 1주차 1차 리뷰
  README.md
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/codesquad/airbnb/AirbnbApplication.java
  be/src/main/java/com/codesquad/airbnb/accommodation/domain/Accommodation.java
  be/src/main/java/com/codesquad/airbnb/accommodation/domain/Reservation.java
  be/src/main/java/com/codesquad/airbnb/accommodation/web/AccommodationController.java
  be/src/main/java/com/codesquad/airbnb/accommodation/web/dto/ListConditionDto.java
  be/src/main/java/com/codesquad/airbnb/accommodation/web/dto/PriceConditionDto.java
  be/src/main/java/com/codesquad/airbnb/common/CalculatorUtils.java
  be/src/main/java/com/codesquad/airbnb/naverapi/ApiKey.java
  be/src/main/java/com/codesquad/airbnb/naverapi/domain/GeoCode.java
  be/src/main/java/com/codesquad/airbnb/naverapi/service/GeoCodeService.java
  be/src/main/java/com/codesquad/airbnb/naverapi/web/GeoCodeController.java
  be/src/main/java/com/codesquad/airbnb/naverapi/web/dto/Address.java
  be/src/main/java/com/codesquad/airbnb/naverapi/web/dto/GeoCodeResponseDto.java
  be/src/main/resources/application.yml
  be/src/test/java/com/codesquad/airbnb/AirbnbApplicationTests.java
  be/src/test/java/com/codesquad/airbnb/naverapi/domain/GeoCodeTest.java
Labels: review-BE

#44 [team-21] 데이먼 첫 번째 PR 드립니다.
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/team21/airbnb/AirbnbApplication.java
  BE/src/main/java/team21/airbnb/controller/HomeController.java
  BE/src/main/java/team21/airbnb/domain/Amenity.java
  BE/src/main/java/team21/airbnb/domain/Booking.java
  BE/src/main/java/team21/airbnb/domain/BookingStatus.java
  BE/src/main/java/team21/airbnb/domain/Image.java
  BE/src/main/java/team21/airbnb/domain/Location.java
  BE/src/main/java/team21/airbnb/domain/Review.java
  BE/src/main/java/team21/airbnb/domain/Room.java
  BE/src/main/java/team21/airbnb/domain/RoomAmenity.java
  BE/src/main/java/team21/airbnb/domain/RoomType.java
  BE/src/main/java/team21/airbnb/domain/SpaceType.java
  BE/src/main/java/team21/airbnb/domain/User.java
  BE/src/main/java/team21/airbnb/domain/Wish.java
  BE/src/main/java/team21/airbnb/dto/response/RoomChargeDistributionResponse.java
  BE/src/main/java/team21/airbnb/repository/RoomRepository.java
  BE/src/main/java/team21/airbnb/service/RoomService.java
  BE/src/main/resources/application.yml
  BE/src/test/java/team21/airbnb/AirbnbApplicationTests.java
  BE/src/test/java/team21/airbnb/controller/HomeControllerTest.java
  BE/src/test/java/team21/airbnb/repository/RoomRepositoryTest.java
  BE/src/test/java/team21/airbnb/service/RoomServiceTest.java
  BE/src/test/resources/application.yml
Labels: review-BE

#17 [Team-05][BE] 비씨 & 노리 airbnb 프로젝트 1주차 첫 번째 PR
  .gitcommit
  Backend/.gitignore
  Backend/HELP.md
  Backend/README.md
  Backend/build.gradle
  Backend/gradle/wrapper/gradle-wrapper.jar
  Backend/gradle/wrapper/gradle-wrapper.properties
  Backend/gradlew
  Backend/gradlew.bat
  Backend/settings.gradle
  Backend/src/main/java/project/airbnb/AirbnbApplication.java
  Backend/src/main/java/project/airbnb/bnb/Bnb.java
  Backend/src/main/java/project/airbnb/reservation/Reservation.java
  Backend/src/main/java/project/airbnb/reservation/ReservationController.java
  Backend/src/main/java/project/airbnb/user/Member.java
  Backend/src/main/java/project/airbnb/wishlist/Wish.java
  Backend/src/main/java/project/airbnb/wishlist/WishController.java
  Backend/src/main/java/project/airbnb/wishlist/WishDto.java
  Backend/src/main/java/project/airbnb/wishlist/WishRepository.java
  Backend/src/main/java/project/airbnb/wishlist/WishService.java
  Backend/src/main/resources/application-bc.yml
  Backend/src/main/resources/application-nori.yml
  Backend/src/main/resources/application.yml
  Backend/src/test/java/project/airbnb/AirbnbApplicationTests.java
  iOS/README.md
Labels: review-BE

#35 [Team01 - iOS] 첫 PR
  .gitignore
  README.md
  airbnb/Podfile
  airbnb/Podfile.lock
  airbnb/airbnb.xcodeproj/project.pbxproj
  airbnb/airbnb.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  airbnb/airbnb.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  airbnb/airbnb.xcworkspace/contents.xcworkspacedata
  airbnb/airbnb.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  airbnb/airbnb/Info.plist
  airbnb/airbnb/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  airbnb/airbnb/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  airbnb/airbnb/Resources/Assets.xcassets/Contents.json
  airbnb/airbnb/Resources/Assets.xcassets/heroImageBackground.imageset/Contents.json
  airbnb/airbnb/Resources/Assets.xcassets/heroImageBackground.imageset/background.png
  airbnb/airbnb/Resources/Assets.xcassets/heroImageBackground.imageset/background@2x.png
  airbnb/airbnb/Resources/Assets.xcassets/heroImageBackground.imageset/background@3x.png
  airbnb/airbnb/Resources/Assets.xcassets/logo.imageset/Contents.json
  airbnb/airbnb/Resources/Assets.xcassets/logo.imageset/logo.png
  airbnb/airbnb/Resources/Assets.xcassets/logo.imageset/logo@2x.png
  airbnb/airbnb/Resources/Assets.xcassets/logo.imageset/logo@3x.png
  airbnb/airbnb/Resources/Base.lproj/LaunchScreen.storyboard
  airbnb/airbnb/Sources/AppDelegate.swift
  airbnb/airbnb/Sources/Extension/UIColor+Extention.swift
  airbnb/airbnb/Sources/SceneDelegate.swift
  airbnb/airbnb/Sources/View/HeroImageView.swift
  airbnb/airbnb/Sources/ViewController/NavigationBarController.swift
  airbnb/airbnbTests/airbnbTests.swift
  airbnb/airbnbUITests/airbnbUITests.swift
  airbnb/airbnbUITests/airbnbUITestsLaunchTests.swift
Labels: review-iOS

#23 [team-31][FE] Muffin & Park 1주차 수요일 PR
  .babelrc
  .eslintrc.js
  .github/ISSUE_TEMPLATE/fe---feat-request.md
  .github/PULL_REQUREST_TEMPLATE.md
  .gitignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/hero-img.png
  public/index.html
  src/App.tsx
  src/common/keyframes.tsx
  src/common/theme.tsx
  src/components/FlexBox.tsx
  src/components/Footer/index.tsx
  src/components/Header/BigSearchBar.tsx
  src/components/Header/Category.tsx
  src/components/Header/Logo.tsx
  src/components/Header/MiniSearchBar.tsx
  src/components/Header/UserInfo.tsx
  src/components/Header/index.tsx
  src/components/Layout.tsx
  src/constants/color.ts
  src/constants/fontSize.ts
  src/index.tsx
  src/pages/MainPage.tsx
  tsconfig.json
  webpack.config.js
Labels: review-FE

#16 [Team-13][iOS][Dale&Mase] 앱 초기 화면(검색 탭) 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  iOS/.gitignore
  iOS/AirbnbApp/.swiftlint.yml
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.pbxproj
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project_BACKUP_48900.pbxproj
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project_BASE_48900.pbxproj
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project_LOCAL_48900.pbxproj
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project_REMOTE_48900.pbxproj
  iOS/AirbnbApp/AirbnbApp/Base.lproj/LaunchScreen.storyboard
  iOS/AirbnbApp/AirbnbApp/Info.plist
  iOS/AirbnbApp/AirbnbApp/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/AirbnbApp/AirbnbApp/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/AirbnbApp/AirbnbApp/Resource/Assets.xcassets/Contents.json
  iOS/AirbnbApp/AirbnbApp/Resource/Assets.xcassets/mockimage.imageset/Contents.json
  iOS/AirbnbApp/AirbnbApp/Resource/Assets.xcassets/mockimage.imageset/mockimage.png
  iOS/AirbnbApp/AirbnbApp/Resource/NotoSansKR-Medium.otf
  iOS/AirbnbApp/AirbnbApp/Resource/NotoSansKR-Regular.otf
  iOS/AirbnbApp/AirbnbApp/Resource/SF-Pro-Display-Medium.otf
  iOS/AirbnbApp/AirbnbApp/Resource/SF-Pro-Display-Regular.otf
  iOS/AirbnbApp/AirbnbApp/Resource/SF-Pro-Display-Semibold.otf
  iOS/AirbnbApp/AirbnbApp/Source/CustomObservable.swift
  iOS/AirbnbApp/AirbnbApp/Source/Extension/UIColor+Extension.swift
  iOS/AirbnbApp/AirbnbApp/Source/Extension/UIFont+Extension.swift
  iOS/AirbnbApp/AirbnbApp/Source/LifeCycle/AppDelegate.swift
  iOS/AirbnbApp/AirbnbApp/Source/LifeCycle/SceneDelegate.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Common/CustomLabel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Common/NearDestinationViewCell.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/DestinationCollectionViewCell.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/MainTabBar/MainTabBarViewController.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/DestinationCollecionViewDataSource.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/DestinationHeaderView.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/DestinationSearchBar.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/DestinationSearchBarDelegate.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/HeroImageViewCell.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/SearchHomeViewController.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/SearchHomeViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/Support/DestinationCollectionViewSection.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/Support/SectionLayoutFactory.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/TravelThemeViewCell.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/TabBar/MainTabBarController.swift
  iOS/AirbnbApp/AirbnbApp/Source/ViewModelProtocol.swift
Labels: review-iOS

#48 [TEAM-07] BE Airbnb 1주차 1번째 PR Sally + zzangmin
  BE/airbnb/.gitignore
  BE/airbnb/HELP.md
  BE/airbnb/build.gradle
  BE/airbnb/gradle/wrapper/gradle-wrapper.jar
  BE/airbnb/gradle/wrapper/gradle-wrapper.properties
  BE/airbnb/gradlew
  BE/airbnb/gradlew.bat
  BE/airbnb/settings.gradle
  BE/airbnb/src/main/java/team07/airbnb/AirbnbApplication.java
  BE/airbnb/src/main/resources/application.properties
  BE/airbnb/src/test/java/team07/airbnb/AirbnbApplicationTests.java
Labels: review-BE

#27 [FE][Team27][Khan, Sonya] 첫 번째 PR - 전체적인 레이아웃
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  airbnb/.gitignore
  airbnb/.prettierrc
  airbnb/package-lock.json
  airbnb/package.json
  airbnb/public/favicon.ico
  airbnb/public/index.html
  airbnb/src/App.tsx
  airbnb/src/assets/data/cityData.js
  airbnb/src/assets/data/footerData.js
  airbnb/src/assets/data/tripData.js
  airbnb/src/assets/image/city/Bucheon.png
  airbnb/src/assets/image/city/Daegu.png
  airbnb/src/assets/image/city/Daejeon.png
  airbnb/src/assets/image/city/Gwangju.png
  airbnb/src/assets/image/city/Seoul.png
  airbnb/src/assets/image/city/Suwon.png
  airbnb/src/assets/image/city/Uijeongbu.png
  airbnb/src/assets/image/city/Ulsan.png
  airbnb/src/assets/image/city/app.js
  airbnb/src/assets/image/trip/Dog.png
  airbnb/src/assets/image/trip/House.png
  airbnb/src/assets/image/trip/Nature.png
  airbnb/src/assets/image/trip/Water.png
  airbnb/src/assets/image/trip/app.js
  airbnb/src/assets/svg/menu.svg
  airbnb/src/assets/svg/searchBtn.svg
  airbnb/src/assets/svg/user.svg
  airbnb/src/components/SearchBar/CheckOut.jsx
  airbnb/src/components/SearchBar/Personnel.jsx
  airbnb/src/components/SearchBar/Price.jsx
  airbnb/src/components/SearchBar/SearchBar.jsx
  airbnb/src/components/SearchBar/SearchBar_styled.jsx
  airbnb/src/components/footer/CompanyInfo.jsx
  airbnb/src/components/footer/Content.jsx
  airbnb/src/components/footer/Footer.jsx
  airbnb/src/components/header/Header.jsx
  airbnb/src/components/header/Logo.jsx
  airbnb/src/components/header/UpperMenu.jsx
  airbnb/src/components/header/UserInfo.jsx
  airbnb/src/components/main/GroupOne.jsx
  airbnb/src/components/main/GroupTwo.jsx
  airbnb/src/components/main/Main.jsx
  airbnb/src/components/main/MainTitle.jsx
  airbnb/src/index.tsx
  airbnb/src/style/globalStyles.js
  airbnb/src/style/mixins.js
  airbnb/src/style/theme.js
  airbnb/tsconfig.json
Labels: review-FE

#12 [Team 21 FE] airbnb 1주차 첫번째 PR
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  FE/.eslintrc.cjs
  FE/.gitignore
  FE/.prettierrc
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/src/App.tsx
  FE/src/index.tsx
  FE/src/react-app-env.d.ts
  FE/tsconfig.json
  README.md
Labels: review-FE

#36 [Team-35] [FE] 첫번째 PR
  .babelrc
  .eslintrc.js
  .gitignore
  .prettier.js
  config/webpack.common.js
  config/webpack.dev.js
  config/webpack.prod.js
  package-lock.json
  package.json
  public/assest/hero-img.png
  public/index.html
  src/App.tsx
  src/UI/Container.tsx
  src/UI/Input.tsx
  src/components/Header/Backdrop.tsx
  src/components/Header/Header.tsx
  src/components/SerachBar/Period.tsx
  src/components/SerachBar/Personnel.tsx
  src/components/SerachBar/Price.tsx
  src/components/SerachBar/SearchBar.tsx
  src/components/calendar/CalendarModal.tsx
  src/components/calendar/MonthTBody.tsx
  src/components/calendar/MonthTHead.tsx
  src/components/calendar/MonthTable.tsx
  src/components/calendar/WeekTRow.tsx
  src/index.tsx
  src/style/GlobalStyle.ts
  src/style/theme.ts
  src/util/calenderUtil.tsx
  tsconfig.json
Labels: review-FE

#9 [Team 18-Android] 메인화면 구성하기
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/todo/airbnb/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/todo/airbnb/data/Accommodations.kt
  app/src/main/java/com/example/todo/airbnb/data/Travel.kt
  app/src/main/java/com/example/todo/airbnb/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/example/todo/airbnb/domain/repository/MainRepository.kt
  app/src/main/java/com/example/todo/airbnb/presentation/main/MainActivity.kt
  app/src/main/java/com/example/todo/airbnb/presentation/main/components/BottomBar.kt
  app/src/main/java/com/example/todo/airbnb/presentation/main/components/MainScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/main/components/TopBar.kt
  app/src/main/java/com/example/todo/airbnb/presentation/reservation/components/ReservationScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/SearchViewModel.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/SearchWidgetState.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/AccommodationsScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/LoadMainImage.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/SearchScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/TravelScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/wishlist/components/WishListScreen.kt
  app/src/main/java/com/example/todo/airbnb/ui/theme/Color.kt
  app/src/main/java/com/example/todo/airbnb/ui/theme/Shape.kt
  app/src/main/java/com/example/todo/airbnb/ui/theme/Theme.kt
  app/src/main/java/com/example/todo/airbnb/ui/theme/Type.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_error.xml
  app/src/main/res/drawable/ic_favorite.xml
  app/src/main/res/drawable/ic_favorite_selected.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_loading.xml
  app/src/main/res/drawable/ic_reservation.xml
  app/src/main/res/drawable/ic_reservation_selected.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_selected.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/example/todo/airbnb/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: review-android

#7 [Team 12][iOS] 메인화면과 지역 검색화면 뷰
  .gitignore
  README.md
  airbnb/airbnb.xcodeproj/project.pbxproj
  airbnb/airbnb.xcodeproj/project.pbxproj.orig
  airbnb/airbnb.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  airbnb/airbnb.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  airbnb/airbnb.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  airbnb/airbnb/AppDelegate.swift
  airbnb/airbnb/Assets.xcassets/AccentColor.colorset/Contents.json
  airbnb/airbnb/Assets.xcassets/AppIcon.appiconset/Contents.json
  airbnb/airbnb/Assets.xcassets/Contents.json
  airbnb/airbnb/Assets.xcassets/gwangju.imageset/Contents.json
  airbnb/airbnb/Assets.xcassets/gwangju.imageset/gwangju.png
  airbnb/airbnb/Assets.xcassets/heroImage.imageset/Contents.json
  airbnb/airbnb/Assets.xcassets/heroImage.imageset/heroImage.jpeg
  airbnb/airbnb/Assets.xcassets/seoul.imageset/Contents.json
  airbnb/airbnb/Assets.xcassets/seoul.imageset/seoul.png
  airbnb/airbnb/Base.lproj/LaunchScreen.storyboard
  airbnb/airbnb/Base.lproj/Main.storyboard
  airbnb/airbnb/Info.plist
  airbnb/airbnb/SceneDelegate.swift
  airbnb/airbnb/View/LocationTableViewCell.swift
  airbnb/airbnb/ViewController/MainTabBarController.swift
  airbnb/airbnb/ViewController/SearchView/LocationCalenderViewController.swift
  airbnb/airbnb/ViewController/SearchView/LocationResultViewController.swift
  airbnb/airbnb/ViewController/SearchView/LocationTableViewController.swift
  airbnb/airbnb/ViewController/SearchView/SearchViewController.swift
  airbnb/airbnb/ViewController/UserViewController.swift
  airbnb/airbnb/ViewController/WishViewController.swift
Labels: review-iOS

#24 [Team - 18 / 검봉 & Tany] 1주차 첫 번째 PR
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/team18/airbnb/AirbnbApplication.java
  BE/src/main/java/team18/airbnb/domain/Accommodation.java
  BE/src/main/java/team18/airbnb/domain/AccommodationInfo.java
  BE/src/main/java/team18/airbnb/domain/AccommodationPrice.java
  BE/src/main/java/team18/airbnb/domain/AccommodationType.java
  BE/src/main/java/team18/airbnb/domain/Region.java
  BE/src/main/java/team18/airbnb/domain/Reservation.java
  BE/src/main/java/team18/airbnb/domain/Review.java
  BE/src/main/java/team18/airbnb/domain/User.java
  BE/src/main/resources/application.yml
  BE/src/test/java/team18/airbnb/AirbnbApplicationTests.java
  BE/src/test/resources/application.yml
Labels: review-BE

#91 [Team-17 BE] airbnb 프로젝트 1주차 금요일 PR입니다.
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/kr/codesquad/airbnb/AirbnbApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/kr/codesquad/airbnb/AirbnbApplicationTests.java
Labels: review-BE

#107 [TEAM-11][BE] 민지노 && 필 Airbnb 1주차 금요일 PR
  BE/.gitignore
  BE/HELP.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/team11/airbnb/AirbnbApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/team11/airbnb/AirbnbApplicationTests.java
Labels: review-BE

#71 [Team-20 BE] Airbnb 프로젝트 1주차(금요일) 리뷰 요청
  be/README.md
  be/src/main/java/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/codesquad/airbnb/domain/Facility.java
  be/src/main/java/codesquad/airbnb/domain/Member.java
  be/src/main/java/codesquad/airbnb/domain/Reservation.java
  be/src/main/java/codesquad/airbnb/domain/ReservationStatus.java
  be/src/main/java/codesquad/airbnb/domain/Schedule.java
  be/src/main/java/codesquad/airbnb/dto/AccommodationPriceDto.java
  be/src/main/java/codesquad/airbnb/dto/AccommodationPriceListDto.java
  be/src/main/java/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/codesquad/airbnb/service/AccommodationService.java
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: review-BE

#103 [team-30] 달력 구현 1주차 PR -2
  airbnb/.eslintrc.js
  airbnb/package-lock.json
  airbnb/package.json
  airbnb/src/App.tsx
  airbnb/src/Component/Schedule/Schedule.tsx
  airbnb/src/Component/Schedule/ScheduleStyle.tsx
  airbnb/src/Component/SearchBar/SearchBarStyle.tsx
  airbnb/src/Context/Searching/index.tsx
  airbnb/src/Pages/Home.tsx
Labels: review-FE

#115 [Team-03] 1주차 두번째 PR
  fe/README.md
  fe/README.old.md
  fe/UserStory.md
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/GNB/AccountMenu/AccountMenu.tsx
  fe/src/components/GNB/GNB.styled.tsx
  fe/src/components/GNB/GNB.tsx
  fe/src/components/GNB/Logo/Logo.tsx
  fe/src/components/GNB/Menu/Menu.styled.tsx
  fe/src/components/GNB/Menu/Menu.tsx
  fe/src/components/Routers/Routers.tsx
  fe/src/components/SearchBar/Period/Period.tsx
  fe/src/components/SearchBar/Personnel/Personnel.tsx
  fe/src/components/SearchBar/Price/Price.tsx
  fe/src/components/SearchBar/SearchBar.styled.tsx
  fe/src/components/SearchBar/SearchBar.tsx
  fe/src/components/SearchBar/SearchList/DeleteButton.tsx
  fe/src/components/SearchBar/SearchList/SearchList.tsx
  fe/src/components/SearchBar/SearchSection/SearchSection.tsx
  fe/src/components/SearchBar/types.ts
  fe/src/context/SearchProvider.tsx
  fe/src/img/svg/delete.svg
  fe/src/img/svg/search-icon.svg
  fe/src/img/svg/search-text-icon.svg
  fe/src/pages/Main/Main.tsx
  fe/src/pages/NotFound.tsx
  fe/src/pages/Search/Search.tsx
  fe/yarn.lock
Labels: review-FE

#97 [Team_02][Kai] : 정적 데이터 바인딩 및 검색창 구현
  Airbnb/Airbnb/Screens/Home/Model/CategoryType.swift
  Airbnb/Airbnb/Screens/Home/Model/City.swift
  Airbnb/Airbnb/Screens/Home/Model/Hero.swift
  Airbnb/Airbnb/Screens/Home/Model/RandomSite.swift
  Airbnb/Airbnb/Screens/Home/Model/Time.swift
  Airbnb/Airbnb/Screens/Home/View/CityCell.swift
  Airbnb/Airbnb/Screens/Home/View/FlowLayoutMaker.swift
  Airbnb/Airbnb/Screens/Home/View/HeroCell.swift
  Airbnb/Airbnb/Screens/Home/View/HomeViewController.swift
  Airbnb/Airbnb/Screens/Home/View/RandomSiteCell.swift
  Airbnb/Airbnb/Screens/Home/ViewModel/CityCellViewModel.swift
  Airbnb/Airbnb/Screens/Home/ViewModel/HeroCellViewModel.swift
  Airbnb/Airbnb/Screens/Home/ViewModel/HomeViewModel.swift
  Airbnb/Airbnb/Screens/Home/ViewModel/RandomSiteCellViewModel.swift
  Airbnb/Airbnb/Screens/Search/View/SearchViewController.swift
Labels: review-iOS

#78 [Team-03] 홈 화면 UI 작업
  ios/AirBnb/.swiftformat
  ios/AirBnb/AirBnb.xcodeproj/project.pbxproj
  ios/AirBnb/AirBnb/Application/AppDelegate.swift
  ios/AirBnb/AirBnb/Application/SceneDelegate.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/HeroCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/HomeController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/HomeViewController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/NearCityCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/RecommendationCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/TitleSupplementaryView.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/ViewModel/HomeViewModel.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Reservation/ReservationViewController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Search/LocationSearchController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Search/SearchResultViewController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/WishList/WishListViewController.swift
  ios/AirBnb/AirBnb/Presentation/Utils/Extensions/UIColor+Extensions.swift
  ios/AirBnb/AirBnb/Presentation/Utils/Observable.swift
  ios/AirBnb/AirBnb/Presentation/Utils/SectionFactory.swift
  ios/AirBnb/AirBnb/Presentation/View/ScrollableView.swift
  ios/README.md
Labels: review-iOS

#118 [Team23 땃쥐] airbnb 2차 PR
  BE/src/main/java/codesquad/airbnb/accommodation/domain/Accommodation.java
  BE/src/main/java/codesquad/airbnb/accommodation/domain/AccommodationImage.java
  BE/src/main/java/codesquad/airbnb/accommodation/domain/Facility.java
  BE/src/main/java/codesquad/airbnb/accommodation/domain/Location.java
  BE/src/main/java/codesquad/airbnb/booking/domain/Booking.java
  BE/src/main/java/codesquad/airbnb/booking/domain/BookingGuests.java
  BE/src/main/java/codesquad/airbnb/booking/domain/BookingPeriod.java
  BE/src/main/java/codesquad/airbnb/booking/domain/BookingStatus.java
  BE/src/main/java/codesquad/airbnb/exception/TooManyImageException.java
  BE/src/main/java/codesquad/airbnb/member/domain/Member.java
  BE/src/main/java/codesquad/airbnb/member/repository/MemberRepository.java
  BE/src/main/java/codesquad/airbnb/review/domain/Review.java
  README.md
Labels: review-BE

#83 [team-07] BE 1주차 2차 PR (sally+zzangmin)
  BE/airbnb/HELP.md
  BE/airbnb/README.md
  BE/airbnb/build.gradle
  BE/airbnb/src/main/java/team07/airbnb/address/Address.java
  BE/airbnb/src/main/java/team07/airbnb/image/Image.java
  BE/airbnb/src/main/java/team07/airbnb/image/ImageType.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/Reservation.java
  BE/airbnb/src/main/java/team07/airbnb/review/Review.java
  BE/airbnb/src/main/java/team07/airbnb/room/Room.java
  BE/airbnb/src/main/java/team07/airbnb/user/User.java
  BE/airbnb/src/main/java/team07/airbnb/user/UserRepository.java
  BE/airbnb/src/main/java/team07/airbnb/wishlist/Wishlist.java
  BE/airbnb/src/main/resources/application.properties
  BE/airbnb/src/main/resources/schema.sql
  README.md
Labels: review-BE

#99 [Team-13][iOS][Dale&Mase] Custom Observable 추상화 및 Alamofire를 이용한 네트워크 통신 구현
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.pbxproj
  iOS/AirbnbApp/AirbnbApp/Source/Model/Model/API/EndPoint.swift
  iOS/AirbnbApp/AirbnbApp/Source/Model/Model/API/EndPoint/EndPointable.swift
  iOS/AirbnbApp/AirbnbApp/Source/Model/Model/API/EndPoint/NetworkError.swift
  iOS/AirbnbApp/AirbnbApp/Source/Model/Model/API/EndPoint/Provider.swift
  iOS/AirbnbApp/AirbnbApp/Source/Model/Model/SearchHomeEntity.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/SearchHomeViewController.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/SearchHomeViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/ViewModel/SearchHomeViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/ViewModel/SearchHomeViewModelAction.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/ViewModel/SearchHomeViewModelBindable.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/ViewModel/SearchHomeViewModelState.swift
  iOS/AirbnbApp/AirbnbApp/Source/ViewModelProtocol.swift
Labels: review-iOS

#65 [Team-16][BE][Yanse] airbnb 프로젝트 1주차 PR#2
  BE/src/main/java/yanse/airbnb/domain/hotel/RoomInfo.java
  BE/src/main/java/yanse/airbnb/domain/main/ImageType.java
  BE/src/main/java/yanse/airbnb/domain/main/MainAroundImage.java
  BE/src/main/java/yanse/airbnb/domain/main/MainImage.java
  BE/src/main/java/yanse/airbnb/domain/main/MainRecommendationImage.java
  BE/src/main/java/yanse/airbnb/domain/member/Member.java
  BE/src/main/java/yanse/airbnb/domain/reservation/DetailFee.java
  BE/src/main/java/yanse/airbnb/domain/reservation/DiscountPolicy.java
  BE/src/main/java/yanse/airbnb/domain/reservation/Reservation.java
  BE/src/main/java/yanse/airbnb/domain/room/Address.java
  BE/src/main/java/yanse/airbnb/domain/room/Room.java
  BE/src/main/java/yanse/airbnb/domain/room/RoomInfo.java
  BE/src/main/java/yanse/airbnb/domain/room/RoomType.java
  BE/src/main/java/yanse/airbnb/domain/wish/WishList.java
Labels: review-BE

#42 [Team-04][BE][테리 & Sammy] 요구사항 분석 및 도메인 설계
  BE/README.md
  BE/docs/RequirementAnalysis.md
  BE/docs/airbnb_DB_ERD.png
  BE/docs/airbnb_table_create.sql
  BE/src/main/java/org/team4/airbnb/domain/Accommodation.java
  BE/src/main/java/org/team4/airbnb/domain/Address.java
  BE/src/main/java/org/team4/airbnb/domain/BaseCreated.java
  BE/src/main/java/org/team4/airbnb/domain/Customer.java
  BE/src/main/java/org/team4/airbnb/domain/Geolocation.java
  BE/src/main/java/org/team4/airbnb/domain/Invoice.java
  BE/src/main/java/org/team4/airbnb/domain/Reservation.java
  BE/src/main/java/org/team4/airbnb/domain/Review.java
  BE/src/main/java/org/team4/airbnb/domain/RoomFeature.java
  BE/src/main/java/org/team4/airbnb/domain/SecondaryImage.java
  BE/src/main/java/org/team4/airbnb/domain/Wish.java
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/logback.xml
Labels: review-BE

#114 [Team 32] [J, 럼카] 1주차 2번째 PR 요청드립니다.
  package.json
  public/index.html
  src/assets/check.svg
  src/assets/chevron-left.svg
  src/assets/chevron-right.svg
  src/assets/heart.svg
  src/assets/hero-img.jpg
  src/assets/menu.svg
  src/assets/minus-circle.svg
  src/assets/minus.svg
  src/assets/pause-circle.svg
  src/assets/plus-circle.svg
  src/assets/plus.svg
  src/assets/search.svg
  src/assets/star.svg
  src/assets/user.svg
  src/assets/x-circle.svg
  src/components/App.jsx
  src/components/Banner.jsx
  src/components/Header/AccountMenu.jsx
  src/components/Header/GNB.jsx
  src/components/Header/index.jsx
  src/components/IconButton.jsx
  src/components/SearchBar/FilterBox.jsx
  src/components/SearchBar/FilterContainer.jsx
  src/components/SearchBar/FilterResetButton.jsx
  src/components/SearchBar/MiniSearchBar.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchButton.jsx
  src/components/calendar/Calendar.jsx
  src/components/calendar/Day.jsx
  src/components/calendar/DaysWrap.jsx
  src/components/calendar/Month.jsx
  src/components/modal/SearchBarModal.jsx
  src/store/FilterContext.jsx
  src/styles/GlobalStyles.js
  src/styles/font.js
Labels: review-FE

#106 [Team-24][FE] Jinnie & Jamie 1주차 두번째 PR
  FE/.storybook/preview.js
  FE/src/App.tsx
  FE/src/assets/icons/index.ts
  FE/src/assets/icons/search.svg
  FE/src/assets/images/bucheon.jpg
  FE/src/assets/images/daegu.jpg
  FE/src/assets/images/daejeon.jpg
  FE/src/assets/images/gwangju.jpg
  FE/src/assets/images/hero-img.jpg
  FE/src/assets/images/index.js
  FE/src/assets/images/seoul.jpg
  FE/src/assets/images/suwon.jpg
  FE/src/assets/images/uijeongbu.jpg
  FE/src/assets/images/ulsan.jpg
  FE/src/assets/styles/GlobalStyle.tsx
  FE/src/components/Footer/CompanyInfo.tsx
  FE/src/components/Footer/Content.tsx
  FE/src/components/Footer/Footer.style.js
  FE/src/components/Footer/constants.tsx
  FE/src/components/Footer/index.tsx
  FE/src/components/GNB/GNB.stories.tsx
  FE/src/components/GNB/GNB.style.js
  FE/src/components/GNB/Logo.tsx
  FE/src/components/GNB/MyPageButton.tsx
  FE/src/components/GNB/Navigation.tsx
  FE/src/components/GNB/index.tsx
  FE/src/components/Header/Header.stories.tsx
  FE/src/components/Header/Header.style.js
  FE/src/components/Header/index.tsx
  FE/src/components/MainContent/CitySection.tsx
  FE/src/components/MainContent/MainContent.style.ts
  FE/src/components/MainContent/TripSection.tsx
  FE/src/components/MainContent/constants.ts
  FE/src/components/MainContent/index.tsx
  FE/src/components/SearchBar/PeriodArea.tsx
  FE/src/components/SearchBar/PersonnelArea.tsx
  FE/src/components/SearchBar/PriceArea.tsx
  FE/src/components/SearchBar/SearchBar.stories.tsx
  FE/src/components/SearchBar/SearchBar.style.ts
  FE/src/components/SearchBar/SearchButton.tsx
  FE/src/components/SearchBar/constants.ts
  FE/src/components/SearchBar/index.tsx
  FE/src/components/common/Icon/Icon.stories.tsx
  FE/src/components/common/Icon/Icon.style.ts
  FE/src/components/common/Icon/index.tsx
  FE/src/constants/index.js
  FE/src/custom.d.ts
  FE/src/data/cityData.ts
  FE/src/data/index.ts
  FE/src/data/nav.ts
  FE/src/data/searchBarData.ts
  FE/src/data/tripData.ts
  FE/src/lib/utils/index.js
  FE/tsconfig.path.json
Labels: review-FE

#92 [Team-22][BE][Lee&벅픽] 1주차 2번째 PR - 도메인 클래스 JPA 적용 및 검색 쿼리 수정
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/domain/DiscountPolicy.java
  be/src/main/java/kr/codesquad/airbnb/domain/PeopleConstraint.java
  be/src/main/java/kr/codesquad/airbnb/domain/Reservation.java
  be/src/main/java/kr/codesquad/airbnb/domain/User.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
Labels: review-BE

#77 [Team-01/BE] 숙소예약 서비스 프로젝트 1주차 2차 리뷰
  be/build.gradle
  be/src/main/java/com/codesquad/airbnb/AirbnbApplication.java
  be/src/main/java/com/codesquad/airbnb/accommodation/domain/Accommodation.java
  be/src/main/java/com/codesquad/airbnb/accommodation/domain/Reservation.java
  be/src/main/java/com/codesquad/airbnb/accommodation/web/AccommodationController.java
  be/src/main/java/com/codesquad/airbnb/accommodation/web/dto/BasicSearchCondition.java
  be/src/main/java/com/codesquad/airbnb/accommodation/web/dto/PriceSearchCondition.java
  be/src/main/java/com/codesquad/airbnb/common/BaseTime.java
  be/src/main/java/com/codesquad/airbnb/common/util/CalculatorUtils.java
  be/src/main/java/com/codesquad/airbnb/common/util/NaverAPIConnector.java
  be/src/main/java/com/codesquad/airbnb/naverapi/domain/GeoCode.java
  be/src/main/java/com/codesquad/airbnb/naverapi/service/GeoCodeService.java
  be/src/main/java/com/codesquad/airbnb/naverapi/web/GeoCodeController.java
  be/src/main/java/com/codesquad/airbnb/naverapi/web/dto/Address.java
  be/src/main/java/com/codesquad/airbnb/naverapi/web/dto/apiresponse/AddressElements.java
  be/src/main/java/com/codesquad/airbnb/naverapi/web/dto/apiresponse/Addresses.java
  be/src/main/java/com/codesquad/airbnb/naverapi/web/dto/apiresponse/NaverAPIResponse.java
  be/src/main/java/com/codesquad/airbnb/reservation/domain/Reservation.java
  be/src/main/java/com/codesquad/airbnb/reservation/service/ReservationService.java
  be/src/main/java/com/codesquad/airbnb/reservation/web/ReservationController.java
  be/src/main/java/com/codesquad/airbnb/reservation/web/dto/ReservationDetailDto.java
  be/src/main/java/com/codesquad/airbnb/reservation/web/dto/ReservationListResponseDto.java
  be/src/main/java/com/codesquad/airbnb/reservation/web/dto/ReservationRequestDto.java
  be/src/main/java/com/codesquad/airbnb/user/domain/User.java
  be/src/main/java/com/codesquad/airbnb/wishlist/domain/WishList.java
  be/src/main/java/com/codesquad/airbnb/wishlist/service/WishListService.java
  be/src/main/java/com/codesquad/airbnb/wishlist/web/WishListController.java
  be/src/main/java/com/codesquad/airbnb/wishlist/web/dto/WishListResponseDto.java
  be/src/main/resources/application.yml
Labels: review-BE

#62 [Team-09][BE][Dave&K] - 1주차 첫번째 PR
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/kr/codesquad/airbnb/AirbnbApplication.java
  src/main/java/kr/codesquad/airbnb/controller/LodgingController.java
  src/main/java/kr/codesquad/airbnb/controller/MainController.java
  src/main/java/kr/codesquad/airbnb/domain/Address.java
  src/main/java/kr/codesquad/airbnb/domain/Event.java
  src/main/java/kr/codesquad/airbnb/domain/Images.java
  src/main/java/kr/codesquad/airbnb/domain/Lodging.java
  src/main/java/kr/codesquad/airbnb/domain/Members.java
  src/main/java/kr/codesquad/airbnb/domain/PlaceType.java
  src/main/java/kr/codesquad/airbnb/domain/PropertyType.java
  src/main/java/kr/codesquad/airbnb/domain/Region.java
  src/main/java/kr/codesquad/airbnb/domain/Reservation.java
  src/main/java/kr/codesquad/airbnb/domain/Wish.java
  src/main/java/kr/codesquad/airbnb/dto/EventResponseDto.java
  src/main/java/kr/codesquad/airbnb/dto/LodgingResponseDto.java
  src/main/java/kr/codesquad/airbnb/dto/RegionResponse.java
  src/main/java/kr/codesquad/airbnb/repository/EventRepository.java
  src/main/java/kr/codesquad/airbnb/repository/ImageRepository.java
  src/main/java/kr/codesquad/airbnb/repository/LodgingRepository.java
  src/main/java/kr/codesquad/airbnb/repository/RegionRepository.java
  src/main/java/kr/codesquad/airbnb/service/LodgingService.java
  src/main/java/kr/codesquad/airbnb/service/MainService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/kr/codesquad/airbnb/AirbnbApplicationTests.java
Labels: review-BE

#90 [Team-03][BE] airbnb 프로젝트 PR
  be/build.gradle
  be/src/main/java/teamproject/airbnb/AirbnbApplication.java
  be/src/main/java/teamproject/airbnb/api/MemberApiController.java
  be/src/main/java/teamproject/airbnb/api/ReservationApiController.java
  be/src/main/java/teamproject/airbnb/api/RoomApiController.java
  be/src/main/java/teamproject/airbnb/domain/Image.java
  be/src/main/java/teamproject/airbnb/domain/Location.java
  be/src/main/java/teamproject/airbnb/domain/Member.java
  be/src/main/java/teamproject/airbnb/domain/Reservation.java
  be/src/main/java/teamproject/airbnb/domain/Review.java
  be/src/main/java/teamproject/airbnb/domain/Room.java
  be/src/main/java/teamproject/airbnb/repository/MemberRepository.java
  be/src/main/java/teamproject/airbnb/repository/RoomRepository.java
  be/src/main/java/teamproject/airbnb/service/MemberService.java
  be/src/main/java/teamproject/airbnb/service/ReservationService.java
  be/src/main/java/teamproject/airbnb/service/RoomQuantityDto.java
  be/src/main/java/teamproject/airbnb/service/RoomService.java
  be/src/main/resources/application.properties
  be/src/main/resources/application.yml
Labels: review-BE

#93 [Team-12][BE][동기&루이] - API 설계 마무리
  BE/src/main/java/louie/dong/airbnb/banner/BannerController.java
  BE/src/main/java/louie/dong/airbnb/controller/AccommodationController.java
  BE/src/main/java/louie/dong/airbnb/controller/PopularDestinationController.java
  BE/src/main/java/louie/dong/airbnb/dto/SearchCountryResponse.java
  BE/src/main/java/louie/dong/airbnb/region/MockRegionService.java
  BE/src/main/java/louie/dong/airbnb/region/RegionController.java
  BE/src/main/java/louie/dong/airbnb/region/dto/SearchRegionResponse.java
  BE/src/main/java/louie/dong/airbnb/service/MockAccommodationService.java
  BE/src/main/java/louie/dong/airbnb/service/MockPopularDestinationService.java
  BE/src/main/java/louie/dong/airbnb/travel/MockTravelService.java
  BE/src/main/java/louie/dong/airbnb/travel/TravelController.java
  BE/src/main/java/louie/dong/airbnb/travel/dto/PopularTravelResponse.java
Labels: review-BE

#74 [Team-15][BE] 포키&나단의 airbnb 프로젝트 PR2
  backend/build.gradle
  backend/src/main/java/team15/airbnb/domain/BaseEntity.java
  backend/src/main/java/team15/airbnb/domain/Favorite.java
  backend/src/main/java/team15/airbnb/domain/Reservation.java
  backend/src/main/java/team15/airbnb/domain/Review.java
  backend/src/main/java/team15/airbnb/domain/User.java
  backend/src/main/java/team15/airbnb/domain/UserType.java
  backend/src/main/java/team15/airbnb/domain/accommodation/Accommodation.java
  backend/src/main/java/team15/airbnb/domain/accommodation/AccommodationDetails.java
  backend/src/main/java/team15/airbnb/domain/accommodation/AccommodationImage.java
  backend/src/main/java/team15/airbnb/domain/accommodation/AccommodationType.java
  backend/src/main/java/team15/airbnb/domain/accommodation/Address.java
  backend/src/main/java/team15/airbnb/domain/accommodation/City.java
  backend/src/main/java/team15/airbnb/domain/accommodation/Country.java
  backend/src/main/java/team15/airbnb/domain/accommodation/DiscountPolicy.java
  backend/src/main/java/team15/airbnb/domain/accommodation/Event.java
  backend/src/main/java/team15/airbnb/domain/accommodation/Region.java
  backend/src/main/java/team15/airbnb/domain/accommodation/Vat.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
Labels: review-BE

#109 [Team 27] Khan & sonya airbnb 1주차 두번째 PR
  airbnb/package-lock.json
  airbnb/package.json
  airbnb/src/assets/data/cityData.js
  airbnb/src/assets/data/footerData.js
  airbnb/src/assets/data/tripData.js
  airbnb/src/assets/image/city/Bucheon.WebP
  airbnb/src/assets/image/city/Daegu.WebP
  airbnb/src/assets/image/city/Daejeon.WebP
  airbnb/src/assets/image/city/Gwangju.WebP
  airbnb/src/assets/image/city/Seoul.WebP
  airbnb/src/assets/image/city/Suwon.WebP
  airbnb/src/assets/image/city/Uijeongbu.WebP
  airbnb/src/assets/image/city/Ulsan.WebP
  airbnb/src/assets/image/city/app.js
  airbnb/src/assets/image/trip/Dog.WebP
  airbnb/src/assets/image/trip/House.WebP
  airbnb/src/assets/image/trip/Nature.WebP
  airbnb/src/assets/image/trip/Water.WebP
  airbnb/src/assets/image/trip/app.js
  airbnb/src/components/Calendar/CalendarBody.jsx
  airbnb/src/components/Calendar/CalendarDates.jsx
  airbnb/src/components/Calendar/CalendarHead.jsx
  airbnb/src/components/Calendar/CalendarModal.jsx
  airbnb/src/components/SearchBar/CheckInOut.jsx
  airbnb/src/components/SearchBar/Personnel.jsx
  airbnb/src/components/SearchBar/Price.jsx
  airbnb/src/components/SearchBar/SearchBar.jsx
  airbnb/src/components/footer/CompanyInfo.jsx
  airbnb/src/components/footer/Content.jsx
  airbnb/src/components/footer/Footer.jsx
  airbnb/src/components/header/Logo.jsx
  airbnb/src/components/header/UpperMenu.jsx
  airbnb/src/components/main/CityInfo.jsx
  airbnb/src/components/main/Main.jsx
  airbnb/src/components/main/TripInfo.jsx
  airbnb/src/style/globalStyles.js
  airbnb/src/style/theme.js
Labels: review-FE

#61 [Team-07][iOS] 검색, 검색결과 화면 UI 구성
  iOS/.gitignore
  iOS/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/Airbnb/Home/HomeViewController.swift
  iOS/Airbnb/Info.plist
  iOS/Airbnb/Search/ConditionCategory.swift
  iOS/Airbnb/Search/ConditionSettingTableViewCell.swift
  iOS/Airbnb/Search/ConditionSettingTableViewDataSource.swift
  iOS/Airbnb/Search/ConditionSettingViewController.swift
  iOS/Airbnb/Search/PositionSearchFactory.swift
  iOS/Airbnb/Search/PositionSearchModel.swift
  iOS/Airbnb/Search/PositionSearchViewController.swift
  iOS/Airbnb/SearchResult/MapViewController.swift
  iOS/Airbnb/SearchResult/SearchResultRoomsViewController.swift
  iOS/Airbnb/Supportings/AppDelegate.swift
  iOS/Airbnb/Supportings/SceneDelegate.swift
  iOS/Airbnb/ViewController.swift
  iOS/AirbnbTests/PositionSearchModelTest.swift
Labels: review-iOS

#116 [team-21] 데이먼 1주차 2번째 PR 요청
  BE/src/main/java/team21/airbnb/controller/HomeController.java
  BE/src/main/java/team21/airbnb/controller/RoomController.java
  BE/src/main/java/team21/airbnb/domain/Booking.java
  BE/src/main/java/team21/airbnb/domain/Room.java
  BE/src/main/java/team21/airbnb/dto/request/RoomChargeDistributionRequest.java
  BE/src/main/java/team21/airbnb/repository/BookingRepository.java
  BE/src/main/java/team21/airbnb/repository/RoomRepository.java
  BE/src/main/java/team21/airbnb/service/RoomService.java
  BE/src/test/java/team21/airbnb/controller/HomeControllerTest.java
  BE/src/test/java/team21/airbnb/controller/RoomControllerTest.java
  BE/src/test/java/team21/airbnb/repository/RoomRepositoryTest.java
  BE/src/test/java/team21/airbnb/service/RoomServiceTest.java
Labels: review-BE

#101 [Team-05][BE] 비씨 & 노리 airbnb 프로젝트 1주차 두 번째 PR
  .github/ISSUE_TEMPLATE/------.md
  Backend/build.gradle
  Backend/src/main/java/project/airbnb/bnb/Address.java
  Backend/src/main/java/project/airbnb/bnb/Bnb.java
  Backend/src/main/java/project/airbnb/bnb/BnbOption.java
  Backend/src/main/java/project/airbnb/bnb/BnbRepository.java
  Backend/src/main/java/project/airbnb/bnb/BnbType.java
  Backend/src/main/java/project/airbnb/bnb/Time.java
  Backend/src/main/java/project/airbnb/bnbImage/BnbImage.java
  Backend/src/main/java/project/airbnb/bnbImage/BnbImageRepository.java
  Backend/src/main/java/project/airbnb/member/Member.java
  Backend/src/main/java/project/airbnb/member/MemberRepository.java
  Backend/src/main/java/project/airbnb/reservation/Reservation.java
  Backend/src/main/java/project/airbnb/reservation/ReservationController.java
  Backend/src/main/java/project/airbnb/reservation/ReservationRepository.java
  Backend/src/main/java/project/airbnb/reservation/ReservationService.java
  Backend/src/main/java/project/airbnb/reservation/SimpleReservationDto.java
  Backend/src/main/java/project/airbnb/user/Member.java
  Backend/src/main/java/project/airbnb/wishlist/Wish.java
  Backend/src/main/java/project/airbnb/wishlist/WishDto.java
  Backend/src/main/resources/application-nori.yml
  Backend/src/main/resources/sql/data.sql
  Backend/src/test/java/project/airbnb/reservation/ReservationControllerTest.java
  README.md
Labels: review-BE

#94 [Team-33][bangtae & 포키] 1주차 금요일 PR
  airbnb-app/config-overrides.js
  airbnb-app/jsconfig.json
  airbnb-app/jsconfig.paths.json
  airbnb-app/package-lock.json
  airbnb-app/package.json
  airbnb-app/src/App.js
  airbnb-app/src/common/globalStyle.js
  airbnb-app/src/component/GNB.jsx
  airbnb-app/src/component/gnb/AccountMenu.jsx
  airbnb-app/src/component/gnb/GNB.jsx
  airbnb-app/src/component/gnb/Logo.jsx
  airbnb-app/src/component/gnb/MenuTabs.jsx
  airbnb-app/src/component/main-banner/MainBanner.jsx
  airbnb-app/src/component/search-bar/ResetButton.jsx
  airbnb-app/src/component/search-bar/SearchBar.jsx
  airbnb-app/src/component/search-bar/SearchButton.jsx
  airbnb-app/src/component/search-bar/SearchInput.jsx
  airbnb-app/src/constants/searchBarText.js
  airbnb-app/src/index.js
Labels: review-FE

#69 [team-31][FE] Muffin & Park 1주차 금요일 PR
  package-lock.json
  package.json
  src/App.tsx
  src/assets/hero-img.png
  src/common/theme.tsx
  src/components/Background.tsx
  src/components/FlexBox.tsx
  src/components/Footer/Copyright.tsx
  src/components/Footer/FooterBottom.tsx
  src/components/Footer/FooterItems.tsx
  src/components/Footer/index.tsx
  src/components/Header/BigSearchBar.tsx
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/components/Header/BigSearchBar/BigMenus.tsx
  src/components/Header/BigSearchBar/index.tsx
  src/components/Header/Category.tsx
  src/components/Header/MiniSearchBar/Menu.tsx
  src/components/Header/MiniSearchBar/Menus.tsx
  src/components/Header/MiniSearchBar/index.tsx
  src/components/Header/UserInfo.tsx
  src/components/Header/index.tsx
  src/components/Main/AnyWhereBox.tsx
  src/components/Main/NearByBox.tsx
  src/constants/fontSize.ts
  src/contexts/HeaderProvider.tsx
  src/hooks/useScroll.tsx
  src/mocks/footer.js
  src/mocks/main.js
  src/pages/MainPage.tsx
  src/types/images.d.ts
  src/types/theme.d.ts
  tsconfig.json
  webpack.config.js
Labels: review-FE

#96 [TEAM-25] Airbnb 1주차 2번째 PR Nick + Benny
  .eslintrc.js
  package-lock.json
  package.json
  public/assets/images/menu.svg
  public/assets/images/search.svg
  public/assets/images/user.svg
  public/assets/images/x-circle.svg
  public/index.html
  src/App.tsx
  src/common/global.ts
  src/common/portal.ts
  src/common/styled.d.ts
  src/common/theme.ts
  src/common/util.styled.ts
  src/common/utils.js
  src/components/Calendar/Calendar.styled.ts
  src/components/Calendar/Calendar.tsx
  src/components/Check/Check.styled.ts
  src/components/Check/Check.tsx
  src/components/Fare/Fare.styled.ts
  src/components/Fare/Fare.tsx
  src/components/GNB/GNB.styeld.js
  src/components/GNB/GNB.styled.ts
  src/components/GNB/GNB.tsx
  src/components/Header/Header.styled.ts
  src/components/Header/Header.tsx
  src/components/Hero/Hero.styled.js
  src/components/Hero/Hero.styled.ts
  src/components/Hero/Hero.tsx
  src/components/InputText/InputText.styled.ts
  src/components/InputText/InputText.tsx
  src/components/Menu/Menu.styled.ts
  src/components/Menu/Menu.tsx
  src/components/Personnel/Personnel.styled.ts
  src/components/Personnel/Personnel.tsx
  src/components/Search/Search.styeld.ts
  src/components/Search/Search.tsx
  src/constant/constant.js
  src/constant/constant.ts
  src/index.tsx
  src/pages/Home/Home.styled.ts
  src/pages/Home/Home.tsx
  src/pages/Rooms/Rooms.styled.js
  src/pages/Rooms/Rooms.styled.ts
  src/pages/Rooms/Rooms.tsx
Labels: review-FE

#81 [Team20][FE] Airbnb 1-2 Calendar 구현
  fe/package-lock.json
  fe/package.json
  fe/src/Temp.tsx
  fe/src/components/Calendar/DayCell.tsx
  fe/src/components/Calendar/DayRow.tsx
  fe/src/components/Calendar/Days.tsx
  fe/src/components/Calendar/MonthTable.tsx
  fe/src/components/Calendar/WeekDay.tsx
  fe/src/components/Calendar/context/PickedDateUnits/index.tsx
  fe/src/components/Calendar/hooks/useDayCell.tsx
  fe/src/components/Calendar/index.tsx
  fe/src/components/Calendar/theme.ts
  fe/src/components/Calendar/utils/index.ts
  fe/src/components/SearchBar/BigSearchBar/style.ts
  fe/src/components/SearchBar/SmallSearchBar/style.ts
  fe/src/styles/GlobalStyle.tsx
  fe/src/styles/mixin.ts
Labels: review-FE

#104 [Team-01] [FE/호이] 1주차 두번째 PR
  fe/src/App.tsx
  fe/src/Components/Calendar/Calendar.styled.ts
  fe/src/Components/Calendar/Calendar.tsx
  fe/src/Components/Calendar/Month/Day/Day.styled.ts
  fe/src/Components/Calendar/Month/Day/Day.tsx
  fe/src/Components/Calendar/Month/Month.styled.ts
  fe/src/Components/Calendar/Month/Month.tsx
  fe/src/Components/CalendarModal/Calendar/Calendar.styled.ts
  fe/src/Components/CalendarModal/Calendar/Calendar.tsx
  fe/src/Components/CalendarModal/CalendarModal.styled.ts
  fe/src/Components/CalendarModal/CalendarModal.tsx
  fe/src/Components/Common/styled.tsx
  fe/src/Components/Gnb/Gnb.styled.ts
  fe/src/Components/SearchBar/SearchBar.styled.ts
  fe/src/Components/SearchBar/SearchBar.tsx
  fe/src/Context/CalendarProvider.tsx
  fe/src/Helpers/interface.ts
  fe/src/Helpers/utils.tsx
  fe/src/Hook/useCalendar.ts
  fe/src/Pages/Home/Home.styled.tsx
  fe/src/Pages/Home/Home.tsx
Labels: review-FE

#88 [Team - 06][BE] 에어비앤비 프로젝트 1주차 2회차 PR
  .github/ISSUE_TEMPLATE/-be--feature-request.md
  .github/ISSUE_TEMPLATE/-ios--feture-request.md
  .github/workflows/main.yml
  BE/README.md
  BE/appspec.yml
  BE/build.gradle
  BE/src/main/java/com/airbnb/api/houses/HouseController.java
  BE/src/main/java/com/airbnb/api/houses/dto/HouseDetailResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/HouseListResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/ImageResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/SearchConditionRequest.java
  BE/src/main/java/com/airbnb/api/search/SearchController.java
  BE/src/main/java/com/airbnb/api/search/dto/SearchConditionRequest.java
  BE/src/main/java/com/airbnb/domain/DiscountPolicy.java
  BE/src/main/java/com/airbnb/domain/House.java
  BE/src/main/java/com/airbnb/domain/HouseDiscountPolicy.java
  BE/src/main/java/com/airbnb/domain/Image.java
  BE/src/main/java/com/airbnb/domain/Position.java
  BE/src/main/java/com/airbnb/domain/Reservation.java
  BE/src/main/java/com/airbnb/domain/Role.java
  BE/src/main/java/com/airbnb/domain/User.java
  BE/src/main/java/com/airbnb/domain/WishList.java
  BE/src/main/java/com/airbnb/repository/HouseCustomRepository.java
  BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
  BE/src/main/java/com/airbnb/repository/HouseRepository.java
  BE/src/main/java/com/airbnb/repository/UserRepository.java
  BE/src/main/java/com/airbnb/service/HouseService.java
  BE/src/main/java/com/airbnb/utils/CardinalDirection.java
  BE/src/main/java/com/airbnb/utils/GeometryUtils.java
  BE/src/main/resources/application.yml
  BE/src/test/java/com/airbnb/repository/HouseRepositoryTest.java
  BE/src/test/java/com/airbnb/service/HouseServiceTest.java
  BE/src/test/resources/application.yml
Labels: review-BE

#117 [Team 28 FE Maeve & JinJeon] Airbnb 프로젝트 1주차(금요일) PR
  .eslintrc.json
  src/App.tsx
  src/Component/Header/GNB/GNB.styled.tsx
  src/Component/Header/GNB/GNB.tsx
  src/Component/Header/Header.tsx
  src/Component/Header/Modal/GuestsDetail.tsx
  src/Component/Header/Modal/Modal.styled.tsx
  src/Component/Header/Modal/Modal.tsx
  src/Component/Header/SearchBar/Guest/Guest.styled.tsx
  src/Component/Header/SearchBar/Guest/Guest.tsx
  src/Component/Header/SearchBar/Price/Price.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.tsx
  src/Component/Header/SearchBar/SearchBar.styled.tsx
  src/Component/Header/SearchBar/SearchBar.tsx
  src/Context/GuestsContext.tsx
  src/Context/modalContext.tsx
  src/Styles/Normalize.jsx
  src/Styles/Reset.jsx
  src/Styles/index.jsx
  src/Styles/theme.js
  src/util/Icons.tsx
Labels: review-FE

#111 [Team-19][BE][Hwi&Jun] - 1주차 2번째 PR 요청
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactoring-.md
  .github/PULL_REQUEST_TEMPLATE.md
  Backend/.gitignore
  Backend/README.md
  Backend/build.gradle
  Backend/gradle/wrapper/gradle-wrapper.jar
  Backend/gradle/wrapper/gradle-wrapper.properties
  Backend/gradlew
  Backend/gradlew.bat
  Backend/settings.gradle
  Backend/src/main/java/com/example/airbnb/AirbnbApplication.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Accommodation.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/AccommodationOptionLine.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/AccommodationType.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Address.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/AmenityCategory.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/AmenitySubCategory.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/City.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Comment.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Image.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Location.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Room.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/member/Gender.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/member/Member.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/member/Role.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/member/Wish.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/reservation/Reservation.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/reservation/ReservationStatus.java
  Backend/src/main/java/com/example/airbnb/business/core/domain/reservation/Time.java
  Backend/src/main/java/com/example/airbnb/business/core/repository/accommodation/AccommodationRepository.java
  Backend/src/main/java/com/example/airbnb/business/core/repository/member/MemberRepository.java
  Backend/src/main/java/com/example/airbnb/business/core/repository/reservation/ReservationRepository.java
  Backend/src/main/java/com/example/airbnb/business/web/controller/AccommodationController.java
  Backend/src/main/java/com/example/airbnb/business/web/controller/AccommodationDetailResponse.java
  Backend/src/main/java/com/example/airbnb/business/web/controller/MemberController.java
  Backend/src/main/java/com/example/airbnb/business/web/controller/MemberDetailResponse.java
  Backend/src/main/java/com/example/airbnb/business/web/controller/ReservationController.java
  Backend/src/main/java/com/example/airbnb/business/web/service/AccommodationService.java
  Backend/src/main/java/com/example/airbnb/business/web/service/MemberService.java
  Backend/src/main/java/com/example/airbnb/business/web/service/ReservationService.java
  Backend/src/main/java/com/example/airbnb/common/BusinessException.java
  Backend/src/main/java/com/example/airbnb/common/ClientRegistration.java
  Backend/src/main/java/com/example/airbnb/common/configuration/JpaConfiguration.java
  Backend/src/main/java/com/example/airbnb/common/configuration/OauthClientProperties.java
  Backend/src/main/java/com/example/airbnb/common/exception/BaseExceptionType.java
  Backend/src/main/java/com/example/airbnb/common/exception/accommodation/AccommodationTypeException.java
  Backend/src/main/java/com/example/airbnb/common/exception/accommodation/CityTypeException.java
  Backend/src/main/java/com/example/airbnb/common/exception/member/MemberTypeException.java
  Backend/src/main/java/com/example/airbnb/common/login/LoginController.java
  Backend/src/main/java/com/example/airbnb/common/login/LoginService.java
  Backend/src/main/java/com/example/airbnb/common/login/controller/LoginController.java
  Backend/src/main/java/com/example/airbnb/common/login/controller/dto/LoginResponse.java
  Backend/src/main/java/com/example/airbnb/common/login/service/GithubLoginService.java
  Backend/src/main/java/com/example/airbnb/common/login/service/LoginService.java
  Backend/src/main/resources/application.yml
  Backend/src/main/resources/sql/schema.sql
  Backend/src/test/java/com/example/airbnb/AirbnbApplicationTests.java
Labels: review-BE

#98 [Team22][FE]1주차 금요일 pr
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/Header/Menu.tsx
  fe/src/components/Header/MiniSearchBar/index.tsx
  fe/src/components/Header/SearchBar/Period.tsx
  fe/src/components/Header/SearchBar/Personnel.tsx
  fe/src/components/Header/SearchBar/Price.tsx
  fe/src/components/Header/SearchBar/SearchButton.tsx
  fe/src/components/Header/SearchBar/index.tsx
  fe/src/components/Header/SearchBar/searchBar.styled.js
  fe/src/components/Header/index.tsx
  fe/src/components/HotelList/Hotel.tsx
  fe/src/components/HotelList/index.tsx
  fe/src/components/Map/index.tsx
  fe/src/components/Modals/PeriodModal.tsx
  fe/src/components/Modals/PersonnelModal.tsx
  fe/src/components/Modals/PersonnelModalWrap.tsx
  fe/src/components/Modals/PriceModal.tsx
  fe/src/components/Modals/styled.js
  fe/src/components/Skeleton/Hotel.tsx
  fe/src/pages/Result.jsx
Labels: review-FE

#79 [team04][iOS] Coordinator 패턴 적용
  iOS/airbnb.xcodeproj/project.pbxproj
  iOS/airbnb/App/AppCoordinator.swift
  iOS/airbnb/App/AppDelegate.swift
  iOS/airbnb/App/SceneDelegate.swift
  iOS/airbnb/Common/Coordinator.swift
  iOS/airbnb/Common/Extension/UIColor+Extension.swift
  iOS/airbnb/Present/CustomView/CustomButton.swift
  iOS/airbnb/Present/CustomView/CustomLabel.swift
  iOS/airbnb/Present/Main/MainFlowCoordinator.swift
  iOS/airbnb/Present/Main/MainViewController.swift
  iOS/airbnb/Present/MainTabBarViewController.swift
  iOS/airbnb/Present/Reservation/ReservationViewController.swift
  iOS/airbnb/Present/TabBar/TabBarController.swift
  iOS/airbnb/Present/TabBar/TabBarCoordinator.swift
  iOS/airbnb/Present/WishList/WishListViewController.swift
  iOS/airbnb/SupportingFiles/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/Gray1.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/Gray3.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/Gray5.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/black.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/blue.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/gray2.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/gray4.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/gray6.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/primary.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/secondary.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/color/white.colorset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/images/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/images/img_hero.imageset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/images/img_hero.imageset/img_hero.png
  iOS/airbnb/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  iOS/airbnb/SupportingFiles/Info.plist
Labels: review-iOS

#73 [Team-06][iOS] SearchResult Controller 구현
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.pbxproj
  iOS/AirbnbApp/AirbnbApp/CollectionView/HeartButtonDelegate.swift
  iOS/AirbnbApp/AirbnbApp/CollectionView/MapCardCollectionViewDataSource.swift
  iOS/AirbnbApp/AirbnbApp/CollectionView/MapViewCardCell.swift
  iOS/AirbnbApp/AirbnbApp/Converter/AddressConverter.swift
  iOS/AirbnbApp/AirbnbApp/Extension/NSMutableAttributedString.swift
  iOS/AirbnbApp/AirbnbApp/Info.plist
  iOS/AirbnbApp/AirbnbApp/Map/HouseInfo.swift
  iOS/AirbnbApp/AirbnbApp/Map/ListButtonDelegate.swift
  iOS/AirbnbApp/AirbnbApp/Map/MapView.swift
  iOS/AirbnbApp/AirbnbApp/Map/MapViewCardCell.swift
  iOS/AirbnbApp/AirbnbApp/Map/MapViewController.swift
  iOS/AirbnbApp/AirbnbApp/Map/PriceAnnotationView.swift
  iOS/AirbnbApp/AirbnbApp/Map/PriceLabel.swift
  iOS/AirbnbApp/AirbnbApp/ReuseableView/HeartButton.swift
  iOS/AirbnbApp/AirbnbApp/ReuseableView/HouseImageView.swift
  iOS/AirbnbApp/AirbnbApp/ReuseableView/HouseNameLabel.swift
  iOS/AirbnbApp/AirbnbApp/ReuseableView/PricePerDayLabel.swift
  iOS/AirbnbApp/AirbnbApp/ReuseableView/ReviewLabel.swift
  iOS/AirbnbApp/AirbnbApp/SearchResult/SearchResultViewController.swift
  iOS/AirbnbApp/AirbnbApp/SearchResult/TableView/ResultCardCell.swift
  iOS/AirbnbApp/AirbnbApp/SearchResult/TableView/SearchResultTableViewDataSource.swift
  iOS/AirbnbApp/AirbnbApp/SupportingFiles/Constants.swift
  iOS/AirbnbApp/AirbnbApp/SupportingFiles/SceneDelegate.swift
Labels: review-iOS

#68 [Team-26][FE][이든&도리] 1주차 02 PR 요청
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/Calendar/index.tsx
  FE/src/components/Calendar/style.js
  FE/src/components/CalendarModal/index.tsx
  FE/src/components/CanvasLineCharts/index.tsx
  FE/src/components/Card.tsx
  FE/src/components/SVGLineChart/index.tsx
  FE/src/components/WindowModal/Portal/index.tsx
  FE/src/components/WindowModal/index.tsx
  FE/src/components/WindowModal/style.js
  FE/src/constants/constants.js
  FE/src/hooks/useToggle.ts
  FE/src/index.tsx
  FE/webpack.common.js
  FE/webpack.development.js
  FE/webpack.production.js
Labels: review-FE

#108 [team-36 / dony & yellow] 1주차 2번째 PR 요청드립니다.
  package.json
  src/GlobalStyles.js
  src/assets/images/icon_search.svg
  src/assets/images/icon_xCircle.svg
  src/components/Header/GNB.style.tsx
  src/components/Header/TopBar.style.tsx
  src/components/Header/TopBar.tsx
  src/components/Header/index.style.tsx
  src/components/Header/index.tsx
  src/components/Modal/PriceModal.style.tsx
  src/components/Modal/PriceModal.tsx
  src/components/Modal/index.style.tsx
  src/components/Modal/index.tsx
  src/components/SearchBar/SearchInputButton.style.tsx
  src/components/SearchBar/SearchInputButton.tsx
  src/components/SearchBar/index.style.tsx
  src/components/SearchBar/index.tsx
  src/components/common/IconButton.style.tsx
  src/components/common/IconButton.tsx
  src/constants/color.ts
  src/constants/font.ts
  src/constants/index.ts
  src/mockData/accommodations.js
  src/pages/index.tsx
  tsconfig.paths.json
  yarn.lock
Labels: review-FE

#87 [team-14 BE] airbnb 프로젝트 1주차 두 번째 PR 입니다.
  .github/workflows/gradle.yml
  backend/Dockerfile
  backend/src/main/resources/application-local.yml
Labels: review-BE

#105 [Team 21] Hemdi & Jimmy airbnb 1주차 두번째 PR
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/assets/Images/hero-img.png
  FE/src/components/Icons/DeleteIcon.tsx
  FE/src/components/Icons/LeftArrowIcon.tsx
  FE/src/components/Icons/Logo.tsx
  FE/src/components/Icons/MenuIcon.tsx
  FE/src/components/Icons/MinusIcon.tsx
  FE/src/components/Icons/PauseIcon.tsx
  FE/src/components/Icons/PlusIcon.tsx
  FE/src/components/Icons/RightArrowIcon.tsx
  FE/src/components/Icons/SearchIcon.tsx
  FE/src/components/Icons/StarIcon.tsx
  FE/src/components/Icons/UserIcon.tsx
  FE/src/components/Icons/heartIcon.tsx
  FE/src/components/header/gnb/gnb.style.js
  FE/src/components/header/gnb/index.tsx
  FE/src/components/header/gnb/loginMenu/index.tsx
  FE/src/components/header/gnb/loginMenu/logInMenu.style.js
  FE/src/components/header/gnb/menuBar/index.tsx
  FE/src/components/header/gnb/menuBar/menubar.style.js
  FE/src/components/header/header.style.js
  FE/src/components/header/index.tsx
  FE/src/components/header/searchBar/index.tsx
  FE/src/components/header/searchBar/searchBar.style.js
  FE/src/components/header/searchBar/searchBarItem/index.tsx
  FE/src/components/header/searchBar/searchBarItem/searchBarItem.style.js
  FE/src/index.tsx
  FE/src/pages/index.tsx
  FE/src/styles/DefaultStyle.js
  FE/src/styles/GlobalStyle.js
  FE/tsconfig.json
Labels: review-FE

#89 [Team-35][FE] 1주차 두번째 PR
  config/webpack.common.js
  package-lock.json
  src/App.tsx
  src/UI/Input.tsx
  src/UI/SearchBarSection.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderBackdrop.tsx
  src/components/SerachBar/Period.tsx
  src/components/SerachBar/Personnel.tsx
  src/components/SerachBar/Price.tsx
  src/components/SerachBar/SearchBar.tsx
  src/components/calendar/CalendarModal.tsx
  src/components/calendar/MonthTBody.tsx
  src/components/calendar/MonthTHead.tsx
  src/components/calendar/MonthTable.tsx
  src/components/calendar/WeekTRow.tsx
  src/constants/constants.tsx
  src/pages/MainPage.tsx
  src/store/CalendarContext.tsx
  src/store/CalendarProvider.tsx
  src/store/calendarReducer.tsx
  src/style/theme.ts
  src/types/types.tsx
  src/util/calenderUtil.tsx
Labels: review-FE

#67 [Team-08][BE][후&아더] - 프로젝트 셋팅, MockService 구현, Swagger 적용, CI/CD 기능 완성
  .github/workflows/gradle.yml
  BE/.gitignore
  BE/Dockerfile
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/ahoo/airbnb/AirbnbApplication.java
  BE/src/main/java/com/ahoo/airbnb/config/SwaggerConfig.java
  BE/src/main/java/com/ahoo/airbnb/member/MemberResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/MockReservationService.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationController.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ChargesResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationRequest.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationsResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeRequest.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeResponse.java
  BE/src/main/java/com/ahoo/airbnb/room/Address.java
  BE/src/main/java/com/ahoo/airbnb/room/Image.java
  BE/src/main/java/com/ahoo/airbnb/room/Images.java
  BE/src/main/java/com/ahoo/airbnb/room/MockRoomService.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomCondition.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomController.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomDetailResponse.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomRequest.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomResponse.java
  BE/src/main/java/com/ahoo/airbnb/wish/MockWishService.java
  BE/src/main/java/com/ahoo/airbnb/wish/WishController.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/ahoo/airbnb/AirbnbApplicationTests.java
Labels: review-BE

#72 [Team-19][AOS] [ Linus& 히데 Airbnb 첫번째주 금요일 PR ] 달력 화면 일부 구현
  app/build.gradle
  app/src/main/java/com/example/airbnb/common/Constants.kt
  app/src/main/java/com/example/airbnb/data/RepositoryImpl.kt
  app/src/main/java/com/example/airbnb/domain/Repository.kt
  app/src/main/java/com/example/airbnb/domain/model/CalendarDay.kt
  app/src/main/java/com/example/airbnb/ui/calendar/CalendarFragment.kt
  app/src/main/java/com/example/airbnb/ui/calendar/CalendarViewModel.kt
  app/src/main/java/com/example/airbnb/ui/calendar/DayAdapter.kt
  app/src/main/java/com/example/airbnb/ui/calendar/MonthAdapter.kt
  app/src/main/java/com/example/airbnb/ui/common/CalendarUtil.kt
  app/src/main/java/com/example/airbnb/ui/common/ImageBindingAdapter.kt
  app/src/main/java/com/example/airbnb/ui/common/Util.kt
  app/src/main/java/com/example/airbnb/ui/home/HomeFragment.kt
  app/src/main/java/com/example/airbnb/ui/information/InformationInputFragment.kt
  app/src/main/java/com/example/airbnb/ui/login/LoginFragment.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_information_input.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/item_calendar_month.xml
  app/src/main/res/navigation/navigation_information.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: review-android

#66 [Team 18-Android] 피드백 반영 및 추가로직
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/todo/airbnb/common/components/HadleImage.kt
  app/src/main/java/com/example/todo/airbnb/data/Travel.kt
  app/src/main/java/com/example/todo/airbnb/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/example/todo/airbnb/domain/repository/MainRepository.kt
  app/src/main/java/com/example/todo/airbnb/presentation/main/components/BottomBar.kt
  app/src/main/java/com/example/todo/airbnb/presentation/main/components/MainScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/SearchViewModel.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/AccommodationsScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/LoadMainImage.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/SearchScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/TopBar.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/TravelScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/date/DateScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/components/navigation/SearchNavigation.kt
Labels: review-android

#110 [Android] Team 15 - 캘린더, 가격 그래프 화면 구현
  android/app/src/main/java/com/example/airbnb/data/repository/DataSourceImpl.kt
  android/app/src/main/java/com/example/airbnb/ui/PriceSettingFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/calendar/CalendarFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/common/ShowCalendarListener.kt
  android/app/src/main/java/com/example/airbnb/ui/placesearch/PlaceSearchAdapter.kt
  android/app/src/main/java/com/example/airbnb/ui/placesearch/PlaceSearchFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/search/SearchCloseTravelAdapter.kt
  android/app/src/main/java/com/example/airbnb/ui/search/SearchFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/search/ViewModel.kt
  android/app/src/main/res/layout/fragment_calendar.xml
  android/app/src/main/res/layout/fragment_place_search.xml
  android/app/src/main/res/layout/fragment_price_setting.xml
Labels: review-android

#70 [team11][iOS] - 장소 검색 화면 / 날짜 지정 화면 구현 (1주차 금요일 PR)
  iOS/Airbnb_iOS/Airbnb_iOS.xcodeproj/project.pbxproj
  iOS/Airbnb_iOS/Airbnb_iOS/Model/Data/DateData.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Model/UseCase/FindAccomodationUseCase.swift
  iOS/Airbnb_iOS/Airbnb_iOS/View/BrowseView/BrowsingSpotCell.swift
  iOS/Airbnb_iOS/Airbnb_iOS/View/BrowseView/BrowsingSpotCollectionView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/View/BrowseView/FamousSpotCollectionView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/View/FindAccomodationView/FindAccomodationView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/View/FindAccomodationView/SelectCalendarView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/ViewController/BrowsingVC/BrowseViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/ViewController/FindAccomodationVC/FindAccomodationViewController.swift
Labels: review-iOS

#75 [Team-08][iOS] Calendar Model 생성 / CollectionView HeaderCell 추가 작업
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb/Search/BackgroundViewController.swift
  iOS/Airbnb/Airbnb/Search/DTO/SearchDayDTO.swift
  iOS/Airbnb/Airbnb/Search/Model/SearchCalendarModel.swift
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/HeaderReusableView.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/LocationCollectionViewCell.swift
  iOS/Airbnb/Airbnb/Source/Assets.xcassets/mockImage.imageset/Contents.json
  iOS/Airbnb/Airbnb/Source/Assets.xcassets/mockImage.imageset/mockImage.png
  iOS/Airbnb/AirbnbTests/AirbnbCalendarModelTests.swift
Labels: review-iOS

#86 [Team14] 여행지 추천 및 자동 완성 검색 기능 구현
  iOS/.swiftlint.yml
  iOS/Plugins/Cherrybnb/Package.swift
  iOS/Plugins/Cherrybnb/Sources/tuist-my-cli/main.swift
  iOS/Podfile
  iOS/Podfile.lock
  iOS/Project.swift
  iOS/Targets/Cherrybnb/Resources/Main.storyboard
  iOS/Targets/Cherrybnb/Sources/Common/Calendar+Extension.swift
  iOS/Targets/Cherrybnb/Sources/Search/View/CalendarPickerCollectionViewCell.swift
  iOS/Targets/Cherrybnb/Sources/Search/View/PlaceCell.swift
  iOS/Targets/Cherrybnb/Sources/Search/ViewController/ListCollectionViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Controller/CalendarPickerViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Model/CalendarPicker.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Model/Month.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/View/CalendarPickerViewCell.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/View/CalendarPickerViewSectionHeader.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/ListCollectionViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/SearchRootViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Model/DefaultRecommendator.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Model/HTTPService.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/View/LocationCell.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/View/PlaceCell.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/View/SearchView.swift
  iOS/Targets/Cherrybnb/Sources/Support/AppDelegate.swift
  iOS/Tuist/Config.swift
  iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: review-iOS

#64 [Team-13][BE][제리&쿠킴] - Event, Place 기능 구현
  BE/src/main/java/team13/kuje/airbnb/domain/Place.java
  BE/src/main/java/team13/kuje/airbnb/domain/Position.java
  BE/src/main/java/team13/kuje/airbnb/repository/PlaceRepository.java
  BE/src/main/java/team13/kuje/airbnb/service/EventService.java
  BE/src/main/java/team13/kuje/airbnb/service/PlaceService.java
  BE/src/main/java/team13/kuje/airbnb/util/MapUtils.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/EventAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/PlaceAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/PlaceTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/PositionTest.java
  BE/src/test/java/team13/kuje/airbnb/service/EventServiceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/PlaceServiceTest.java
Labels: review-BE

#95 [Team-16] [Android] [PR-2] 홈 화면 컴포즈로 구현
  Android/app/src/main/java/com/team16/airbnb/ui/HomeFragment.kt
  Android/app/src/main/java/com/team16/airbnb/ui/search/SearchFragment.kt
  Android/app/src/main/res/drawable/ic_back.xml
  Android/app/src/main/res/drawable/ic_close.xml
  Android/app/src/main/res/layout/fragment_search.xml
  Android/app/src/main/res/layout/item_search_area.xml
  Android/app/src/main/res/layout/item_search_description.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/themes.xml
Labels: review-android

#144 [Team-16][BE][Yanse] airbnb 프로젝트 2주차 PR#3
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/yanse/airbnb/domain/image/Image.java
  BE/src/main/java/yanse/airbnb/domain/image/MainImageRepository.java
  BE/src/main/java/yanse/airbnb/domain/image/RoomImage.java
  BE/src/main/java/yanse/airbnb/domain/member/Members.java
  BE/src/main/java/yanse/airbnb/domain/reservation/DetailFee.java
  BE/src/main/java/yanse/airbnb/domain/reservation/Reservation.java
  BE/src/main/java/yanse/airbnb/domain/room/Address.java
  BE/src/main/java/yanse/airbnb/domain/room/Room.java
  BE/src/main/java/yanse/airbnb/domain/room/RoomInfo.java
  BE/src/main/java/yanse/airbnb/domain/room/RoomRepository.java
  BE/src/main/java/yanse/airbnb/domain/room/RoomType.java
  BE/src/main/java/yanse/airbnb/domain/wish/Wish.java
  BE/src/main/java/yanse/airbnb/service/MainService.java
  BE/src/main/java/yanse/airbnb/service/SearchService.java
  BE/src/main/java/yanse/airbnb/type/DiscountPolicy.java
  BE/src/main/java/yanse/airbnb/type/ImageType.java
  BE/src/main/java/yanse/airbnb/type/RoomType.java
  BE/src/main/java/yanse/airbnb/web/controller/MainController.java
  BE/src/main/java/yanse/airbnb/web/controller/SearchController.java
  BE/src/main/java/yanse/airbnb/web/dto/ImageListDto.java
  BE/src/main/java/yanse/airbnb/web/dto/ResponseSearchAddressDto.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
Labels: review-BE

#156 [team-03] 홈화면 ViewModel 구현
  ios/AirBnb/AirBnb.xcodeproj/project.pbxproj
  ios/AirBnb/AirBnb/Application/SceneDelegate.swift
  ios/AirBnb/AirBnb/Domain/Entities/Accommodation.swift
  ios/AirBnb/AirBnb/Domain/Entities/City.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/HomeViewController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/NearCityCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/RecommendationCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/View/HeroCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/View/NearCityCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/View/RecommendationCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/View/TitleSupplementaryView.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/ViewModel/HomeViewModel.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Reservation/ReservationViewController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Search/LocationSearchController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Search/SearchResultViewController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/WishList/WishListViewController.swift
  ios/AirBnb/AirBnb/Presentation/Utils/Extensions/Equatable+Extensions.swift
  ios/AirBnb/AirBnb/Presentation/Utils/Extensions/Hashable+hash.swift
  ios/AirBnb/AirBnb/Presentation/Utils/Extensions/UIView+Extensions.swift
  ios/AirBnb/AirBnb/Presentation/Utils/Observable.swift
  ios/AirBnb/AirBnb/Presentation/Utils/SectionFactory.swift
  ios/AirBnb/Toolbox/Package.swift
Labels: review-iOS

#150 [Team-22][BE][Lee&벅픽] 2주차 1번째 PR - 숙소 검색 쿼리 수정, 숙소 예약 API 구현
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/domain/accommodation/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/domain/accommodation/AccommodationNotFoundException.java
  be/src/main/java/kr/codesquad/airbnb/domain/discountpolicy/DiscountPolicy.java
  be/src/main/java/kr/codesquad/airbnb/domain/member/Member.java
  be/src/main/java/kr/codesquad/airbnb/domain/member/MemberNotFoundException.java
  be/src/main/java/kr/codesquad/airbnb/domain/reservation/Reservation.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveFormResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/exception/CustomException.java
  be/src/main/java/kr/codesquad/airbnb/exception/CustomExceptionHandler.java
  be/src/main/java/kr/codesquad/airbnb/exception/ErrorResponse.java
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/kr/codesquad/airbnb/repository/MemberRepository.java
  be/src/main/java/kr/codesquad/airbnb/repository/ReservationRepository.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
  be/src/main/resources/application.properties
  be/src/main/resources/application.yml
  be/src/main/resources/dml.sql
  be/src/main/resources/logback-spring.xml
Labels: review-BE

#145 [team-33 포키 & bangtae] 2주차 첫번째 pr보냅니다.
  airbnb-app/src/App.js
  airbnb-app/src/component/header/Header.js
  airbnb-app/src/component/header/calender/Calender.jsx
  airbnb-app/src/component/header/calender/CalenderDateProvider.jsx
  airbnb-app/src/component/header/calender/CalenderPage.jsx
  airbnb-app/src/component/header/calender/DateBox.jsx
  airbnb-app/src/component/header/calender/DatesOfMonth.jsx
  airbnb-app/src/component/header/calender/Days.jsx
  airbnb-app/src/component/header/calender/NextButton.jsx
  airbnb-app/src/component/header/calender/PrevButton.jsx
  airbnb-app/src/component/header/gnb/AccountMenu.jsx
  airbnb-app/src/component/header/gnb/GNB.jsx
  airbnb-app/src/component/header/gnb/Logo.jsx
  airbnb-app/src/component/header/gnb/MenuTabs.jsx
  airbnb-app/src/component/header/search-bar/ResetButton.jsx
  airbnb-app/src/component/header/search-bar/SearchBar.jsx
  airbnb-app/src/component/header/search-bar/SearchBarProvider.jsx
  airbnb-app/src/component/header/search-bar/SearchButton.jsx
  airbnb-app/src/component/header/search-bar/SearchInput.jsx
  airbnb-app/src/component/header/search-bar/SearchInputModal.jsx
  airbnb-app/src/component/main-banner/MainBanner.jsx
  airbnb-app/src/component/search-bar/ResetButton.jsx
  airbnb-app/src/component/search-bar/SearchBar.jsx
  airbnb-app/src/component/search-bar/SearchInput.jsx
  airbnb-app/src/constants/calenderText.js
Labels: review-FE

#172 [FE][team-30] 2주차 1번째 PR
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE.md
  airbnb/.eslintignore
  airbnb/.eslintrc.js
  airbnb/package-lock.json
  airbnb/package.json
  airbnb/public/mockServiceWorker.js
  airbnb/src/App.tsx
  airbnb/src/Component/Schedule/Schedule.tsx
  airbnb/src/Components/GNB/AccountMenu.tsx
  airbnb/src/Components/GNB/GNB.tsx
  airbnb/src/Components/GNB/GNBstyle.tsx
  airbnb/src/Components/GNB/Menus.tsx
  airbnb/src/Components/GNB/index.ts
  airbnb/src/Components/Schedule/BaseWeekend.tsx
  airbnb/src/Components/Schedule/CalendarDate.tsx
  airbnb/src/Components/Schedule/CalendarHeader.tsx
  airbnb/src/Components/Schedule/Day.tsx
  airbnb/src/Components/Schedule/Schedule.style.tsx
  airbnb/src/Components/Schedule/Schedule.tsx
  airbnb/src/Components/SearchBar/Item.tsx
  airbnb/src/Components/SearchBar/SearchBar.tsx
  airbnb/src/Components/SearchBar/SearchBarStyle.tsx
  airbnb/src/Components/SearchBar/SearchButton.tsx
  airbnb/src/Components/SearchBar/index.ts
  airbnb/src/Context/Searching/index.tsx
  airbnb/src/Contexts/Searching/context.tsx
  airbnb/src/Contexts/Searching/index.ts
  airbnb/src/Contexts/Searching/reducer.ts
  airbnb/src/Contexts/Searching/types.ts
  airbnb/src/Hooks/SearchBarHooks.ts
  airbnb/src/Pages/Home.tsx
  airbnb/src/index.tsx
  airbnb/src/mocks/browser.js
  airbnb/src/mocks/handlers.js
  airbnb/src/styles/ColorTheme.tsx
  airbnb/src/types/Theme.d.ts
  airbnb/tsconfig.eslint.json
  airbnb/tsconfig.json
  airbnb/tsconfig.paths.json
Labels: review-FE

#162 [Team-17 BE] airbnb 프로젝트 2주차 화요일 PR입니다.
  backend/build.gradle
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/Accommodation.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/AccommodationDetailResponse.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/AccommodationImage.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/AccommodationInfo.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/AccommodationRepository.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/AccommodationType.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/Amenity.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/AmenityType.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/Host.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/Report.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/dto/AccommodationSearchRequest.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/dto/AccommodationsResponse.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/web/AccommodationController.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/web/AccommodationService.java
Labels: review-BE

#171 [FE][Team23][Millie & Oliver] 세 번째 PR
  FE/.eslintrc
  FE/.eslintrc.js
  FE/.prettierrc
  FE/db.json
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/api/core/index.ts
  FE/src/api/mainContents.ts
  FE/src/assets/hero-img.png
  FE/src/components/GNB/GNB.style.ts
  FE/src/components/GNB/Logo.tsx
  FE/src/components/GNB/NavMenu.tsx
  FE/src/components/GNB/ProfileButton.tsx
  FE/src/components/GNB/index.tsx
  FE/src/components/Header/Header.style.ts
  FE/src/components/Header/index.tsx
  FE/src/components/SearchBar/SearchBar.style.ts
  FE/src/components/SearchBar/index.tsx
  FE/src/index.tsx
  FE/src/layout/index.tsx
  FE/src/pages/MainContents/index.tsx
  FE/src/pages/NotFound/index.tsx
  FE/src/pages/SearchResult/index.tsx
  FE/src/styles/GlobalStyle.ts
  FE/src/styles/Normalize.ts
  FE/src/styles/icons.ts
  FE/src/styles/mixins.ts
  FE/src/styles/theme.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: review-FE

#143 [Team-25][BE][Jay] AWS 인프라 & CI/CD 환경 구축 및 숙소 통계 API 반영 PR
  .github/ISSUE_TEMPLATE/------.md
  .github/workflows/ci-dev-be.yml
  .github/workflows/deploy-prod-be.yml
  backend/.gitignore
  backend/Dockerfile
  backend/README.md
  backend/appspec.yml
  backend/build.gradle
  backend/docker-compose.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/scripts/deploy.sh
  backend/settings.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/codesquad/airbnb/AirbnbApplication.java
  backend/src/main/java/codesquad/airbnb/accomodation/AccommodationController.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Accommodation.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Address.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Image.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Provides.java
  backend/src/main/java/codesquad/airbnb/accomodation/dto/PriceAndCount.java
  backend/src/main/java/codesquad/airbnb/accomodation/dto/PriceAndCountStatistics.java
  backend/src/main/java/codesquad/airbnb/accomodation/repository/AccommodationQueryRepository.java
  backend/src/main/java/codesquad/airbnb/accomodation/service/AccommodationStatisticsService.java
  backend/src/main/java/codesquad/airbnb/accomodation/service/AccommodationStatisticsServiceImpl.java
  backend/src/main/java/codesquad/airbnb/accomodation/service/AmountUnitPolicy.java
  backend/src/main/java/codesquad/airbnb/accomodation/service/DummyAccommodationStatisticsService.java
  backend/src/main/java/codesquad/airbnb/config/JasyptConfig.java
  backend/src/main/java/codesquad/airbnb/config/QueryDSLConfig.java
  backend/src/main/java/codesquad/airbnb/exception/AirbnbRuntimeException.java
  backend/src/main/java/codesquad/airbnb/exception/ErrorResponse.java
  backend/src/main/java/codesquad/airbnb/exception/GlobalExceptionHandler.java
  backend/src/main/java/codesquad/airbnb/member/Member.java
  backend/src/main/java/codesquad/airbnb/reservation/Reservation.java
  backend/src/main/java/codesquad/airbnb/reservation/Schedule.java
  backend/src/main/java/codesquad/airbnb/reservation/StartEndDate.java
  backend/src/main/java/codesquad/airbnb/wish/Wish.java
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/application.properties
  backend/src/main/resources/sql/airbnb-schema.sql
  backend/src/test/java/codesquad/airbnb/AirbnbApplicationTests.java
  backend/src/test/java/codesquad/airbnb/ApiDocumentUtils.java
  backend/src/test/java/codesquad/airbnb/accomodation/AccommodationControllerTest.java
  backend/src/test/java/codesquad/airbnb/accomodation/repository/AccommodationQueryRepositoryTest.java
  backend/src/test/java/codesquad/airbnb/accomodation/service/AccommodationStatisticsServiceTest.java
  backend/src/test/java/codesquad/airbnb/config/JasyptConfigTest.java
  backend/src/test/resources/application.properties
  backend/src/test/resources/sql/accommodation-statistics.sql
Labels: review-BE

#133 [Team-09][BE][Dave&K] - 2주차 첫번째 PR
  build.gradle
  src/main/java/kr/codesquad/airbnb/AirbnbApplication.java
  src/main/java/kr/codesquad/airbnb/controller/LodgingController.java
  src/main/java/kr/codesquad/airbnb/controller/MainController.java
  src/main/java/kr/codesquad/airbnb/domain/Images.java
  src/main/java/kr/codesquad/airbnb/domain/Lodging.java
  src/main/java/kr/codesquad/airbnb/domain/Reservation.java
  src/main/java/kr/codesquad/airbnb/dto/LodgingResponse.java
  src/main/java/kr/codesquad/airbnb/dto/LodgingResponseDto.java
  src/main/java/kr/codesquad/airbnb/repository/CustomLodgingRepository.java
  src/main/java/kr/codesquad/airbnb/repository/CustomLodgingRepositoryImpl.java
  src/main/java/kr/codesquad/airbnb/repository/LodgingRepository.java
  src/main/java/kr/codesquad/airbnb/request/SearchLodgingRequest.java
  src/main/java/kr/codesquad/airbnb/service/LodgingService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: review-BE
