Repository codesquad-members-2022/airbnb, pull requests merged in 2022-06, with the labels that each got.

#134 [team-31][FE] Muffin & Park 2주차 수요일 PR
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  src/App.tsx
  src/assets/room_sample.jpg
  src/components/Calendar/MonthCard/CardBody.jsx
  src/components/Calendar/MonthCard/CardTitle.jsx
  src/components/Calendar/MonthCard/ClickableDate.jsx
  src/components/Calendar/MonthCard/index.jsx
  src/components/Calendar/MonthCards.jsx
  src/components/Calendar/MonthNav/LeftArrow.jsx
  src/components/Calendar/MonthNav/RightArrow.jsx
  src/components/Calendar/MonthNav/index.jsx
  src/components/Calendar/index.jsx
  src/components/Chart/index.tsx
  src/components/Footer/FooterBottom.tsx
  src/components/Footer/FooterItems.tsx
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/components/Header/BigSearchBar/BigMenus.tsx
  src/components/Header/BigSearchBar/Modal/index.tsx
  src/components/Header/BigSearchBar/index.tsx
  src/components/Header/MiniSearchBar/Menu.tsx
  src/components/Header/MiniSearchBar/Menus.tsx
  src/constants/widths.ts
  src/contexts/HeaderProvider.tsx
  src/hooks/useScroll.tsx
  src/hooks/useThrottle.jsx
  src/mocks/footer.js
  src/mocks/room.js
  webpack.config.js
Labels: review-FE

#146 [Team23 땃쥐] airbnb 3차 PR
  BE/src/main/java/codesquad/airbnb/accommodation/repository/AccommodationRepository.java
  BE/src/main/java/codesquad/airbnb/accommodation/service/AccommodationCommandService.java
  BE/src/main/java/codesquad/airbnb/accommodation/service/AccommodationQueryService.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/AccommodationController.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationPricesResponse.java
  BE/src/main/java/codesquad/airbnb/booking/domain/BookingGuests.java
  BE/src/main/java/codesquad/airbnb/booking/domain/BookingPeriod.java
  BE/src/main/java/codesquad/airbnb/booking/repository/BookingRepository.java
  BE/src/main/java/codesquad/airbnb/booking/service/BookingCommandService.java
  BE/src/main/java/codesquad/airbnb/booking/service/BookingQueryService.java
  BE/src/main/java/codesquad/airbnb/booking/web/BookingController.java
  BE/src/main/java/codesquad/airbnb/member/repository/MemberRepository.java
  BE/src/main/java/codesquad/airbnb/member/service/MemberCommandService.java
  BE/src/main/java/codesquad/airbnb/member/service/MemberQueryService.java
  BE/src/main/java/codesquad/airbnb/member/web/MemberController.java
  BE/src/main/java/codesquad/airbnb/review/repository/ReviewRepository.java
  BE/src/main/java/codesquad/airbnb/review/service/ReviewCommandService.java
  BE/src/main/java/codesquad/airbnb/review/service/ReviewQueryService.java
  BE/src/main/java/codesquad/airbnb/review/web/ReviewController.java
Labels: review-BE

#163 [Team 32] [J, 럼카] 2주차 1번째 PR 요청드립니다.
  .gitignore
  jsconfig.json
  package-lock.json
  package.json
  public/index.html
  src/components/Calendar/Calendar.jsx
  src/components/Calendar/Day.jsx
  src/components/Calendar/DaysWrap.jsx
  src/components/Calendar/Month.jsx
  src/components/IconButton.jsx
  src/components/Modal/ReservationModal.jsx
  src/components/Modal/SearchBarModal.jsx
  src/components/PriceModal/Canvas.jsx
  src/components/PriceModal/calculate.js
  src/components/PriceModal/index.jsx
  src/components/SearchBar/Filter/FilterBox.jsx
  src/components/SearchBar/Filter/FilterResetButton.jsx
  src/components/SearchBar/Filter/index.tsx
  src/components/SearchBar/FilterContainer.jsx
  src/components/SearchBar/Guest.jsx
  src/components/SearchBar/Price.jsx
  src/components/SearchBar/Schedule.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchButton.jsx
  src/components/calendar/Day.jsx
  src/index.jsx
  src/mockData/accommodation.js
  src/store/FilterContext.jsx
  src/styles/zIndex.ts
  tsconfig.json
Labels: review-FE

#137 [team-21] 데이먼 2주차 1번째 PR 요청
  BE/src/main/java/team21/airbnb/controller/RoomController.java
  BE/src/main/java/team21/airbnb/dto/response/RoomChargeDistributionResponse.java
  BE/src/main/java/team21/airbnb/repository/RoomRepository.java
  BE/src/main/java/team21/airbnb/service/RoomService.java
  BE/src/test/java/team21/airbnb/controller/RoomControllerTest.java
  BE/src/test/java/team21/airbnb/repository/RoomRepositoryTest.java
  BE/src/test/java/team21/airbnb/service/RoomServiceTest.java
Labels: review-BE

#121 [Team-26][FE][이든-도리] 2주차 01 PR 요청
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/Calendar/index.tsx
  FE/src/components/CalendarModal/index.tsx
  FE/src/components/PriceChart/constants.js
  FE/src/components/PriceChart/index.tsx
  FE/src/components/PriceChart/mixins.js
  FE/src/components/PriceChart/style.js
  FE/src/components/WindowModal/Portal/index.tsx
  FE/src/components/WindowModal/index.tsx
  FE/src/components/WindowModal/style.js
  FE/src/constants/constants.js
  FE/src/hooks/useToggle.ts
  FE/webpack.development.js
Labels: review-FE

#131 [Team-06][iOS] Network작업 및 reqeust UnitTest
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.pbxproj
  iOS/AirbnbApp/AirbnbApp.xcodeproj/xcshareddata/xcschemes/AirbnbApp.xcscheme
  iOS/AirbnbApp/AirbnbApp.xcodeproj/xcuserdata/bagjinseob.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/AirbnbApp/AirbnbApp/Delegate/HeartButtonDelegate.swift
  iOS/AirbnbApp/AirbnbApp/Delegate/ListButtonDelegate.swift
  iOS/AirbnbApp/AirbnbApp/Extension/Extensions.swift
  iOS/AirbnbApp/AirbnbApp/Info.plist
  iOS/AirbnbApp/AirbnbApp/Model/HouseInfo.swift
  iOS/AirbnbApp/AirbnbApp/Network/EndPoint.swift
  iOS/AirbnbApp/AirbnbApp/Network/NetworkManagable.swift
  iOS/AirbnbApp/AirbnbApp/Network/NetworkManager.swift
  iOS/AirbnbApp/AirbnbApp/Repository/HouseInfoRepository.swift
  iOS/AirbnbApp/AirbnbApp/ReuseableView/HeartButton.swift
  iOS/AirbnbApp/AirbnbApp/View/CollectionView/MapCardCollectionViewDataSource.swift
  iOS/AirbnbApp/AirbnbApp/View/CollectionView/MapViewCardCell.swift
  iOS/AirbnbApp/AirbnbApp/View/Map/MapView.swift
  iOS/AirbnbApp/AirbnbApp/View/Map/PriceAnnotationView.swift
  iOS/AirbnbApp/AirbnbApp/View/Map/PriceLabel.swift
  iOS/AirbnbApp/AirbnbApp/View/TableView/ResultCardCell.swift
  iOS/AirbnbApp/AirbnbApp/View/TableView/SearchResultTableViewDataSource.swift
  iOS/AirbnbApp/AirbnbApp/ViewController/MainViewController.swift
  iOS/AirbnbApp/AirbnbApp/ViewController/MapViewController.swift
  iOS/AirbnbApp/AirbnbApp/ViewController/SearchResultViewController.swift
  iOS/AirbnbApp/HouseInfoRepositroyUnitTest/HouseInfoRepositroyUnitTest.swift
  iOS/AirbnbApp/NetworkManagerTest/MockData.json
  iOS/AirbnbApp/NetworkManagerTest/MockDataModel.swift
  iOS/AirbnbApp/NetworkManagerTest/NetworkManagerTest.swift
  iOS/AirbnbApp/NetworkManagerTest/URLMockProtocol.swift
Labels: review-iOS

#175 [Team-03] 2주차 첫번째 PR
  fe/public/index.html
  fe/src/App.tsx
  fe/src/Portal.tsx
  fe/src/components/Modal/Modal.tsx
  fe/src/components/SearchBar/Period/Period.tsx
  fe/src/components/SearchBar/Personnel/Personnel.tsx
  fe/src/components/SearchBar/Price/Price.tsx
  fe/src/components/SearchBar/SearchBar.styled.tsx
  fe/src/components/SearchBar/SearchBar.tsx
  fe/src/components/SearchBar/SearchList/SearchList.tsx
  fe/src/components/SearchBar/types.ts
  fe/src/context/ModalProvider.tsx
  fe/src/context/SearchProvider.tsx
  fe/src/img/svg/search-text-icon.svg
  fe/yarn.lock
Labels: review-FE

#161 [Team-34] 베르&쥬 2주차 화요일 PR
  .eslintrc.js
  README.md
  craco.config.js
  package-lock.json
  package.json
  public/fakeDB.json
  src/App.tsx
  src/assets/account-icon.svg
  src/assets/hero-img.png
  src/assets/nextButton.svg
  src/assets/nyancat+adventuretime.gif
  src/assets/pause-icon.svg
  src/assets/prevButton.svg
  src/assets/search-icon.svg
  src/assets/x-icon.svg
  src/components/Calendar/CalendarPage/index.jsx
  src/components/Calendar/CalendarPage/style.js
  src/components/Calendar/index.jsx
  src/components/Calendar/style.js
  src/components/GNB/GNB.tsx
  src/components/GNB/index.tsx
  src/components/GNB/style.ts
  src/components/SearchBar/Period/index.tsx
  src/components/SearchBar/Period/style.ts
  src/components/SearchBar/Personnel/index.tsx
  src/components/SearchBar/Personnel/style.ts
  src/components/SearchBar/Price/index.tsx
  src/components/SearchBar/Price/style.ts
  src/components/SearchBar/index.tsx
  src/components/SearchBar/style.ts
  src/components/common/Icon/index.jsx
  src/components/common/Icon/style.js
  src/components/common/Modal/index.jsx
  src/components/common/Modal/style.js
  src/components/common/TextBox/index.jsx
  src/components/common/TextBox/style.js
  src/constants/calendar.js
  src/constants/data.js
  src/constants/index.js
  src/constants/number.js
  src/custom.d.ts
  src/index.tsx
  src/pages/Main/index.tsx
  src/pages/Main/style.ts
  src/pages/NotFound/index.tsx
  src/pages/SearchResult/index.tsx
  src/pages/SearchResult/style.ts
  src/styles/GlobalStyles.ts
  src/styles/fonts/Dongle-Regular.woff
  src/styles/fonts/index.js
  src/styles/fonts/notosanskr-regular-webfont.woff
  src/styles/style.d.ts
  src/styles/theme.ts
  src/types.d.ts
  src/utils/calendar.js
  src/utils/index.js
  tsconfig.paths.json
Labels: review-FE

#127 [Team-27][FE][Khan-sonya] 2주차 첫번째 PR 요청
  airbnb/public/index.html
  airbnb/src/components/Calendar/CalendarBody.jsx
  airbnb/src/components/Calendar/CalendarDates.jsx
  airbnb/src/components/Calendar/CalendarHead.jsx
  airbnb/src/components/Calendar/CalendarModal.jsx
  airbnb/src/components/Modal/Modal.jsx
  airbnb/src/components/Modal/ModalStyle.jsx
  airbnb/src/components/PriceRange/Canvas.jsx
  airbnb/src/components/PriceRange/PriceRange.jsx
  airbnb/src/components/SearchBar/CheckInOut.jsx
  airbnb/src/components/SearchBar/PriceRange.jsx
  airbnb/src/components/SearchBar/SearchBar.jsx
  airbnb/src/components/footer/Content.jsx
  airbnb/src/components/header/Header.jsx
  airbnb/src/components/main/CityInfo.jsx
  airbnb/src/contexts/CalendarProvider.jsx
  airbnb/src/style/theme.js
  airbnb/src/utility/dateUtil.js
Labels: review-FE

#164 [Team-01] [FE/호이] 2주차 첫번째 PR
  fe/src/App.tsx
  fe/src/Components/Calendar/Calendar.tsx
  fe/src/Components/Calendar/Month/Day/Day.styled.ts
  fe/src/Components/HeadCount/HeadCount.styled.ts
  fe/src/Components/HeadCount/HeadCount.tsx
  fe/src/Components/HeadCount/TicketBox/TicketBox.styled.ts
  fe/src/Components/HeadCount/TicketBox/TicketBox.tsx
  fe/src/Components/SearchBar/SearchBar.styled.ts
  fe/src/Components/SearchBar/SearchBar.tsx
  fe/src/Context/HeadCountProvider.tsx
  fe/src/Helpers/constant.js
  fe/src/Helpers/interface.ts
  fe/src/Helpers/utils.tsx
  fe/src/Hook/useCalendar.ts
  fe/src/Hook/useHeadCount.ts
  fe/src/Hook/useOutsideClick.ts
  fe/src/Pages/Home/CalendarModal/CalendarModal.tsx
  fe/src/Pages/Home/HeadCountModal/HeadCountModal.tsx
  fe/src/Pages/Home/Home.tsx
Labels: review-FE

#138 [Team20][FE] Airbnb 2-1 Chart 구현
  fe/.eslintrc.json
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/public/sliderThumb.svg
  fe/src/App.tsx
  fe/src/InputRangeTest.tsx
  fe/src/Router.tsx
  fe/src/Temp.tsx
  fe/src/apis/accommodation.ts
  fe/src/components/AccountMenu/index.tsx
  fe/src/components/Calendar/DayCell.tsx
  fe/src/components/Calendar/DayRow.tsx
  fe/src/components/Calendar/Days.tsx
  fe/src/components/Calendar/MonthTable.tsx
  fe/src/components/Calendar/WeekDay.tsx
  fe/src/components/Calendar/context/PickedDateUnits/index.tsx
  fe/src/components/Calendar/hooks/useDayCell.tsx
  fe/src/components/Calendar/index.tsx
  fe/src/components/Calendar/theme.ts
  fe/src/components/Calendar/utils/index.ts
  fe/src/components/Chart/Drawer.tsx
  fe/src/components/Chart/bzCurve.ts
  fe/src/components/Chart/index.tsx
  fe/src/components/Chart/style.ts
  fe/src/components/Gnb/index.tsx
  fe/src/components/Gnb/style.ts
  fe/src/components/Header/index.tsx
  fe/src/components/Header/style.ts
  fe/src/components/MultiRangeSlider/LeftInput.tsx
  fe/src/components/MultiRangeSlider/RightInput.tsx
  fe/src/components/MultiRangeSlider/context/InputRange/index.tsx
  fe/src/components/MultiRangeSlider/index.tsx
  fe/src/components/MultiRangeSlider/style.ts
  fe/src/components/SearchBar/BigSearchBar/Button.tsx
  fe/src/components/SearchBar/BigSearchBar/DateButton.tsx
  fe/src/components/SearchBar/BigSearchBar/GuestsButton.tsx
  fe/src/components/SearchBar/BigSearchBar/PriceButton.tsx
  fe/src/components/SearchBar/BigSearchBar/index.tsx
  fe/src/components/SearchBar/BigSearchBar/style.ts
  fe/src/components/SearchBar/SmallSearchBar/Button.tsx
  fe/src/components/SearchBar/SmallSearchBar/DateButton.tsx
  fe/src/components/SearchBar/SmallSearchBar/GuestsButton.tsx
  fe/src/components/SearchBar/SmallSearchBar/PriceButton.tsx
  fe/src/components/SearchBar/SmallSearchBar/index.tsx
  fe/src/components/SearchBar/SmallSearchBar/style.ts
  fe/src/components/SearchBar/common.ts
  fe/src/components/buttons/SearchButton.tsx
  fe/src/hooks/useFetch/helpers.ts
  fe/src/hooks/useFetch/useFetch.tsx
  fe/src/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/Home/style.ts
  fe/src/pages/NoteFound/index.tsx
  fe/src/pages/Search/index.tsx
  fe/src/pages/Search/style.ts
  fe/src/styles/icons.tsx
  fe/src/styles/theme.ts
  fe/src/utils/index.ts
  fe/webpack.config.js
Labels: review-FE

#174 [Team 28 FE Maeve & JinJeon] Airbnb 프로젝트 2주차(수요일) PR
  src/Api/hotelsPricesApi.js
  src/App.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.styled.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.tsx
  src/Component/Header/Modal/Modal.styled.tsx
  src/Component/Header/Modal/Modal.tsx
  src/Component/Header/Modal/PriceDetail/PriceDetail.styled.tsx
  src/Component/Header/Modal/PriceDetail/PriceDetail.tsx
  src/Component/Header/Modal/PriceDetail/PriceGraph/PriceGraph.styled.tsx
  src/Component/Header/Modal/PriceDetail/PriceGraph/PriceGraph.tsx
  src/Component/Header/Modal/PriceDetail/PriceGraph/PriceRangeSlider/PriceRangeSlider.styled.tsx
  src/Component/Header/Modal/PriceDetail/PriceGraph/PriceRangeSlider/PriceRangeSlider.tsx
  src/Component/Header/SearchBar/Guest/Guest.tsx
  src/Component/Header/SearchBar/Price/Price.styled.tsx
  src/Component/Header/SearchBar/Price/Price.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.tsx
  src/Context/PriceContext.tsx
  src/Context/ScheduleContext.tsx
  src/MockData/controllers.js
  src/MockData/data.js
  src/MockData/handlers.js
  src/Styles/theme.js
  src/util/Icons.tsx
  src/util/util.tsx
Labels: review-FE

#157 [Team 14] 목적지를 탭하면 커스텀 캘린더를 화면에 띄울 수 있음
  iOS/Targets/Cherrybnb/Sources/Common/Calendar+Extension.swift
  iOS/Targets/Cherrybnb/Sources/Search/View/CalendarPickerCollectionViewCell.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Controller/CalendarPickerViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Controller/SearchDateViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Model/CalendarPicker.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Model/Month.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/View/CalendarPickerViewCell.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/SearchLocationViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/SearchRootViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/View/LocationCell.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/View/PlaceCell.swift
  iOS/Targets/Cherrybnb/Tests/CalendarPickerSpec.swift
  iOS/Targets/Cherrybnb/Tests/SearchSpec.swift
Labels: review-iOS

#141 [Team-13][BE][제리&쿠킴] - Github Actions를 활용한 자동화 배포
  .github/build-and-depoly-to-aws.yml
  BE/Dockerfile
  BE/src/main/java/team13/kuje/airbnb/controller/model/WrapperDto.java
  BE/src/main/java/team13/kuje/airbnb/repository/PlaceRepository.java
  BE/src/main/java/team13/kuje/airbnb/service/PlaceService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/team13/kuje/airbnb/acceptance/EventAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/PlaceAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/EventServiceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/PlaceServiceTest.java
  BE/src/test/resources/application.yml
  BE/src/test/resources/testdb/data.sql
  BE/src/test/resources/testdb/schema.sql
Labels: review-BE

#176 [team-36 | dony & yellow] 2주차 1번째 PR 요청드립니다.
  .eslintrc.json
  package.json
  public/index.html
  public/mockServiceWorker.js
  src/App.tsx
  src/GlobalStyles.tsx
  src/components/Header/TopBar.tsx
  src/components/Header/index.style.tsx
  src/components/Header/index.tsx
  src/components/Hero/index.style.tsx
  src/components/Hero/index.tsx
  src/components/Modal/PriceModal.tsx
  src/components/Modal/index.style.tsx
  src/components/Modal/index.tsx
  src/components/SearchBar/SearchInputButton.tsx
  src/components/SearchBar/index.tsx
  src/components/common/IconButton.tsx
  src/constants/date.ts
  src/constants/type.ts
  src/contexts/ReservationInfoProvider.tsx
  src/index.tsx
  src/layout/index.style.tsx
  src/layout/index.tsx
  src/mockData/accommodations.js
  src/mocks/accommodations.js
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/index.tsx
  src/utils/util.ts
  tsconfig.paths.json
  yarn.lock
Labels: review-FE

#152 [BE] Team-14 2주 1차 PR 요청
  .github/workflows/gradle.yml
  backend/build.gradle
  backend/src/main/java/com/team14/cherrybnb/auth/domain/Member.java
  backend/src/main/java/com/team14/cherrybnb/auth/domain/Role.java
  backend/src/main/java/com/team14/cherrybnb/common/config/SpringDataJpaConfig.java
  backend/src/main/java/com/team14/cherrybnb/common/domain/Address.java
  backend/src/main/java/com/team14/cherrybnb/common/domain/AddressRepository.java
  backend/src/main/java/com/team14/cherrybnb/common/util/GeometryUtils.java
  backend/src/main/java/com/team14/cherrybnb/dummy/DummyDataService.java
  backend/src/main/java/com/team14/cherrybnb/revervation/domain/Reservation.java
  backend/src/main/java/com/team14/cherrybnb/revervation/domain/ReservationState.java
  backend/src/main/java/com/team14/cherrybnb/room/application/RoomSearchService.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/ReviewRepository.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/Room.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/RoomImage.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/RoomInfo.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/RoomRepository.java
  backend/src/main/java/com/team14/cherrybnb/room/dto/ReviewSummary.java
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/team14/cherrybnb/common/domain/AddressRepositoryTest.java
Labels: review-BE

#135 [Team-18][BE][타니&검봉] - 메인 레인아웃 API, AWS 인프라 구성
  BE/README.md
  BE/src/main/java/team18/airbnb/AirbnbApplication.java
  BE/src/main/java/team18/airbnb/domain/Accommodation.java
  BE/src/main/java/team18/airbnb/domain/AccommodationAddress.java
  BE/src/main/java/team18/airbnb/domain/AccommodationImg.java
  BE/src/main/java/team18/airbnb/domain/AccommodationInfo.java
  BE/src/main/java/team18/airbnb/domain/AccommodationSubImg.java
  BE/src/main/java/team18/airbnb/domain/DiscountPolicy.java
  BE/src/main/java/team18/airbnb/domain/Region.java
  BE/src/main/java/team18/airbnb/domain/Reservation.java
  BE/src/main/java/team18/airbnb/domain/ReservationFee.java
  BE/src/main/java/team18/airbnb/domain/User.java
  BE/src/main/java/team18/airbnb/domain/WishList.java
  BE/src/main/java/team18/airbnb/generalDto/LookAroundRegionDto.java
  BE/src/main/java/team18/airbnb/home/HomeController.java
  BE/src/main/java/team18/airbnb/home/HomeRepository.java
  BE/src/main/java/team18/airbnb/home/HomeService.java
  BE/src/main/java/team18/airbnb/home/dto/AccommodationByConceptDto.java
  BE/src/main/java/team18/airbnb/search/SearchController.java
  BE/src/main/java/team18/airbnb/search/SearchRepository.java
  BE/src/main/java/team18/airbnb/search/SearchService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data/data.sql
  BE/src/test/java/team18/airbnb/home/HomeServiceTest.java
Labels: review-BE

#158 [team-2][BB] Airbnb 2주차 PR - 1
  frontend/src/@types/index.d.ts
  frontend/src/App.tsx
  frontend/src/components/Header/SearchBar/SearchBar.style.ts
  frontend/src/components/Header/SearchBar/SelectItemArea/ButtonArea/ButtonArea.style.ts
  frontend/src/components/Header/SearchBar/SelectItemArea/ButtonArea/ButtonArea.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/CheckInOut.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/PeopleCount.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/ReservationFee.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/SelectItem.style.ts
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/SelectItem.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItemArea.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItemTemplate/SelectItemTemplate.style.ts
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItemTemplate/SelectItemTemplate.tsx
  frontend/src/components/Main/SearchResult/SearchResult.tsx
  frontend/src/components/NotFound/NotFound.tsx
  frontend/src/index.tsx
  frontend/src/router/index.d.ts
  frontend/src/router/pages.tsx
  frontend/src/router/router.tsx
  frontend/src/styles/theme.ts
  frontend/tsconfig.json
Labels: review-FE

#129 [team11][iOS] - 사용자 위치 정보 확인 및 CustomCallendar 작성 (2주차 화요일 PR)
  iOS/Airbnb_iOS/Airbnb_iOS.xcodeproj/project.pbxproj
  iOS/Airbnb_iOS/Airbnb_iOS/Browsing/Controller/BrowseViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Browsing/View/BorwsingSpotCollectionView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Browsing/View/BrowsingSpotCell.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Common/Controller/TabBarController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Controller/CalendarViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Controller/FindAccomodationViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Model/Day.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Model/MonthMetadata.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Model/UseCase/CalendarViewControllerUseCase.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/View/BudgetView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/View/CalendarCollectionCell.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/View/CalendarCollectionHeaderView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/View/CalendarView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/View/FindAccomodationCell.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/View/FindAccomodationView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Home/Controller/HomewViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Home/Model/UseCase/LocationManager.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Home/View/AroundSpotCell.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Home/View/CollectionHeaderView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Home/View/HomeView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Home/View/MainEventCell.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Home/View/ThemeSpotCell.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Model/Data/DateData.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Model/UseCase/FindAccomodationUseCase.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Reservation/Controller/ReservationViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Utility/CollectionLayout/BrowsingSpotCollectionLayout.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Utility/Converter/DateConverter.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Utility/DataSource/BrowsingSpotCollectionDataSource.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Utility/Extension/Date+.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Utility/Extension/Day+.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Utility/Extension/String+.swift
  iOS/Airbnb_iOS/Airbnb_iOS/View/BrowseView/FamousSpotCollectionView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/View/FindAccomodationView/DayLabel.swift
  iOS/Airbnb_iOS/Airbnb_iOS/View/FindAccomodationView/DayRangeIndicatorView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/View/FindAccomodationView/SelectCalendarView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/ViewController/TabBarItemVC/SearchViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/WishList/Controller/WishlistViewController.swift
  iOS/Airbnb_iOS/Podfile
  iOS/Airbnb_iOS/Podfile.lock
Labels: review-iOS

#155 [Team-15] [Android] 검색 사용자 설정 구현 + Compose 적용
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/airbnb/HeadCountComposeActivity.kt
  android/app/src/main/java/com/example/airbnb/HeadCountFragment.kt
  android/app/src/main/java/com/example/airbnb/ISettingPage.kt
  android/app/src/main/java/com/example/airbnb/SettingActivity.kt
  android/app/src/main/java/com/example/airbnb/SettingViewModel.kt
  android/app/src/main/java/com/example/airbnb/di/ApplicationModule.kt
  android/app/src/main/java/com/example/airbnb/ui/PriceSettingFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/common/constant.kt
  android/app/src/main/java/com/example/airbnb/ui/placesearch/PlaceSearchFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/theme/Color.kt
  android/app/src/main/java/com/example/airbnb/ui/theme/Shape.kt
  android/app/src/main/java/com/example/airbnb/ui/theme/Theme.kt
  android/app/src/main/java/com/example/airbnb/ui/theme/Type.kt
  android/app/src/main/res/drawable/ic_baseline_add_circle_outline_24.xml
  android/app/src/main/res/drawable/ic_baseline_check_24.xml
  android/app/src/main/res/drawable/ic_baseline_chevron_left_24.xml
  android/app/src/main/res/drawable/ic_baseline_remove_circle_outline_24.xml
  android/app/src/main/res/layout/activity_setting.xml
  android/app/src/main/res/layout/fragment_head_count.xml
  android/app/src/main/res/layout/fragment_price_setting.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: review-android

#126 [Team-08][iOS] Calendar View / UIBezierPath Column Graph 작업
  iOS/.gitignore
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb/Info.plist
  iOS/Airbnb/Airbnb/Network/NetworkCommonComponents.swift
  iOS/Airbnb/Airbnb/Network/NetworkServices.swift
  iOS/Airbnb/Airbnb/Network/SearchUseCase.swift
  iOS/Airbnb/Airbnb/Search/BackgroundViewController.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarHearderView.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewCell.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewController.swift
  iOS/Airbnb/Airbnb/Search/CommonTableViewController.swift
  iOS/Airbnb/Airbnb/Search/DTO/Day.swift
  iOS/Airbnb/Airbnb/Search/DTO/Reservations.swift
  iOS/Airbnb/Airbnb/Search/DTO/SearchDayDTO.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/ColumnGraphView.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/CustomRangeSlider.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/CustomRangeSliderThumbLayer.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/CustomRangeSliderTrackLayer.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/PriceGraphViewController.swift
  iOS/Airbnb/Airbnb/Search/Model/CalendarModel.swift
  iOS/Airbnb/Airbnb/Search/Model/LocationModel.swift
  iOS/Airbnb/Airbnb/Search/Model/MonthMetadata.swift
  iOS/Airbnb/Airbnb/Search/Model/ReservationModel.swift
  iOS/Airbnb/Airbnb/Search/Model/SearchCalendarModel.swift
  iOS/Airbnb/Airbnb/Search/Model/SearchModel.swift
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchHeadCountViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/HeaderReusableView.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/LocationCollectionViewCell.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/SearchCellCommonType.swift
  iOS/Airbnb/Airbnb/Source/AppDelegate.swift
  iOS/Airbnb/Airbnb/Source/CommonColors.swift
  iOS/Airbnb/AirbnbTests/AirbnbSearchUseCaseResponseTests.swift
Labels: review-iOS

#123 [Team-17] [Android] Flow 연산자 사용 및 compose 리사이클러뷰 구현
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/airbnb/data/CityInfo.kt
  android/app/src/main/java/com/example/airbnb/datasource/TmapDataSource.kt
  android/app/src/main/java/com/example/airbnb/datasource/TmapDataSourceImpl.kt
  android/app/src/main/java/com/example/airbnb/di/NetworkModule.kt
  android/app/src/main/java/com/example/airbnb/model/City.kt
  android/app/src/main/java/com/example/airbnb/network/TmapRequest.kt
  android/app/src/main/java/com/example/airbnb/repository/HomeRepositoryImpl.kt
  android/app/src/main/java/com/example/airbnb/repository/TmapRepository.kt
  android/app/src/main/java/com/example/airbnb/repository/TmapRepositoryImpl.kt
  android/app/src/main/java/com/example/airbnb/ui/MainActivity.kt
  android/app/src/main/java/com/example/airbnb/ui/home/Accommodation.kt
  android/app/src/main/java/com/example/airbnb/ui/home/AccommodationList.kt
  android/app/src/main/java/com/example/airbnb/ui/home/HomeAdapter.kt
  android/app/src/main/java/com/example/airbnb/ui/home/HomeFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/search/SearchFragment.kt
  android/app/src/main/java/com/example/airbnb/viewmodels/HomeViewModel.kt
  android/app/src/main/res/drawable/city_item_background.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/city_item.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/navigation/navigation_home.xml
  android/build.gradle
Labels: review-android

#202 [iOS] 검색화면 하단 탭 & FilterViewModel 구현
  Airbnb/Airbnb/Helpers/FlowLayoutMaker.swift
  Airbnb/Airbnb/Screens/Filter/Model/FilterCategory.swift
  Airbnb/Airbnb/Screens/Filter/View/FilterListCell.swift
  Airbnb/Airbnb/Screens/Filter/View/FilterViewController.swift
  Airbnb/Airbnb/Screens/Filter/ViewModel/FilterListCellViewModel.swift
  Airbnb/Airbnb/Screens/Filter/ViewModel/FilterListViewModel.swift
  Airbnb/Airbnb/Screens/Home/View/HomeViewController.swift
  Airbnb/Airbnb/Screens/Search/View/SearchViewController.swift
  Airbnb/Airbnb/Screens/TabBarController.swift
  Airbnb/Airbnb/Support/SceneDelegate.swift
Labels: review-iOS

#213 [Team 28 FE Maeve & JinJeon] Airbnb 프로젝트 2주차(금요일) PR
  package-lock.json
  package.json
  src/App.tsx
  src/Component/Header/GNB/GNB.styled.tsx
  src/Component/Header/GNB/GNB.tsx
  src/Component/Header/Header.styled.tsx
  src/Component/Header/Header.tsx
  src/Component/Header/Modal/CalendarDetail.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.styled.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.tsx
  src/Component/Header/Modal/GuestsDetail.tsx
  src/Component/Header/Modal/Modal.styled.tsx
  src/Component/Header/Modal/Modal.tsx
  src/Component/Header/Modal/PriceDetail.tsx
  src/Component/Header/Modal/PriceDetail/PriceDetail.tsx
  src/Component/Header/Modal/PriceDetail/PriceGraph/PriceGraph.tsx
  src/Component/Header/Modal/PriceDetail/PriceGraph/PriceRangeSlider/PriceRangeSlider.styled.tsx
  src/Component/Header/Modal/PriceDetail/PriceGraph/PriceRangeSlider/PriceRangeSlider.tsx
  src/Component/Header/SearchBar/Guest/Guest.styled.tsx
  src/Component/Header/SearchBar/Guest/Guest.tsx
  src/Component/Header/SearchBar/Price/Price.styled.tsx
  src/Component/Header/SearchBar/Price/Price.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.styled.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.tsx
  src/Component/Header/SearchBar/SearchBar.styled.tsx
  src/Component/Header/SearchBar/SearchBar.tsx
  src/Component/Header/SearchBar/SmallSearchBar.styled.tsx
  src/Component/Header/SearchBar/SmallSearchBar.tsx
  src/Component/Main.tsx
  src/Component/MainDesc.tsx
  src/Component/NotFound.tsx
  src/Component/SearchDesc.tsx
  src/Context/GuestsContext.tsx
  src/Context/PriceContext.tsx
  src/Context/ScheduleContext.tsx
  src/Context/index.tsx
  src/Context/modalContext.tsx
  src/MockData/controllers.js
  src/Router/index.tsx
  src/Styles/Normalize.jsx
  src/Styles/theme.js
  src/util/Icons.tsx
  src/util/util.tsx
Labels: review-FE

#211 [team-33 포키 & bangtae] 2주차 두번째 pr보냅니다.
  airbnb-app/jsconfig.paths.json
  airbnb-app/src/App.js
  airbnb-app/src/common/theme.js
  airbnb-app/src/component/header/Header.jsx
  airbnb-app/src/component/header/calender/Calender.jsx
  airbnb-app/src/component/header/calender/NextButton.jsx
  airbnb-app/src/component/header/calender/PrevButton.jsx
  airbnb-app/src/component/header/gnb/AccountMenu.jsx
  airbnb-app/src/component/header/gnb/GNB.jsx
  airbnb-app/src/component/header/gnb/Logo.jsx
  airbnb-app/src/component/header/gnb/MenuTabs.jsx
  airbnb-app/src/component/header/modal/calender/Calender.jsx
  airbnb-app/src/component/header/modal/calender/CalenderCarousel.jsx
  airbnb-app/src/component/header/modal/calender/CalenderPage.jsx
  airbnb-app/src/component/header/modal/calender/DateBox.jsx
  airbnb-app/src/component/header/modal/calender/DatesOfMonth.jsx
  airbnb-app/src/component/header/modal/calender/Days.jsx
  airbnb-app/src/component/header/modal/calender/NextButton.jsx
  airbnb-app/src/component/header/modal/calender/PrevButton.jsx
  airbnb-app/src/component/header/modal/personnel/ControllerButtons.jsx
  airbnb-app/src/component/header/modal/personnel/Personnel.jsx
  airbnb-app/src/component/header/modal/personnel/PersonnelController.jsx
  airbnb-app/src/component/header/modal/personnel/PersonnelSelectBox.jsx
  airbnb-app/src/component/header/search-bar/ResetButton.jsx
  airbnb-app/src/component/header/search-bar/SearchBar.jsx
  airbnb-app/src/component/header/search-bar/SearchButton.jsx
  airbnb-app/src/component/header/search-bar/SearchInput.jsx
  airbnb-app/src/component/header/search-bar/SearchInputModal.jsx
  airbnb-app/src/component/main-banner/MainBanner.jsx
  airbnb-app/src/constants/PersonnelText.js
  airbnb-app/src/context/CalenderDateProvider.jsx
  airbnb-app/src/context/PersonnelProvider.jsx
  airbnb-app/src/context/SearchBarProvider.jsx
  airbnb-app/src/styled-component/ModalContainer.js
  airbnb-app/src/utils/custom-styled-component/CustomThemeProvider.jsx
  airbnb-app/src/utils/custom-styled-component/customStyled.js
  airbnb-app/src/utils/custom-styled-component/domElements.js
  airbnb-app/src/utils/custom-styled-component/useTheme.jsx
  airbnb-app/src/utils/utils.js
Labels: review-FE

#190 [Team-20 BE] Airbnb 프로젝트 2주차(금요일) 리뷰 요청
  be/README.md
  be/src/main/java/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/codesquad/airbnb/controller/OAuthController.java
  be/src/main/java/codesquad/airbnb/domain/Member.java
  be/src/main/java/codesquad/airbnb/dto/AccommodationDto.java
  be/src/main/java/codesquad/airbnb/dto/OAuthAccessToken.java
  be/src/main/java/codesquad/airbnb/dto/UserSearchForm.java
  be/src/main/java/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/codesquad/airbnb/repository/MemberRepository.java
  be/src/main/java/codesquad/airbnb/service/AccommodationService.java
  be/src/main/java/codesquad/airbnb/service/OAuthService.java
  be/src/main/resources/data.sql
Labels: review-BE

#219 [Team22][FE] 도비 & JS 2주차 금 PR
  fe/src/components/Calendar.tsx
  fe/src/components/Calender/Calendar.tsx
  fe/src/components/Calender/Day.tsx
  fe/src/components/Header/SearchBar/MiniSearchBar/index.tsx
  fe/src/components/Header/SearchBar/Personnel.tsx
  fe/src/components/Header/SearchBar/Price.tsx
  fe/src/components/Header/SearchBar/index.tsx
  fe/src/components/Header/SearchWrapper.tsx
  fe/src/components/Header/index.tsx
  fe/src/components/Modals/PeriodModal.tsx
  fe/src/components/Modals/Price/Chart.tsx
  fe/src/components/Modals/Price/RangeSlider.tsx
  fe/src/components/Modals/Price/index.tsx
  fe/src/components/Modals/Price/priceTypes.ts
  fe/src/components/Modals/PriceModal.tsx
  fe/src/contexts/PersonnelContext.tsx
  fe/src/contexts/PriceContext.tsx
  fe/src/contexts/periodContext.tsx
  fe/src/mocks/hotelPrices.tsx
  fe/src/utils/helper.tsx
  fe/src/utils/util.tsx
Labels: review-FE

#180 [Team-24][BE] airbnb 프로젝트 PR #3
  be/build.gradle
  be/src/main/java/kr/codesquad/airbnb/AirbnbApplication.java
  be/src/main/java/kr/codesquad/airbnb/AuthenticationFilter.java
  be/src/main/java/kr/codesquad/airbnb/controller/RoomController.java
  be/src/main/java/kr/codesquad/airbnb/domain/Amenity.java
  be/src/main/java/kr/codesquad/airbnb/domain/Booking.java
  be/src/main/java/kr/codesquad/airbnb/domain/DiscountTax.java
  be/src/main/java/kr/codesquad/airbnb/domain/Guest.java
  be/src/main/java/kr/codesquad/airbnb/domain/Location.java
  be/src/main/java/kr/codesquad/airbnb/domain/Member.java
  be/src/main/java/kr/codesquad/airbnb/domain/Room.java
  be/src/main/java/kr/codesquad/airbnb/domain/RoomAmenity.java
  be/src/main/java/kr/codesquad/airbnb/domain/RoomDiscountTax.java
  be/src/main/java/kr/codesquad/airbnb/dto/CategorizedPrice.java
  be/src/main/java/kr/codesquad/airbnb/dto/RangeOfPrice.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomPriceStatistic.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomPriceStatisticDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomPriceStatisticRequest.java
  be/src/main/java/kr/codesquad/airbnb/exception/CustomException.java
  be/src/main/java/kr/codesquad/airbnb/exception/ErrorCode.java
  be/src/main/java/kr/codesquad/airbnb/exception/GlobalExceptionHandler.java
  be/src/main/java/kr/codesquad/airbnb/repository/RoomRepository.java
  be/src/main/java/kr/codesquad/airbnb/response/BasicResponse.java
  be/src/main/java/kr/codesquad/airbnb/response/CommonResponse.java
  be/src/main/java/kr/codesquad/airbnb/response/ErrorResponse.java
  be/src/main/java/kr/codesquad/airbnb/service/RoomService.java
  be/src/main/resources/application.properties
  be/src/main/resources/sql/data.sql
  be/src/main/resources/sql/schema.sql
  be/src/test/java/kr/codesquad/airbnb/controller/RoomControllerTest.java
  be/src/test/java/kr/codesquad/airbnb/repository/RoomRepositoryTest.java
  be/src/test/java/kr/codesquad/airbnb/service/RoomServiceTest.java
Labels: review-BE

#222 [Team23 땃쥐] airbnb 4차 PR
  BE/build.gradle
  BE/src/main/java/codesquad/airbnb/accommodation/service/AccommodationCommandService.java
  BE/src/main/java/codesquad/airbnb/accommodation/service/AccommodationQueryService.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/AccommodationController.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationDetailResponse.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationPricesResponse.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationRegisterResponse.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationSaveRequest.java
  BE/src/main/java/codesquad/airbnb/booking/domain/BookingPeriod.java
  BE/src/main/java/codesquad/airbnb/exception/AccommodationNotFoundException.java
  BE/src/main/java/codesquad/airbnb/exception/DuplicateGitHubIdException.java
  BE/src/main/java/codesquad/airbnb/exception/DuplicateMemberNameException.java
  BE/src/main/java/codesquad/airbnb/exception/InvalidPeriodException.java
  BE/src/main/java/codesquad/airbnb/exception/MemberNotFoundException.java
  BE/src/main/java/codesquad/airbnb/member/domain/Member.java
  BE/src/main/java/codesquad/airbnb/member/repository/MemberRepository.java
  BE/src/main/java/codesquad/airbnb/member/service/MemberCommandService.java
  BE/src/main/java/codesquad/airbnb/member/service/MemberQueryService.java
  BE/src/main/java/codesquad/airbnb/member/web/MemberController.java
  BE/src/main/java/codesquad/airbnb/member/web/dto/MemberDetailResponse.java
  BE/src/main/java/codesquad/airbnb/member/web/dto/MemberJoinRequest.java
  BE/src/main/java/codesquad/airbnb/member/web/dto/MemberJoinResponse.java
  BE/src/test/java/codesquad/airbnb/booking/domain/BookingPeriodTest.java
Labels: review-BE

#203 [Team - 06][BE] 에어비앤비 프로젝트 2주차 2회차 PR
  BE/README.md
  BE/build.gradle
  BE/src/main/java/com/airbnb/api/houses/HouseController.java
  BE/src/main/java/com/airbnb/api/houses/dto/AccommodationCostResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/HouseCountResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/HouseDetailResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/ImageResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/LocationInformationRequest.java
  BE/src/main/java/com/airbnb/api/houses/dto/NumberOfHousesByPrice.java
  BE/src/main/java/com/airbnb/api/houses/dto/NumberOfHousesByPriceResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/SearchConditionRequest.java
  BE/src/main/java/com/airbnb/api/interceptor/AuthenticationInterceptor.java
  BE/src/main/java/com/airbnb/api/login/oauth/OAuthLoginController.java
  BE/src/main/java/com/airbnb/api/login/oauth/dto/LoginResponse.java
  BE/src/main/java/com/airbnb/api/users/UserController.java
  BE/src/main/java/com/airbnb/config/WebConfig.java
  BE/src/main/java/com/airbnb/domain/DiscountPolicy.java
  BE/src/main/java/com/airbnb/domain/House.java
  BE/src/main/java/com/airbnb/domain/HouseDiscountPolicy.java
  BE/src/main/java/com/airbnb/domain/login/OAuthServer.java
  BE/src/main/java/com/airbnb/domain/login/OauthToken.java
  BE/src/main/java/com/airbnb/domain/login/dto/UserProfileDto.java
  BE/src/main/java/com/airbnb/domain/login/github/GitHubOAuthServer.java
  BE/src/main/java/com/airbnb/domain/login/github/GitHubToken.java
  BE/src/main/java/com/airbnb/domain/login/kakao/KakaoOAuthServer.java
  BE/src/main/java/com/airbnb/domain/login/kakao/KakaoProfile.java
  BE/src/main/java/com/airbnb/domain/login/kakao/KakaoToken.java
  BE/src/main/java/com/airbnb/repository/HouseRepository.java
  BE/src/main/java/com/airbnb/repository/UserRepository.java
  BE/src/main/java/com/airbnb/repository/dto/HouseCount.java
  BE/src/main/java/com/airbnb/service/HouseService.java
  BE/src/main/java/com/airbnb/service/LoginService.java
  BE/src/main/java/com/airbnb/utils/CardinalDirection.java
  BE/src/main/java/com/airbnb/utils/geometry/GeometryUtils.java
  BE/src/main/java/com/airbnb/utils/oauth/JwtTokenProvider.java
  BE/src/main/resources/application.yml
  BE/src/test/java/com/airbnb/repository/HouseRepositoryTest.java
  BE/src/test/java/com/airbnb/service/HouseServiceTest.java
Labels: review-BE

#225 [team-30][FE] 2주차 2번째PR 작업현황 및 고민사항
  airbnb/package-lock.json
  airbnb/package.json
  airbnb/public/index.html
  airbnb/src/Components/GNB/AccountMenu.tsx
  airbnb/src/Components/GNB/GNB.style.tsx
  airbnb/src/Components/GNB/GNB.tsx
  airbnb/src/Components/GNB/Menus.tsx
  airbnb/src/Components/Schedule/Day.tsx
  airbnb/src/Components/Schedule/Schedule.style.tsx
  airbnb/src/Components/Schedule/Schedule.tsx
  airbnb/src/Components/SearchBar/Item.tsx
  airbnb/src/Components/SearchBar/SearchBar.style.tsx
  airbnb/src/Components/SearchBar/SearchBar.tsx
  airbnb/src/Components/SearchBar/SearchButton.tsx
  airbnb/src/Contexts/Searching/Action.ts
  airbnb/src/Contexts/Searching/context.tsx
  airbnb/src/Contexts/Searching/index.ts
  airbnb/src/Contexts/Searching/reducer.ts
  airbnb/src/Contexts/Searching/types.ts
  airbnb/src/Hooks/SearchBarHooks.ts
  airbnb/src/Pages/Home.tsx
  airbnb/src/index.tsx
  airbnb/src/lib/Schedule/Components/BaseWeekend.tsx
  airbnb/src/lib/Schedule/Components/Calendar.tsx
  airbnb/src/lib/Schedule/Components/CalendarDate.tsx
  airbnb/src/lib/Schedule/Components/CalendarHeader.tsx
  airbnb/src/lib/Schedule/Components/Day.tsx
  airbnb/src/lib/Schedule/Components/Schedule.style.tsx
  airbnb/src/lib/Schedule/Components/Schedule.tsx
  airbnb/src/lib/Schedule/Contexts/context.tsx
  airbnb/src/lib/Schedule/Contexts/index.ts
  airbnb/src/lib/Schedule/Contexts/types.ts
  airbnb/src/lib/Schedule/Hooks/ScheduleHooks.ts
  airbnb/src/lib/Schedule/index.ts
  airbnb/src/styles/GlobalStyle.tsx
  airbnb/src/testCanvas/test.html
  airbnb/src/testCanvas/test.js
Labels: review-FE

#209 [Team-01] [FE/호이] 2주차 두번째 PR
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/Components/Calendar/Calendar.styled.ts
  fe/src/Components/Calendar/Calendar.tsx
  fe/src/Components/Calendar/Month/Month.styled.ts
  fe/src/Components/Gnb/Gnb.styled.ts
  fe/src/Components/Gnb/Gnb.tsx
  fe/src/Components/HeadCount/HeadCount.styled.ts
  fe/src/Components/HeadCount/HeadCount.tsx
  fe/src/Components/SearchBar/MiniSearchBar.tsx
  fe/src/Components/SearchBar/SearchBar.styled.ts
  fe/src/Components/SearchBar/SearchBar.tsx
  fe/src/Context/CalendarProvider.tsx
  fe/src/Helpers/interface.ts
  fe/src/Helpers/utils.tsx
  fe/src/Hook/useCalendar.ts
  fe/src/Hook/useOutsideClick.ts
  fe/src/Pages/Common/CalendarModal/CalendarModal.tsx
  fe/src/Pages/Common/HeadCountModal/HeadCountModal.tsx
  fe/src/Pages/Common/SearchView.styled.ts
  fe/src/Pages/Common/SearchView.tsx
  fe/src/Pages/Home/Home.styled.tsx
  fe/src/Pages/Home/Home.tsx
  fe/src/Pages/NotFound/NotFound.styled.ts
  fe/src/Pages/NotFound/NotFound.tsx
  fe/src/Pages/SearchResult/SearchResult.styled.ts
  fe/src/Pages/SearchResult/SearchResult.tsx
Labels: review-FE

#181 [Team-20][FE] Airbnb 2-2 Price Picker 구현
  fe/src/App.tsx
  fe/src/InputRangeTest.tsx
  fe/src/Temp.tsx
  fe/src/apis/accommodation.ts
  fe/src/components/Chart/Drawer.tsx
  fe/src/components/Chart/index.tsx
  fe/src/components/Chart/style.ts
  fe/src/components/Gnb/index.tsx
  fe/src/components/MultiRangeSlider/LeftInput.tsx
  fe/src/components/MultiRangeSlider/RightInput.tsx
  fe/src/components/MultiRangeSlider/common.ts
  fe/src/components/MultiRangeSlider/context/InputRange/index.tsx
  fe/src/components/MultiRangeSlider/index.tsx
  fe/src/components/MultiRangeSlider/style.ts
  fe/src/components/PricePicker/index.tsx
  fe/src/components/PricePicker/style.ts
  fe/src/contexts/Accommodation/index.tsx
  fe/src/hooks/useFetch/useFetch.tsx
  fe/src/index.tsx
  fe/src/mocks/AccommodationData.ts
  fe/src/mocks/handlers.ts
Labels: review-FE

#216 [FE][Team23][Millie & Oliver] 네 번째 PR
  FE/.eslintrc
  FE/db.json
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/apis/core/index.ts
  FE/src/apis/mainContents.ts
  FE/src/assets/favicon.png
  FE/src/components/Footer/Footer.style.ts
  FE/src/components/Footer/index.tsx
  FE/src/components/GNB/GNB.style.ts
  FE/src/components/GNB/Logo.tsx
  FE/src/components/GNB/NavMenu.tsx
  FE/src/components/GNB/ProfileButton.tsx
  FE/src/components/GNB/index.tsx
  FE/src/components/Header/Header.style.ts
  FE/src/components/Header/index.tsx
  FE/src/components/Modal/Modal.style.ts
  FE/src/components/Modal/index.tsx
  FE/src/components/SearchBar/SearchBar.style.ts
  FE/src/components/SearchBar/SearchButton.tsx
  FE/src/components/SearchBar/SearchInput.tsx
  FE/src/components/SearchBar/index.tsx
  FE/src/components/common/AlbumItem/AlbumItem.style.ts
  FE/src/components/common/AlbumItem/index.tsx
  FE/src/components/common/ListItem/ListItem.style.ts
  FE/src/components/common/ListItem/index.tsx
  FE/src/constants/actions.ts
  FE/src/constants/constant.ts
  FE/src/constants/searchBarData.ts
  FE/src/context/SearchProvider.tsx
  FE/src/layout/index.tsx
  FE/src/mocks/searchBarTempData.ts
  FE/src/pages/MainContents/MainContents.style.ts
  FE/src/pages/MainContents/index.tsx
  FE/src/pages/NotFound/NotFound.style.ts
  FE/src/pages/NotFound/index.tsx
  FE/src/styles/commonStyle.ts
  FE/src/styles/icons.ts
  FE/src/utils/updateData.ts
  FE/src/utils/utils.ts
  FE/webpack.config.js
Labels: review-FE

#208 [Team-22][BE][Lee&벅픽] 2주차 2번째 PR - 숙소 검색 쿼리 수정 및 샘플 데이터 추가
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
  be/src/main/resources/dml.sql
Labels: review-BE

#204 [Team-16][BE][Yanse] airbnb 프로젝트 2주차 PR#4
  BE/.gitignore
  BE/build.gradle
  BE/src/main/generated/yanse/airbnb/domain/image/QImage.java
  BE/src/main/generated/yanse/airbnb/domain/image/QRoomImage.java
  BE/src/main/generated/yanse/airbnb/domain/member/QMembers.java
  BE/src/main/generated/yanse/airbnb/domain/reservation/QDetailFee.java
  BE/src/main/generated/yanse/airbnb/domain/reservation/QReservation.java
  BE/src/main/generated/yanse/airbnb/domain/room/QAddress.java
  BE/src/main/generated/yanse/airbnb/domain/room/QRoom.java
  BE/src/main/generated/yanse/airbnb/domain/room/QRoomInfo.java
  BE/src/main/generated/yanse/airbnb/domain/wish/QWish.java
  BE/src/main/java/yanse/airbnb/domain/image/Image.java
  BE/src/main/java/yanse/airbnb/domain/image/RoomImage.java
  BE/src/main/java/yanse/airbnb/domain/image/repository/ImageRepository.java
  BE/src/main/java/yanse/airbnb/domain/image/repository/RoomImageRepository.java
  BE/src/main/java/yanse/airbnb/domain/member/Members.java
  BE/src/main/java/yanse/airbnb/domain/reservation/DetailFee.java
  BE/src/main/java/yanse/airbnb/domain/reservation/Reservation.java
  BE/src/main/java/yanse/airbnb/domain/room/Address.java
  BE/src/main/java/yanse/airbnb/domain/room/Room.java
  BE/src/main/java/yanse/airbnb/domain/room/RoomInfo.java
  BE/src/main/java/yanse/airbnb/domain/room/RoomRepository.java
  BE/src/main/java/yanse/airbnb/domain/room/repository/RoomRepository.java
  BE/src/main/java/yanse/airbnb/domain/room/repository/RoomRepositoryCustom.java
  BE/src/main/java/yanse/airbnb/domain/room/repository/RoomRepositoryImpl.java
  BE/src/main/java/yanse/airbnb/domain/wish/Wish.java
  BE/src/main/java/yanse/airbnb/service/MainService.java
  BE/src/main/java/yanse/airbnb/service/SearchService.java
  BE/src/main/java/yanse/airbnb/type/DiscountPolicy.java
  BE/src/main/java/yanse/airbnb/type/ImageType.java
  BE/src/main/java/yanse/airbnb/type/RoomType.java
  BE/src/main/java/yanse/airbnb/web/controller/MainController.java
  BE/src/main/java/yanse/airbnb/web/controller/SearchController.java
  BE/src/main/java/yanse/airbnb/web/dto/ImageDto.java
  BE/src/main/java/yanse/airbnb/web/dto/RequestRoomSearchDto.java
  BE/src/main/java/yanse/airbnb/web/dto/ResponseDto.java
  BE/src/main/java/yanse/airbnb/web/dto/ResponseRoomDto.java
  BE/src/main/java/yanse/airbnb/web/dto/RoomDto.java
  BE/src/main/java/yanse/airbnb/web/dto/RoomImageDto.java
  BE/src/main/resources/data.sql
Labels: review-BE

#189 [Team03][BE] 세번째 PR입니다
  be/build.gradle
  be/src/main/java/teamproject/airbnb/api/ReservationApiController.java
  be/src/main/java/teamproject/airbnb/api/RoomApiController.java
  be/src/main/java/teamproject/airbnb/controller/MemberController.java
  be/src/main/java/teamproject/airbnb/controller/RoomController.java
  be/src/main/java/teamproject/airbnb/controller/RoomQuantityResponseDto.java
  be/src/main/java/teamproject/airbnb/controller/RoomSearchInfoRequestDto.java
  be/src/main/java/teamproject/airbnb/controller/RoomSimpleInfoResponseDto.java
  be/src/main/java/teamproject/airbnb/domain/Member.java
  be/src/main/java/teamproject/airbnb/domain/Review.java
  be/src/main/java/teamproject/airbnb/domain/Room.java
  be/src/main/java/teamproject/airbnb/repository/RoomRepository.java
  be/src/main/java/teamproject/airbnb/service/RoomQuantityDto.java
  be/src/main/java/teamproject/airbnb/service/RoomService.java
  be/src/main/java/teamproject/airbnb/service/RoomSimpleInfoDto.java
Labels: review-BE

#217 [Team 32] [J, 럼카] 2주차 2번째 PR 요청드립니다.
  .gitignore
  package-lock.json
  package.json
  public/_redirects
  public/index.html
  src/components/Accommodations/AccommodationHeader.jsx
  src/components/Accommodations/AccommodationItem.jsx
  src/components/Accommodations/index.jsx
  src/components/App.jsx
  src/components/Calendar/Calendar.jsx
  src/components/Calendar/Day.jsx
  src/components/GuestModal/Counter.jsx
  src/components/GuestModal/GuestSettingForm.jsx
  src/components/GuestModal/index.jsx
  src/components/Header/index.jsx
  src/components/Map/index.jsx
  src/components/Modal/SearchBarModal.jsx
  src/components/PriceModal/Canvas.jsx
  src/components/PriceModal/RangeSliderController.jsx
  src/components/PriceModal/calculate.js
  src/components/PriceModal/index.jsx
  src/components/SearchBar/Filter/index.tsx
  src/components/SearchBar/Guest.jsx
  src/components/SearchBar/MiniSearchBar.jsx
  src/components/SearchBar/Price.jsx
  src/components/SearchBar/Schedule.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchButton.jsx
  src/constants/canvasSize.js
  src/constants/message.js
  src/constants/priceRange.js
  src/constants/size.js
  src/mockData/accommodation.js
  src/pages/Home.jsx
  src/pages/ReservationSuccess.jsx
  src/pages/SearchResult.jsx
  src/reducer/guestReducer.js
  src/reducer/modalReducer.js
  src/reducer/priceReducer.js
  src/reducer/scheduleReducer.js
  src/store/FilterContext.jsx
  src/styles/GlobalStyles.js
  src/styles/font.js
  src/styles/zIndex.ts
Labels: review-FE

#177 [Team-08][BE][후&아더] - 로컬DB 환경구성, 엔티티 작성 및 연관관계 매핑, 숙박 요금 계산 API 구현
  BE/build.gradle
  BE/src/main/java/com/ahoo/airbnb/entity/Address.java
  BE/src/main/java/com/ahoo/airbnb/entity/BaseEntity.java
  BE/src/main/java/com/ahoo/airbnb/entity/ChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/entity/Coordinate.java
  BE/src/main/java/com/ahoo/airbnb/entity/Member.java
  BE/src/main/java/com/ahoo/airbnb/entity/MemberType.java
  BE/src/main/java/com/ahoo/airbnb/entity/Reservation.java
  BE/src/main/java/com/ahoo/airbnb/entity/Room.java
  BE/src/main/java/com/ahoo/airbnb/entity/RoomChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/entity/RoomImage.java
  BE/src/main/java/com/ahoo/airbnb/entity/Wish.java
  BE/src/main/java/com/ahoo/airbnb/exception/ErrorResponse.java
  BE/src/main/java/com/ahoo/airbnb/exception/ExceptionMessage.java
  BE/src/main/java/com/ahoo/airbnb/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/ahoo/airbnb/reservation/MockReservationService.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationController.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationService.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/AccommodationChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/AccommodationTaxChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ChargePolicyType.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/CleaningChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ServiceChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/WeeklyDiscountChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ChargesResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationRequest.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeRequest.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeResponse.java
  BE/src/main/java/com/ahoo/airbnb/room/ImageResponse.java
  BE/src/main/java/com/ahoo/airbnb/room/ImagesResponse.java
  BE/src/main/java/com/ahoo/airbnb/room/MockRoomService.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomRepository.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomDetailResponse.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomRequest.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomResponse.java
  BE/src/main/java/com/ahoo/airbnb/utils/DateUtils.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/sql/data.sql
  BE/src/main/resources/sql/schema.sql
  BE/src/test/java/com/ahoo/airbnb/data/TestData.java
  BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
Labels: review-BE

#206 [Team 14] 하위 지역까지 검색하고, 날짜를 탭하면 선택한 날짜 범위가 달력에 표시됨
  iOS/Targets/Cherrybnb/Sources/Common/Font+Extension.swift
  iOS/Targets/Cherrybnb/Sources/Common/Hour.swift
  iOS/Targets/Cherrybnb/Sources/Common/PlaceFactory.swift
  iOS/Targets/Cherrybnb/Sources/Common/TimeFormatter.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Controller/CalendarPickerViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Controller/SearchDateViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Model/CalendarPicker.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Model/Month.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/View/CalendarPickerViewCell.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/DetailSearchDataSource.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/DetailSearchDelegate.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/RecommandDelegate.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/RecommendationDataSource.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/SearchLocationDataSource.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/SearchLocationViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Model/HTTPService.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/View/LocationCell.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/View/PlaceCell.swift
  iOS/Targets/Cherrybnb/Sources/Support/AppDelegate.swift
  iOS/Targets/Cherrybnb/Tests/CalendarPickerSpec.swift
  iOS/Targets/Cherrybnb/Tests/SearchSpec.swift
  iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: review-iOS

#223 [team-21] 데이먼 2주차 2번째 PR요청
  BE/src/main/java/team21/airbnb/controller/RoomController.java
  BE/src/main/java/team21/airbnb/domain/Booking.java
  BE/src/main/java/team21/airbnb/domain/BookingStatus.java
  BE/src/main/java/team21/airbnb/domain/Location.java
  BE/src/main/java/team21/airbnb/domain/Room.java
  BE/src/main/java/team21/airbnb/domain/RoomImage.java
  BE/src/main/java/team21/airbnb/domain/RoomType.java
  BE/src/main/java/team21/airbnb/domain/SpaceType.java
  BE/src/main/java/team21/airbnb/domain/embeddable/GuestGroup.java
  BE/src/main/java/team21/airbnb/domain/embeddable/Location.java
  BE/src/main/java/team21/airbnb/domain/embeddable/ReviewStatus.java
  BE/src/main/java/team21/airbnb/domain/embeddable/RoomChargeInformation.java
  BE/src/main/java/team21/airbnb/domain/embeddable/RoomCondition.java
  BE/src/main/java/team21/airbnb/domain/embeddable/StayDate.java
  BE/src/main/java/team21/airbnb/dto/request/RoomSearchCondition.java
  BE/src/main/java/team21/airbnb/dto/response/RoomDetailResponse.java
  BE/src/main/java/team21/airbnb/dto/response/RoomSearchResponse.java
  BE/src/main/java/team21/airbnb/repository/RoomRepository.java
  BE/src/main/java/team21/airbnb/service/RoomService.java
  BE/src/main/resources/application.yml
  BE/src/test/java/team21/airbnb/config/TestConfig.java
  BE/src/test/java/team21/airbnb/repository/RoomRepositoryTest.java
  BE/src/test/java/team21/airbnb/service/RoomServiceTest.java
Labels: review-BE

#182 [Team-05][BE] 비씨 & 노리 airbnb 프로젝트 2주차 두 번째 PR
  Backend/build.gradle
  Backend/src/main/java/project/airbnb/bnb/Bnb.java
  Backend/src/main/java/project/airbnb/bnb/BnbController.java
  Backend/src/main/java/project/airbnb/bnb/BnbService.java
  Backend/src/main/java/project/airbnb/bnb/dto/BnbDetailDto.java
  Backend/src/main/java/project/airbnb/bnb/dto/BnbSimpleDto.java
  Backend/src/main/java/project/airbnb/bnb/dto/SearchQueryDto.java
  Backend/src/main/java/project/airbnb/bnb/embedded/Address.java
  Backend/src/main/java/project/airbnb/bnb/embedded/BnbOption.java
  Backend/src/main/java/project/airbnb/bnb/embedded/CheckInOutTime.java
  Backend/src/main/java/project/airbnb/bnb/embedded/Coordinates.java
  Backend/src/main/java/project/airbnb/commons/ApiResponse.java
  Backend/src/main/java/project/airbnb/data/DataProcessor.java
  Backend/src/main/java/project/airbnb/reservation/ReservationController.java
  Backend/src/main/java/project/airbnb/reservation/ReservationDetailDto.java
  Backend/src/main/java/project/airbnb/reservation/ReservationService.java
  Backend/src/main/java/project/airbnb/reservation/ReservationSimpleDto.java
  Backend/src/main/java/project/airbnb/response/BnbSearchResponse.java
  Backend/src/main/java/project/airbnb/response/CommonResponse.java
  Backend/src/main/java/project/airbnb/wishlist/Wish.java
  Backend/src/main/java/project/airbnb/wishlist/WishController.java
  Backend/src/main/java/project/airbnb/wishlist/WishDto.java
  Backend/src/main/java/project/airbnb/wishlist/WishRepository.java
  Backend/src/main/java/project/airbnb/wishlist/WishService.java
  Backend/src/main/resources/application-bc.yml
  Backend/src/main/resources/application.yml
  Backend/src/main/resources/bnbInitData.csv
  Backend/src/main/resources/hotel_data.xlsx
  Backend/src/main/resources/sql/data.sql
  Backend/src/test/java/project/airbnb/TestDataBuilder.java
  Backend/src/test/java/project/airbnb/bnb/BnbControllerTest.java
  Backend/src/test/java/project/airbnb/reservation/ReservationControllerTest.java
  Backend/src/test/java/project/airbnb/wishlist/WishServiceTest.java
Labels: review-BE

#227 [Team-34] 베르&쥬 2주차 금요일 PR
  .eslintrc.js
  package-lock.json
  package.json
  src/App.jsx
  src/App.tsx
  src/components/Calendar/CalendarDate/index.tsx
  src/components/Calendar/CalendarDate/style.ts
  src/components/Calendar/CalendarPage/index.tsx
  src/components/Calendar/CalendarPage/style.ts
  src/components/Calendar/index.jsx
  src/components/Calendar/index.tsx
  src/components/Calendar/style.js
  src/components/Calendar/style.ts
  src/components/SearchBar/Period/index.tsx
  src/components/SearchBar/Personnel/index.tsx
  src/components/SearchBar/Price/index.tsx
  src/components/SearchBar/Price/style.ts
  src/components/SearchBar/index.tsx
  src/components/common/Modal/index.jsx
  src/components/common/TextBox/index.jsx
  src/components/common/TextBox/index.tsx
  src/components/common/TextBox/style.ts
  src/constants/calendar.js
  src/constants/calendar.ts
  src/constants/index.js
  src/contexts/CalendarProvider.tsx
  src/pages/NotFound/index.jsx
  src/styles/GlobalStyles.ts
  src/styles/fonts/index.js
  src/utils/calendar.js
  src/utils/calendar.ts
  src/utils/index.js
  tsconfig.json
Labels: review-FE

#179 [Team-07][iOS] 실 서버 연동 작업 및 숙소 리스트 및 상세화면, 지도 화면 구현
  iOS/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Common/CustomCollectionViewDataSource.swift
  iOS/Airbnb/Common/JsonHandler.swift
  iOS/Airbnb/Common/Margins.swift
  iOS/Airbnb/Common/RoundButton.swift
  iOS/Airbnb/Common/UIView+Extension.swift
  iOS/Airbnb/Entity/RoomDetail.swift
  iOS/Airbnb/Entity/RoomPositionInfo.swift
  iOS/Airbnb/ExtraSearch/ConditionSettingUseCase.swift
  iOS/Airbnb/PositionSearch/PositionSearchViewController.swift
  iOS/Airbnb/RoomDetail/RoomDetailRepository.swift
  iOS/Airbnb/RoomDetail/RoomDetailUseCase.swift
  iOS/Airbnb/RoomDetail/RoomDetailViewController.swift
  iOS/Airbnb/RoomDetail/View/RoomDetailDescriptionView.swift
  iOS/Airbnb/RoomDetail/View/RoomDetailHostProfileView.swift
  iOS/Airbnb/RoomDetail/View/RoomDetailReservateView.swift
  iOS/Airbnb/RoomDetail/View/RoomDetailTitleView.swift
  iOS/Airbnb/RoomList/MapViewController.swift
  iOS/Airbnb/RoomList/RoomListUseCase.swift
  iOS/Airbnb/RoomList/RoomListViewController.swift
  iOS/Airbnb/RoomList/View/SearchResultRoomCell.swift
  iOS/Airbnb/RoomList/View/SearchResultRoomsHeaderView.swift
  iOS/Airbnb/RoomPositionMap/RoomPositionMapRepository.swift
  iOS/Airbnb/RoomPositionMap/RoomPositionMapUseCase.swift
  iOS/Airbnb/RoomPositionMap/RoomPositionMapViewController.swift
  iOS/Airbnb/RoomPositionMap/View/CustomGoogleMapMarker.swift
  iOS/Airbnb/RoomPositionMap/View/RoomPositionMapCollectionViewCell.swift
  iOS/Airbnb/SearchFilter/SearchFilterUseCase.swift
  iOS/Airbnb/SearchFilter/SearchFilterViewController.swift
  iOS/Airbnb/SearchFilter/View/FilterCategory.swift
  iOS/Airbnb/SearchFilter/View/SearchFilterTableViewCell.swift
  iOS/Airbnb/SearchFilter/View/SearchFilterTableViewDataSource.swift
  iOS/Airbnb/Server/NetworkHandler.swift
  iOS/Airbnb/Server/Resource/ContentType.swift
  iOS/Airbnb/Server/Resource/EndPoint.swift
  iOS/Airbnb/Server/Resource/HttpMethod.swift
Labels: review-iOS

#194 [Team-19][AOS] [ Linus& 히데 Airbnb 두번째주 금요일 PR ] 인원 선택 페이지 완성, 정보 입력 페이지 구조 수정, 로그인 JWT 받아오기 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactoring-.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-dev-be.yml
  android/app/.idea/.gitignore
  android/app/.idea/gradle.xml
  android/app/.idea/misc.xml
  android/app/.idea/vcs.xml
  android/app/.idea/workspace.xml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/airbnb/AirbnbApplication.kt
  android/app/src/main/java/com/example/airbnb/common/AccessToken.kt
  android/app/src/main/java/com/example/airbnb/common/Constants.kt
  android/app/src/main/java/com/example/airbnb/data/RepositoryImpl.kt
  android/app/src/main/java/com/example/airbnb/data/remote/LoginApi.kt
  android/app/src/main/java/com/example/airbnb/data/remote/LoginDataSource.kt
  android/app/src/main/java/com/example/airbnb/data/remote/LoginRemoteDataSource.kt
  android/app/src/main/java/com/example/airbnb/di/AppModule.kt
  android/app/src/main/java/com/example/airbnb/di/NetWorkModule.kt
  android/app/src/main/java/com/example/airbnb/domain/Repository.kt
  android/app/src/main/java/com/example/airbnb/ui/calendar/CalendarFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/guestRange/GuestRangeFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/home/HomeFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/information/InformationActivity.kt
  android/app/src/main/java/com/example/airbnb/ui/information/InformationViewModel.kt
  android/app/src/main/java/com/example/airbnb/ui/login/LoginFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/login/LoginViewModel.kt
  android/app/src/main/java/com/example/airbnb/ui/login/LoginWebViewFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/priceRange/PriceRangeFragment.kt
  android/app/src/main/res/drawable/ic_add_circle_outline_black_24dp.xml
  android/app/src/main/res/drawable/ic_remove_circle_outline_black_24dp.xml
  android/app/src/main/res/layout/activity_information.xml
  android/app/src/main/res/navigation/navigation_information.xml
  android/app/src/main/res/navigation/navigation_main.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: review-android

#183 [team11][iOS] - 데이터 관리 객체 분리 및 리팩토링 (2주차 금요일 PR)
  iOS/Airbnb_iOS/Airbnb_iOS.xcodeproj/project.pbxproj
  iOS/Airbnb_iOS/Airbnb_iOS/Browsing/Controller/BrowseViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Browsing/Model/MKDataManager.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Browsing/View/BrowsingSpotCell.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Controller/CalendarViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Controller/DataSource&Delegate/CalendarCollectionDataSource.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Controller/DataSource&Delegate/FindAccomodationTableDataSource.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Controller/DataSource&Delegate/FindAccomodationTableDelegate.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Controller/FindAccomodationViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Model/AccomodationData.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/Model/UseCase/CalendarUseCase.swift
  iOS/Airbnb_iOS/Airbnb_iOS/FindAccomodation/View/FindAccomodationView.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Home/Controller/HomewViewController.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Utility/DataSource/BrowsingSpotCollectionDataSource.swift
  iOS/Airbnb_iOS/Airbnb_iOS/Utility/Extension/Int+.swift
Labels: review-iOS

#187 [team-14 BE] airbnb 프로젝트 2주차 1번째 PR 입니다. #3
  backend/src/main/java/com/team14/cherrybnb/auth/domain/Member.java
  backend/src/main/java/com/team14/cherrybnb/auth/domain/MemberRepository.java
  backend/src/main/java/com/team14/cherrybnb/common/config/SpringDataJpaConfig.java
  backend/src/main/java/com/team14/cherrybnb/common/config/SwaggerConfig.java
  backend/src/main/java/com/team14/cherrybnb/common/domain/Address.java
  backend/src/main/java/com/team14/cherrybnb/common/util/GeometryUtils.java
  backend/src/main/java/com/team14/cherrybnb/openapi/DistanceInfo.java
  backend/src/main/java/com/team14/cherrybnb/openapi/DistanceInfoResponse.java
  backend/src/main/java/com/team14/cherrybnb/openapi/DistanceSearchController.java
  backend/src/main/java/com/team14/cherrybnb/openapi/DistanceSearchService.java
  backend/src/main/java/com/team14/cherrybnb/openapi/District.java
  backend/src/main/java/com/team14/cherrybnb/openapi/DummyDataService.java
  backend/src/main/java/com/team14/cherrybnb/openapi/Position.java
  backend/src/main/java/com/team14/cherrybnb/revervation/application/ReservationService.java
  backend/src/main/java/com/team14/cherrybnb/revervation/domain/Reservation.java
  backend/src/main/java/com/team14/cherrybnb/revervation/domain/ReservationRepository.java
  backend/src/main/java/com/team14/cherrybnb/revervation/dto/ReservationCardResponse.java
  backend/src/main/java/com/team14/cherrybnb/revervation/dto/ReservationDetailResponse.java
  backend/src/main/java/com/team14/cherrybnb/revervation/dto/ReservationRequest.java
  backend/src/main/java/com/team14/cherrybnb/revervation/ui/ReservationController.java
  backend/src/main/java/com/team14/cherrybnb/room/application/RoomSearchService.java
  backend/src/main/java/com/team14/cherrybnb/room/application/RoomService.java
  backend/src/main/java/com/team14/cherrybnb/room/application/WishService.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/Review.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/ReviewRepository.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/Room.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/RoomImage.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/RoomInfo.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/RoomPriceCondition.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/RoomRepository.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/Wish.java
  backend/src/main/java/com/team14/cherrybnb/room/domain/WishRepository.java
  backend/src/main/java/com/team14/cherrybnb/room/dto/ReviewSummary.java
  backend/src/main/java/com/team14/cherrybnb/room/dto/RoomCardResponse.java
  backend/src/main/java/com/team14/cherrybnb/room/dto/RoomDetailResponse.java
  backend/src/main/java/com/team14/cherrybnb/room/dto/wish/WishCardResponse.java
  backend/src/main/java/com/team14/cherrybnb/room/dto/wish/WishRequest.java
  backend/src/main/java/com/team14/cherrybnb/room/ui/RoomController.java
  backend/src/main/java/com/team14/cherrybnb/room/ui/WishController.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/team14/cherrybnb/common/domain/AddressRepositoryTest.java
Labels: review-BE

#224 [team-2][BB] Airbnb 2주차 PR - 2
  frontend/.gitignore
  frontend/package.json
  frontend/src/@types/import-png.d.ts
  frontend/src/App.tsx
  frontend/src/assets/pause-circle2.svg
  frontend/src/components/Header/SearchBar/ModalInnerItems/ReservationFeeModal/PriceChart.tsx
  frontend/src/components/Header/SearchBar/ModalInnerItems/ReservationFeeModal/PriceSelectArea.tsx
  frontend/src/components/Header/SearchBar/ModalInnerItems/ReservationFeeModal/RangeSlider.tsx
  frontend/src/components/Header/SearchBar/ModalInnerItems/ReservationFeeModal/ReservationFeeModal.style.ts
  frontend/src/components/Header/SearchBar/SearchBar.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/ReservationFee.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/SelectItem.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItemArea.style.ts
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItemArea.tsx
  frontend/src/components/Main/Main.tsx
  frontend/src/contexts/QueryContexts.tsx
  frontend/src/contexts/contexts.ts
  frontend/src/index.tsx
  frontend/src/router/Contexts.ts
  frontend/src/router/Link.tsx
  frontend/src/router/index.d.ts
  frontend/src/router/pages.tsx
  frontend/src/router/router.tsx
  frontend/src/styles/theme.ts
  frontend/src/utils/utils.ts
Labels: review-FE

#198 [Team-26][FE][이든-도리] 2주차 02 PR 요청
  .gitignore
  FE/.eslintrc.json
  FE/src/App.tsx
  FE/src/components/Calendar/index.tsx
  FE/src/components/Calendar/style.js
  FE/src/components/CalendarModal/index.tsx
  FE/src/components/CalendarModal/style.js
  FE/src/components/CanvasLineCharts/index.tsx
  FE/src/components/Chart/index.tsx
  FE/src/components/PriceChart/index.tsx
  FE/src/components/PriceChart/style.js
  FE/src/components/SVGLineChart/index.tsx
  FE/src/constants/constants.js
Labels: review-FE

#226 [Team-27][FE][Khan-sonya] 2주차 두번째 PR
  airbnb/package-lock.json
  airbnb/package.json
  airbnb/src/assets/svg/deleteBtn.svg
  airbnb/src/assets/svg/minusBtn.svg
  airbnb/src/assets/svg/piusBtn.svg
  airbnb/src/components/Calendar/CalendarBody.tsx
  airbnb/src/components/Calendar/CalendarDates.jsx
  airbnb/src/components/Calendar/CalendarDates.tsx
  airbnb/src/components/Calendar/CalendarHead.tsx
  airbnb/src/components/Calendar/CalendarModal.tsx
  airbnb/src/components/Modal/Modal.jsx
  airbnb/src/components/Modal/ModalStyle.jsx
  airbnb/src/components/Modal/RenderModal.jsx
  airbnb/src/components/PriceRange/Canvas.jsx
  airbnb/src/components/PriceRange/PriceRange.jsx
  airbnb/src/components/PriceRange/Slider.jsx
  airbnb/src/components/SearchBar/CheckInOut.jsx
  airbnb/src/components/SearchBar/Personnel.jsx
  airbnb/src/components/SearchBar/SearchBar.jsx
  airbnb/src/components/personnel/PersonnelItem.jsx
  airbnb/src/components/personnel/PersonnelModal.jsx
  airbnb/src/contexts/CalendarProvider.jsx
  airbnb/src/contexts/CalendarProvider.tsx
  airbnb/src/hooks/useInputDispatch.tsx
  airbnb/src/hooks/useInputState.tsx
  airbnb/src/utility/dateUtil.js
Labels: review-FE

#205 [Team-13][BE][제리&쿠킴] - GET /api/rooms/{room_id} 숙박 디테일 조회 기능 구현
  .github/workflows/build-and-depoly-to-aws.yml
  BE/src/main/java/team13/kuje/airbnb/controller/EventController.java
  BE/src/main/java/team13/kuje/airbnb/controller/PlaceController.java
  BE/src/main/java/team13/kuje/airbnb/controller/RoomsController.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/EventDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/RoomDetailDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/RoomDetailPriceDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/WrapperDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/WrapperDtoList.java
  BE/src/main/java/team13/kuje/airbnb/domain/Event.java
  BE/src/main/java/team13/kuje/airbnb/domain/Host.java
  BE/src/main/java/team13/kuje/airbnb/domain/Place.java
  BE/src/main/java/team13/kuje/airbnb/domain/Position.java
  BE/src/main/java/team13/kuje/airbnb/domain/ReservationGuest.java
  BE/src/main/java/team13/kuje/airbnb/domain/ReservationPeriod.java
  BE/src/main/java/team13/kuje/airbnb/domain/Room.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomImage.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomPrice.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomPriceInfo.java
  BE/src/main/java/team13/kuje/airbnb/repository/PlaceRepository.java
  BE/src/main/java/team13/kuje/airbnb/repository/RoomsRepository.java
  BE/src/main/java/team13/kuje/airbnb/service/PlaceService.java
  BE/src/main/java/team13/kuje/airbnb/service/RoomsService.java
  BE/src/main/java/team13/kuje/airbnb/util/MapUtils.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/team13/kuje/airbnb/acceptance/EventAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/PlaceAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/RoomsAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/ReservationGuestTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/ReservationPeriodTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/RoomPriceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/EventServiceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/PlaceServiceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/RoomsServiceTest.java
  BE/src/test/resources/application.yml
  BE/src/test/resources/testdb/data.sql
  BE/src/test/resources/testdb/schema.sql
Labels: review-BE

#214 [Team-18][BE][타니&검봉] - 2주차 마지막 PR
  BE/README.md
  BE/src/main/java/team18/airbnb/AirbnbApplication.java
  BE/src/main/java/team18/airbnb/domain/Accommodation.java
  BE/src/main/java/team18/airbnb/domain/AccommodationAddress.java
  BE/src/main/java/team18/airbnb/domain/AccommodationImg.java
  BE/src/main/java/team18/airbnb/domain/AccommodationInfo.java
  BE/src/main/java/team18/airbnb/domain/AccommodationSubImg.java
  BE/src/main/java/team18/airbnb/domain/Region.java
  BE/src/main/java/team18/airbnb/domain/Reservation.java
  BE/src/main/java/team18/airbnb/domain/ReservationFee.java
  BE/src/main/java/team18/airbnb/domain/User.java
  BE/src/main/java/team18/airbnb/home/HomeController.java
  BE/src/main/java/team18/airbnb/region/RegionController.java
  BE/src/main/java/team18/airbnb/region/RegionRepository.java
  BE/src/main/java/team18/airbnb/region/RegionService.java
  BE/src/main/java/team18/airbnb/region/dto/AccommodationByConceptDto.java
  BE/src/main/java/team18/airbnb/region/dto/HomeLayoutDto.java
  BE/src/main/java/team18/airbnb/reservation/ReservationController.java
  BE/src/main/java/team18/airbnb/reservation/ReservationRepository.java
  BE/src/main/java/team18/airbnb/reservation/ReservationService.java
  BE/src/main/java/team18/airbnb/reservation/dto/UserReservationDto.java
  BE/src/main/java/team18/airbnb/search/SearchController.java
  BE/src/main/resources/data/data.sql
  BE/src/test/java/team18/airbnb/home/RegionServiceTest.java
Labels: review-BE

#188 [team-31][FE] Muffin & Park 2주차 금요일
  .eslintrc.js
  src/App.tsx
  src/common/keyframes.tsx
  src/common/theme.tsx
  src/components/Background.tsx
  src/components/Calendar/MonthCard/ClickableDate.jsx
  src/components/Calendar/MonthCards/MonthCard/CardBody/ClickableDate.jsx
  src/components/Calendar/MonthCards/MonthCard/CardBody/index.jsx
  src/components/Calendar/MonthCards/MonthCard/CardTitle.jsx
  src/components/Calendar/MonthCards/MonthCard/index.jsx
  src/components/Calendar/MonthCards/index.jsx
  src/components/Calendar/MonthNav/index.jsx
  src/components/Calendar/index.jsx
  src/components/Calendar/useCalendar.jsx
  src/components/Chart/Graph.tsx
  src/components/Chart/Title.tsx
  src/components/Chart/index.tsx
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/components/Header/BigSearchBar/BigMenus.tsx
  src/components/Header/BigSearchBar/Modal/index.tsx
  src/components/Header/BigSearchBar/index.tsx
  src/components/Header/Category.tsx
  src/components/Header/MiniSearchBar/Menu.tsx
  src/components/Header/MiniSearchBar/index.tsx
  src/components/Header/UserInfo.tsx
  src/components/Header/index.tsx
  src/components/Persons/index.tsx
  src/constants/widths.ts
  src/contexts/PersonProvider.tsx
  src/contexts/PriceProvider.tsx
  src/mocks/room.js
  tsconfig.json
Labels: review-FE

#229 [team-36 | dony & yellow] 2주차 2번째 PR 요청드립니다.
  src/assets/images/icon_chevronLeft.svg
  src/assets/images/icon_chevronRight.svg
  src/components/Calendar/DateUnit.jsx
  src/components/Calendar/WeekDays.jsx
  src/components/Calendar/YearMonth.jsx
  src/components/Calendar/index.jsx
  src/components/Modal/PeriodModal.jsx
  src/components/Modal/PriceModal.tsx
  src/components/Modal/index.style.tsx
  src/components/SearchBar/SearchInputButton.style.tsx
  src/components/SearchBar/SearchInputButton.tsx
  src/components/SearchBar/index.style.tsx
  src/components/SearchBar/index.tsx
  src/components/common/IconButton.style.tsx
  src/components/common/IconButton.tsx
  src/constants/date.ts
  src/constants/index.ts
  src/constants/reservation.ts
  src/constants/type.ts
  src/contexts/ReservationInfoProvider.tsx
  src/contexts/SelectedModalProvider.tsx
  src/layout/index.tsx
  src/mocks/handlers.ts
Labels: review-FE

#195 [Team-03] MVVM 패턴 적용
  ios/AirBnb/AirBnb.xcodeproj/project.pbxproj
  ios/AirBnb/AirBnb/Data/PersistentStorage/ImageCacheStorage/DefaultImageCacheStorage.swift
  ios/AirBnb/AirBnb/Data/PersistentStorage/ImageCacheStorage/ImageCacheStorage.swift
  ios/AirBnb/AirBnb/Data/Repositories/DefaultImageRepository.swift
  ios/AirBnb/AirBnb/Domain/Entities/City.swift
  ios/AirBnb/AirBnb/Domain/Interfaces/ImageFactory.swift
  ios/AirBnb/AirBnb/Domain/UseCases/FetchImageUseCase.swift
  ios/AirBnb/AirBnb/Infrastructures/NetworkService.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/HomeViewController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/View/HeroCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/View/NearCityCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/View/RecommendationCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/View/TitleSupplementaryView.swift
Labels: review-iOS

#212 [Team 18 - Android] 인원 입력 및 숙소 검색 결과
  app/build.gradle
  app/src/main/java/com/example/todo/airbnb/common/components/HadleImage.kt
  app/src/main/java/com/example/todo/airbnb/common/components/ToastMessage.kt
  app/src/main/java/com/example/todo/airbnb/data/Travel.kt
  app/src/main/java/com/example/todo/airbnb/domain/model/Personnel.kt
  app/src/main/java/com/example/todo/airbnb/domain/model/Search.kt
  app/src/main/java/com/example/todo/airbnb/presentation/main/components/BottomBar.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/SearchViewModel.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/date/components/DateScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/fare/components/Fare.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/main/AccommodationsScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/main/SearchScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/main/TravelScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/personnel/PersonnelScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/personnel/components/PersonnelScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/searchresult/SearchResultScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/searchresult/components/SearchResultScreen.kt
  app/src/main/res/drawable/ic_outline_add_circle.xml
  app/src/main/res/drawable/ic_outline_remove_circle.xml
Labels: review-android

#220 [Team-17 BE] airbnb 프로젝트 2주차 금요일 PR입니다.
  backend/.gitignore
  backend/src/main/java/kr/codesquad/airbnb/accomodation/controller/AccommodationController.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/Accommodation.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/AccommodationImage.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/AccommodationInfo.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/AccommodationType.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/Amenity.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/Host.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/domain/Report.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/dto/AccommodationResponse.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/dto/AccommodationSearchRequest.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/dto/AccommodationsResponse.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/service/AccommodationService.java
  backend/src/main/java/kr/codesquad/airbnb/accomodation/web/AccommodationService.java
  backend/src/main/java/kr/codesquad/airbnb/config/QueryDSLConfig.java
  backend/src/main/java/kr/codesquad/airbnb/reservation/controller/ReservationController.java
  backend/src/main/java/kr/codesquad/airbnb/reservation/domain/Reservation.java
  backend/src/main/java/kr/codesquad/airbnb/reservation/domain/ReservationRepository.java
  backend/src/main/java/kr/codesquad/airbnb/reservation/domain/User.java
  backend/src/main/java/kr/codesquad/airbnb/reservation/domain/WishList.java
  backend/src/main/java/kr/codesquad/airbnb/reservation/dto/ReservationRequest.java
  backend/src/main/java/kr/codesquad/airbnb/reservation/dto/ReservationResponse.java
  backend/src/main/java/kr/codesquad/airbnb/reservation/dto/Result.java
  backend/src/main/java/kr/codesquad/airbnb/reservation/service/ReservationService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
Labels: review-BE

#254 [Team-24][BE] airbnb 프로젝트 PR #4
  be/build.gradle
  be/src/main/generated/kr/codesquad/airbnb/domain/QAmenity.java
  be/src/main/generated/kr/codesquad/airbnb/domain/QBooking.java
  be/src/main/generated/kr/codesquad/airbnb/domain/QDiscountTax.java
  be/src/main/generated/kr/codesquad/airbnb/domain/QGuest.java
  be/src/main/generated/kr/codesquad/airbnb/domain/QLocation.java
  be/src/main/generated/kr/codesquad/airbnb/domain/QMember.java
  be/src/main/generated/kr/codesquad/airbnb/domain/QRoom.java
  be/src/main/generated/kr/codesquad/airbnb/domain/QRoomAmenity.java
  be/src/main/generated/kr/codesquad/airbnb/domain/QRoomDiscountTax.java
  be/src/main/java/kr/codesquad/airbnb/AuthenticationFilter.java
  be/src/main/java/kr/codesquad/airbnb/config/QueryDslConfig.java
  be/src/main/java/kr/codesquad/airbnb/controller/BookingController.java
  be/src/main/java/kr/codesquad/airbnb/controller/RoomController.java
  be/src/main/java/kr/codesquad/airbnb/domain/Booking.java
  be/src/main/java/kr/codesquad/airbnb/domain/DiscountPolicy.java
  be/src/main/java/kr/codesquad/airbnb/domain/TaxPolicy.java
  be/src/main/java/kr/codesquad/airbnb/dto/AmenityDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/BookingDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/BookingRoomRequest.java
  be/src/main/java/kr/codesquad/airbnb/dto/CategorizedPrice.java
  be/src/main/java/kr/codesquad/airbnb/dto/DiscountTaxDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/RangeOfPrice.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomPriceStatistic.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomPriceStatisticDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomPriceStatisticRequest.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomSearchDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomSearchRequest.java
  be/src/main/java/kr/codesquad/airbnb/exception/ErrorCode.java
  be/src/main/java/kr/codesquad/airbnb/exception/GlobalExceptionHandler.java
  be/src/main/java/kr/codesquad/airbnb/repository/BookingRepository.java
  be/src/main/java/kr/codesquad/airbnb/repository/CustomBookingRepository.java
  be/src/main/java/kr/codesquad/airbnb/repository/CustomBookingRepositoryImpl.java
  be/src/main/java/kr/codesquad/airbnb/repository/CustomRoomRepository.java
  be/src/main/java/kr/codesquad/airbnb/repository/CustomRoomRepositoryImpl.java
  be/src/main/java/kr/codesquad/airbnb/repository/MemberRepository.java
  be/src/main/java/kr/codesquad/airbnb/repository/RoomRepository.java
  be/src/main/java/kr/codesquad/airbnb/response/CommonResponse.java
  be/src/main/java/kr/codesquad/airbnb/response/ErrorResponse.java
  be/src/main/java/kr/codesquad/airbnb/service/BookingService.java
  be/src/main/java/kr/codesquad/airbnb/service/MemberService.java
  be/src/main/java/kr/codesquad/airbnb/service/RoomService.java
  be/src/main/java/kr/codesquad/airbnb/util/Validator.java
  be/src/main/resources/sql/data.sql
  be/src/test/java/kr/codesquad/airbnb/controller/RoomControllerTest.java
  be/src/test/java/kr/codesquad/airbnb/repository/RoomRepositoryTest.java
  be/src/test/java/kr/codesquad/airbnb/service/RoomServiceTest.java
Labels: review-BE

#267 [Team23 땃쥐] airbnb 5차 PR
  BE/src/main/java/codesquad/airbnb/accommodation/domain/Accommodation.java
  BE/src/main/java/codesquad/airbnb/accommodation/domain/AccommodationImage.java
  BE/src/main/java/codesquad/airbnb/accommodation/domain/Facility.java
  BE/src/main/java/codesquad/airbnb/accommodation/domain/Location.java
  BE/src/main/java/codesquad/airbnb/accommodation/dto/AccommodationSearchCondition.java
  BE/src/main/java/codesquad/airbnb/accommodation/repository/AccommodationCustomRepository.java
  BE/src/main/java/codesquad/airbnb/accommodation/repository/AccommodationRepository.java
  BE/src/main/java/codesquad/airbnb/accommodation/repository/AccommodationRepositoryImpl.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/AccommodationController.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationListElement.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationListRequest.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationListResponse.java
  BE/src/main/java/codesquad/airbnb/review/domain/Review.java
  BE/src/main/java/codesquad/airbnb/util/RandomValueGenerator.java
  BE/src/test/java/codesquad/airbnb/querydsl/QuerydslTest.java
Labels: review-BE

#260 [Team 28 FE Maeve & JinJeon] Airbnb 프로젝트 3주차(수요일) PR
  src/App.tsx
  src/Component/Header/GNB/GNB.styled.tsx
  src/Component/Header/GNB/GNB.tsx
  src/Component/Header/Header.styled.tsx
  src/Component/Header/Header.tsx
  src/Component/Header/Modal/CalendarDetail.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/Calendar.styled.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/Calendar.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/CalendarCell.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/CalendarDayBox.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/CalendarTitle.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.styled.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.tsx
  src/Component/Header/Modal/Modal.styled.tsx
  src/Component/Header/Modal/PriceDetail.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniGuest/MiniGuest.styled.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniGuest/MiniGuest.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniPrice/MiniPrice.styled.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniPrice/MiniPrice.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniSchedule/MiniSchedule.styled.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniSchedule/MiniSchedule.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniSearchBar.styled.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniSearchBar.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.tsx
  src/Component/Header/SearchBar/SearchBar.styled.tsx
  src/Component/Header/SearchBar/SearchBar.tsx
  src/Component/Header/SearchBar/SmallSearchBar.styled.tsx
  src/Component/Header/SearchBar/SmallSearchBar.tsx
  src/Styles/Normalize.jsx
  src/Styles/theme.js
  src/util/util.tsx
Labels: review-FE

#228 [Team-04][BE][테리 & Sammy] 4번째 PR
  BE/docs/airbnb_default_data.sql
  BE/docs/airbnb_table_create.sql
  BE/src/main/java/org/team4/airbnb/AirbnbApplication.java
  BE/src/main/java/org/team4/airbnb/accommodation/Accommodation.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationRepository.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationType.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationTypeConverter.java
  BE/src/main/java/org/team4/airbnb/accommodation/RoomFeature.java
  BE/src/main/java/org/team4/airbnb/customer/Customer.java
  BE/src/main/java/org/team4/airbnb/customer/CustomerController.java
  BE/src/main/java/org/team4/airbnb/customer/CustomerRepository.java
  BE/src/main/java/org/team4/airbnb/customer/CustomerService.java
  BE/src/main/java/org/team4/airbnb/customer/dto/AccommodationForWishListResponse.java
  BE/src/main/java/org/team4/airbnb/domain/BaseCreated.java
  BE/src/main/java/org/team4/airbnb/dummydata/ApiCallParseController.java
  BE/src/main/java/org/team4/airbnb/exception/AccommodationNotFoundException.java
  BE/src/main/java/org/team4/airbnb/exception/AccommodationTypeNotFoundException.java
  BE/src/main/java/org/team4/airbnb/exception/BusinessException.java
  BE/src/main/java/org/team4/airbnb/exception/CustomExceptionHandler.java
  BE/src/main/java/org/team4/airbnb/exception/CustomerNotFoundException.java
  BE/src/main/java/org/team4/airbnb/exception/ErrorCode.java
  BE/src/main/java/org/team4/airbnb/exception/ErrorResponse.java
  BE/src/main/java/org/team4/airbnb/exception/NotFoundException.java
  BE/src/main/java/org/team4/airbnb/exception/ReservationNotFoundException.java
  BE/src/main/java/org/team4/airbnb/reservation/Invoice.java
  BE/src/main/java/org/team4/airbnb/reservation/Reservation.java
  BE/src/main/java/org/team4/airbnb/reservation/ReservationController.java
  BE/src/main/java/org/team4/airbnb/reservation/ReservationRepository.java
  BE/src/main/java/org/team4/airbnb/reservation/ReservationService.java
  BE/src/main/java/org/team4/airbnb/reservation/dto/ReservationRequest.java
  BE/src/main/java/org/team4/airbnb/reservation/dto/ReservationResponse.java
  BE/src/main/java/org/team4/airbnb/wish/Wish.java
  BE/src/main/java/org/team4/airbnb/wish/WishRepository.java
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/logback.xml
  BE/src/test/java/org/team4/airbnb/accommodation/AccommodationRepositoryTest.java
  BE/src/test/java/org/team4/airbnb/customer/CustomerRepositoryTest.java
  BE/src/test/java/org/team4/airbnb/reservation/ReservationRepositoryTest.java
  BE/src/test/java/org/team4/airbnb/util/EntityCreator.java
  BE/src/test/java/org/team4/airbnb/wish/WishRepositoryTest.java
Labels: review-BE

#263 [team-29][아울 & 난정]3주차 수요일 PR
  mockData.json
  package-lock.json
  package.json
  src/App.jsx
  src/ClickedTabProvider.jsx
  src/assets/leftArrow.svg
  src/assets/rightArrow.svg
  src/components/header/modal/CalendarModal.jsx
  src/components/header/modal/GuestModal.jsx
  src/components/header/modal/GuestTab.jsx
  src/components/header/modal/Modal.js
  src/components/header/modal/PriceModal.jsx
  src/components/header/searchBar/CheckIn.jsx
  src/components/header/searchBar/CheckOut.jsx
  src/components/header/searchBar/CylindricalBox.jsx
  src/components/header/searchBar/GuestBox.jsx
  src/components/header/searchBar/MiniSearchBar.jsx
  src/components/header/searchBar/PriceBox.jsx
  src/components/header/searchBar/SearchBar.jsx
  src/components/header/searchBar/SearchPageSeacrhBar.jsx
  src/components/main/searchMain/AccomodationList.jsx
  src/components/main/searchMain/AccomodationListItem.jsx
  src/constants.js
  src/contexts/OptionProvider.jsx
  src/contexts/PeriodProvider.jsx
  src/contexts/SearchBarClickedTabProvider.jsx
  src/helper/constants.js
  src/helper/mockData.js
  src/helper/theme.js
  src/helper/util.js
  src/lib/Calendar.jsx
  src/lib/Calendar/Days.jsx
  src/lib/Calendar/Month.jsx
  src/lib/Calendar/Week.jsx
  src/lib/CalendarContext.jsx
  src/lib/Days.jsx
  src/lib/util.js
  src/pages/Home.jsx
Labels: review-FE

#246 [Team-12] 루이 & 동기 3주차 첫번째 PR
  BE/build.gradle
  BE/src/main/java/louie/dong/airbnb/accommodation/Accommodation.java
  BE/src/main/java/louie/dong/airbnb/accommodation/AccommodationController.java
  BE/src/main/java/louie/dong/airbnb/accommodation/AccommodationImage.java
  BE/src/main/java/louie/dong/airbnb/accommodation/AccommodationRepository.java
  BE/src/main/java/louie/dong/airbnb/accommodation/AccommodationService.java
  BE/src/main/java/louie/dong/airbnb/accommodation/DiscountPolicy.java
  BE/src/main/java/louie/dong/airbnb/accommodation/ImageType.java
  BE/src/main/java/louie/dong/airbnb/accommodation/MockAccommodationService.java
  BE/src/main/java/louie/dong/airbnb/accommodation/RoomInformation.java
  BE/src/main/java/louie/dong/airbnb/accommodation/dto/AccommodationDetailResponse.java
  BE/src/main/java/louie/dong/airbnb/accommodation/dto/AccommodationResponse.java
  BE/src/main/java/louie/dong/airbnb/accommodation/dto/AccommodationSearchRequest.java
  BE/src/main/java/louie/dong/airbnb/banner/BannerController.java
  BE/src/main/java/louie/dong/airbnb/book/Book.java
  BE/src/main/java/louie/dong/airbnb/book/BookController.java
  BE/src/main/java/louie/dong/airbnb/book/BookRepository.java
  BE/src/main/java/louie/dong/airbnb/book/BookService.java
  BE/src/main/java/louie/dong/airbnb/book/MockBockService.java
  BE/src/main/java/louie/dong/airbnb/book/dto/BookDetailResponse.java
  BE/src/main/java/louie/dong/airbnb/book/dto/BookResponse.java
  BE/src/main/java/louie/dong/airbnb/book/dto/BookSaveRequest.java
  BE/src/main/java/louie/dong/airbnb/region/MockRegionService.java
  BE/src/main/java/louie/dong/airbnb/travel/TravelController.java
  BE/src/main/java/louie/dong/airbnb/wishlist/MockWishListService.java
  BE/src/main/java/louie/dong/airbnb/wishlist/Wish.java
  BE/src/main/java/louie/dong/airbnb/wishlist/WishController.java
  BE/src/main/java/louie/dong/airbnb/wishlist/WishRepository.java
  BE/src/main/java/louie/dong/airbnb/wishlist/WishService.java
  BE/src/main/java/louie/dong/airbnb/wishlist/dto/WishListResponse.java
  BE/src/main/java/louie/dong/airbnb/wishlist/dto/WishResponse.java
  BE/src/main/java/louie/dong/airbnb/wishlist/dto/WishSaveRequest.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/static/docs/index.html
  BE/src/test/java/louie/dong/airbnb/integration/AccommodationIntegrationTest.java
  BE/src/test/java/louie/dong/airbnb/integration/BannerIntegrationTest.java
  BE/src/test/java/louie/dong/airbnb/integration/BookIntegrationTest.java
  BE/src/test/java/louie/dong/airbnb/integration/RegionIntegrationTest.java
  BE/src/test/java/louie/dong/airbnb/integration/TravelIntegrationTest.java
  BE/src/test/java/louie/dong/airbnb/integration/WishListIntegrationTest.java
Labels: review-BE

#280 [Team-03] 3주차 첫번째 PR
  fe/.eslintrc
  fe/src/App.tsx
  fe/src/Portal.tsx
  fe/src/components/GNB/AccountMenu/AccountMenu.tsx
  fe/src/components/GNB/GNB.tsx
  fe/src/components/GNB/Logo/Logo.tsx
  fe/src/components/GNB/Menu/Menu.tsx
  fe/src/components/Modal/Modal.styled.ts
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/Period/Callendar/Callendar.styled.ts
  fe/src/components/Modal/Period/Callendar/Callendar.tsx
  fe/src/components/Modal/Period/Period.styled.ts
  fe/src/components/Modal/Period/Period.tsx
  fe/src/components/Modal/Personnel/Personnel.styled.ts
  fe/src/components/Modal/Personnel/Personnel.tsx
  fe/src/components/Routers/Routers.tsx
  fe/src/components/SearchBar/Period/Period.tsx
  fe/src/components/SearchBar/Personnel/Personnel.tsx
  fe/src/components/SearchBar/Price/Price.tsx
  fe/src/components/SearchBar/SearchBar.styled.tsx
  fe/src/components/SearchBar/SearchBar.tsx
  fe/src/components/SearchBar/SearchList/DeleteButton.tsx
  fe/src/components/SearchBar/SearchList/SearchList.tsx
  fe/src/components/SearchBar/types.ts
  fe/src/components/common/Section/Section.tsx
  fe/src/context/ModalProvider.tsx
  fe/src/context/SearchProvider.tsx
  fe/src/helpers/constant.ts
  fe/src/img/svg/left.svg
  fe/src/img/svg/minus-circle.svg
  fe/src/img/svg/plus-circle.svg
  fe/src/img/svg/right.svg
  fe/src/img/svg/search-icon.svg
  fe/src/pages/Main/Main.tsx
  fe/src/pages/NotFound.tsx
  fe/src/pages/Search/Search.tsx
Labels: review-FE

#271 [Team 32] [J, 럼카] 3주차 1번째 PR 요청드립니다.
  package.json
  src/components/Accommodations/AccommodationItem.jsx
  src/components/Accommodations/index.jsx
  src/components/App.jsx
  src/components/Header/index.jsx
  src/components/Map/index.jsx
  src/components/PriceModal/RangeSliderController.jsx
  src/components/PriceModal/index.jsx
  src/components/SearchBar/Guest.jsx
  src/components/SearchBar/MiniSearchBar.jsx
  src/components/SearchBar/Price.jsx
  src/components/SearchBar/SearchButton.jsx
  src/mockData/accommodation.js
  src/pages/NoMatch.jsx
  src/reducer/priceReducer.js
  src/store/AccommodationContext.jsx
  src/store/FilterContext.jsx
  src/styles/customOverlay.js
  src/styles/size.js
  src/utils/fromStateToString.js
  src/utils/util.js
Labels: review-FE

#237 [Team - 06][BE] 에어비앤비 프로젝트 3주차 1회차 PR
  BE/README.md
  BE/build.gradle
  BE/scripts/run_new_was.sh
  BE/src/main/java/com/airbnb/AirbnbApplication.java
  BE/src/main/java/com/airbnb/api/houses/HouseController.java
  BE/src/main/java/com/airbnb/api/houses/dto/GraphResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/LocationInformationRequest.java
  BE/src/main/java/com/airbnb/api/houses/dto/NumberOfHousesByPrice.java
  BE/src/main/java/com/airbnb/api/houses/dto/NumberOfHousesByPriceResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/ReservationDetailResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/ReservationInformationRequest.java
  BE/src/main/java/com/airbnb/api/houses/dto/ReservationResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/ReservationsResponse.java
  BE/src/main/java/com/airbnb/api/houses/dto/SearchConditionRequest.java
  BE/src/main/java/com/airbnb/api/interceptor/AuthenticationInterceptor.java
  BE/src/main/java/com/airbnb/api/login/oauth/OAuthLoginController.java
  BE/src/main/java/com/airbnb/api/users/UserController.java
  BE/src/main/java/com/airbnb/api/wish/WishController.java
  BE/src/main/java/com/airbnb/api/wish/dto/WishCreateRequest.java
  BE/src/main/java/com/airbnb/api/wish/dto/WishDeleteRequest.java
  BE/src/main/java/com/airbnb/api/wish/dto/WishListResponse.java
  BE/src/main/java/com/airbnb/api/wish/dto/WishResponse.java
  BE/src/main/java/com/airbnb/common/ResultDto.java
  BE/src/main/java/com/airbnb/domain/House.java
  BE/src/main/java/com/airbnb/domain/Reservation.java
  BE/src/main/java/com/airbnb/domain/User.java
  BE/src/main/java/com/airbnb/domain/Wish.java
  BE/src/main/java/com/airbnb/domain/WishList.java
  BE/src/main/java/com/airbnb/domain/login/OAuthServer.java
  BE/src/main/java/com/airbnb/domain/login/github/GitHubOAuthServer.java
  BE/src/main/java/com/airbnb/domain/login/kakao/KakaoOAuthServer.java
  BE/src/main/java/com/airbnb/repository/HouseRepository.java
  BE/src/main/java/com/airbnb/repository/ReservationRepository.java
  BE/src/main/java/com/airbnb/repository/UserRepository.java
  BE/src/main/java/com/airbnb/repository/WishRepository.java
  BE/src/main/java/com/airbnb/service/HouseService.java
  BE/src/main/java/com/airbnb/service/LoginService.java
  BE/src/main/java/com/airbnb/service/WishService.java
  BE/src/main/java/com/airbnb/utils/geometry/GeometryUtils.java
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/application-test.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/sql/data.sql
  BE/src/test/java/com/airbnb/api/houses/HouseControllerTest.java
  BE/src/test/java/com/airbnb/repository/HouseRepositoryTest.java
  BE/src/test/java/com/airbnb/repository/ReservationRepositoryTest.java
  BE/src/test/java/com/airbnb/service/HouseServiceTest.java
  BE/src/test/java/com/airbnb/wish/integrate/WishControllerTest.java
  BE/src/test/java/com/airbnb/wish/unit/WishServiceTest.java
  BE/src/test/resources/application.yml
Labels: review-BE

#269 [Android] Team15 - 구글 지도 불러오기 & Search Result 페이징 처리
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/airbnb/CertificationWorker.kt
  android/app/src/main/java/com/example/airbnb/DownloadBroadcastReceiver.kt
  android/app/src/main/java/com/example/airbnb/MapActivity.kt
  android/app/src/main/java/com/example/airbnb/SearchResultFragment.kt
  android/app/src/main/java/com/example/airbnb/common/BindModule.kt
  android/app/src/main/java/com/example/airbnb/common/common.kt
  android/app/src/main/java/com/example/airbnb/common/notification.kt
  android/app/src/main/java/com/example/airbnb/data/mainrepository/MainDataSource.kt
  android/app/src/main/java/com/example/airbnb/data/mainrepository/MainMainDataSourceImpl.kt
  android/app/src/main/java/com/example/airbnb/data/mainrepository/MainRepository.kt
  android/app/src/main/java/com/example/airbnb/data/model/Marker.kt
  android/app/src/main/java/com/example/airbnb/data/repository/DataSource.kt
  android/app/src/main/java/com/example/airbnb/data/repository/DataSourceImpl.kt
  android/app/src/main/java/com/example/airbnb/data/repository/Repository.kt
  android/app/src/main/java/com/example/airbnb/data/searchresultrepository/SearchResultDataSource.kt
  android/app/src/main/java/com/example/airbnb/data/searchresultrepository/SearchResultDataSourceImpl.kt
  android/app/src/main/java/com/example/airbnb/data/searchresultrepository/SearchResultRepository.kt
  android/app/src/main/java/com/example/airbnb/network/APIService.kt
  android/app/src/main/java/com/example/airbnb/network/common/NetworkResponse.kt
  android/app/src/main/java/com/example/airbnb/network/common/NetworkResponseAdapterFactory.kt
  android/app/src/main/java/com/example/airbnb/network/dto/HeroImage.kt
  android/app/src/main/java/com/example/airbnb/network/dto/MainEvent.kt
  android/app/src/main/java/com/example/airbnb/network/dto/MainRegions.kt
  android/app/src/main/java/com/example/airbnb/network/dto/PostLocation.kt
  android/app/src/main/java/com/example/airbnb/network/dto/SearchContents.kt
  android/app/src/main/java/com/example/airbnb/network/dto/SearchResult.kt
  android/app/src/main/java/com/example/airbnb/ui/MainActivity.kt
  android/app/src/main/java/com/example/airbnb/ui/common/BindingAdapter.kt
  android/app/src/main/java/com/example/airbnb/ui/common/ButtonState.kt
  android/app/src/main/java/com/example/airbnb/ui/compose/CustomRoundButton.kt
  android/app/src/main/java/com/example/airbnb/ui/myreservation/MyReservationFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/placesearch/PlaceSearchFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/search/SearchFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/search/ViewModel.kt
  android/app/src/main/java/com/example/airbnb/ui/searchresult/SearchResultFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/searchresult/SearchResultPagingAdapter.kt
  android/app/src/main/java/com/example/airbnb/ui/searchresult/SearchResultPagingSource.kt
  android/app/src/main/java/com/example/airbnb/ui/searchresult/SearchResultViewModel.kt
  android/app/src/main/java/com/example/airbnb/ui/settingcompose/PriceSettingFragment.kt
  android/app/src/main/java/com/example/airbnb/ui/settingcompose/SettingViewModel.kt
  android/app/src/main/res/drawable/custom_button_background.xml
  android/app/src/main/res/drawable/custom_map_marker.xml
  android/app/src/main/res/drawable/ic_baseline_hotel_24.xml
  android/app/src/main/res/drawable/ic_baseline_menu_24.xml
  android/app/src/main/res/layout/activity_map.xml
  android/app/src/main/res/layout/custom_marker.xml
  android/app/src/main/res/layout/custom_round_button.xml
  android/app/src/main/res/layout/fragment_my_reservation.xml
  android/app/src/main/res/layout/fragment_search.xml
  android/app/src/main/res/layout/fragment_search_result.xml
  android/app/src/main/res/layout/item_close_travel.xml
  android/app/src/main/res/layout/item_search_result.xml
  android/app/src/main/res/navigation/navigation.xml
  android/app/src/main/res/values-night/strings.xml
  android/app/src/main/res/values/attr.xml
  android/app/src/main/res/values/strings.xml
Labels: review-android

#235 [Team-15][BE] 포키&나단의 airbnb 프로젝트 PR4
  backend/build.gradle
  backend/src/main/java/team15/airbnb/accommodation/application/AccommodationService.java
  backend/src/main/java/team15/airbnb/accommodation/domain/Accommodation.java
  backend/src/main/java/team15/airbnb/accommodation/domain/DiscountPolicy.java
  backend/src/main/java/team15/airbnb/accommodation/domain/Vat.java
  backend/src/main/java/team15/airbnb/accommodation/infrastructure/AccommodationRepository.java
  backend/src/main/java/team15/airbnb/accommodation/presentation/controller/AccommodationController.java
  backend/src/main/java/team15/airbnb/accommodation/presentation/dto/AccommodationFeeDto.java
  backend/src/main/java/team15/airbnb/accommodation/presentation/dto/AccommodationFeesResponse.java
  backend/src/main/java/team15/airbnb/accommodation/presentation/dto/AccommodationListResponse.java
  backend/src/main/java/team15/airbnb/accommodation/presentation/dto/AccommodationSimpleInfoResponse.java
  backend/src/main/java/team15/airbnb/accommodation/presentation/dto/SearchAccommodationsByOptionsResponse.java
  backend/src/main/java/team15/airbnb/accommodation/presentation/dto/SearchAccommodationsOptionsRequest.java
  backend/src/main/java/team15/airbnb/category/application/CategoryService.java
  backend/src/main/java/team15/airbnb/category/infrastructure/AirbnbMySqlDialect.java
  backend/src/main/java/team15/airbnb/category/infrastructure/RegionRepository.java
  backend/src/main/java/team15/airbnb/category/presentation/controller/CategoryController.java
  backend/src/main/java/team15/airbnb/category/presentation/dto/RegionDistanceDto.java
  backend/src/main/java/team15/airbnb/category/presentation/dto/RegionResponse.java
  backend/src/main/java/team15/airbnb/common/domain/BaseEntity.java
  backend/src/main/java/team15/airbnb/reservation/application/.keep
  backend/src/main/java/team15/airbnb/reservation/application/ReservationService.java
  backend/src/main/java/team15/airbnb/reservation/domain/Reservation.java
  backend/src/main/java/team15/airbnb/reservation/infrastructure/.keep
  backend/src/main/java/team15/airbnb/reservation/infrastructure/ReservationRepository.java
  backend/src/main/java/team15/airbnb/reservation/presentation/.keep
  backend/src/main/java/team15/airbnb/reservation/presentation/controller/ReservationController.java
  backend/src/main/java/team15/airbnb/reservation/presentation/dto/PreviewResponse.java
  backend/src/main/java/team15/airbnb/reservation/presentation/dto/ReservationDetailsDto.java
  backend/src/main/java/team15/airbnb/reservation/presentation/dto/ReservationDetailsResponse.java
  backend/src/main/java/team15/airbnb/reservation/presentation/dto/ReservationDto.java
  backend/src/main/java/team15/airbnb/reservation/presentation/dto/ReservationResponse.java
  backend/src/main/java/team15/airbnb/reservation/presentation/dto/ReserveDto.java
  backend/src/main/java/team15/airbnb/search/application/AutoCompleteService.java
  backend/src/main/java/team15/airbnb/search/infrastructure/AutoCompleteRepository.java
  backend/src/main/java/team15/airbnb/search/presentation/AutoCompleteController.java
  backend/src/main/java/team15/airbnb/search/presentation/dto/RecommendedKeywordListResponse.java
  backend/src/main/java/team15/airbnb/user/application/.keep
  backend/src/main/java/team15/airbnb/user/application/FavoriteService.java
  backend/src/main/java/team15/airbnb/user/domain/Favorite.java
  backend/src/main/java/team15/airbnb/user/domain/User.java
  backend/src/main/java/team15/airbnb/user/domain/UserType.java
  backend/src/main/java/team15/airbnb/user/infrastructure/.keep
  backend/src/main/java/team15/airbnb/user/infrastructure/FavoriteRepository.java
  backend/src/main/java/team15/airbnb/user/infrastructure/UserRepository.java
  backend/src/main/java/team15/airbnb/user/presentation/.keep
  backend/src/main/java/team15/airbnb/user/presentation/controller/FavoriteController.java
  backend/src/main/java/team15/airbnb/user/presentation/dto/AddFavoriteRequest.java
  backend/src/main/java/team15/airbnb/user/presentation/dto/DeleteFavoriteRequest.java
  backend/src/main/java/team15/airbnb/user/presentation/dto/FavoriteDto.java
  backend/src/main/java/team15/airbnb/user/presentation/dto/FavoritesResponse.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/team15/airbnb/user/infrastructure/UserRepositoryClassTest.java
Labels: review-BE

#274 [Team-24][FE] Jinnie & Jamie 3주차 첫번째 PR
  FE/package-lock.json
  FE/package.json
  FE/src/assets/icons/index.ts
  FE/src/assets/icons/next.svg
  FE/src/assets/icons/pause.svg
  FE/src/assets/icons/prev.svg
  FE/src/components/Calendar/Calendar.style.js
  FE/src/components/Calendar/Day.tsx
  FE/src/components/Calendar/Month.tsx
  FE/src/components/Calendar/RenderCalendar.tsx
  FE/src/components/Calendar/Week.tsx
  FE/src/components/Calendar/index.tsx
  FE/src/components/ChartSlider/Chart/Chart.stories.tsx
  FE/src/components/ChartSlider/Chart/Chart.style.ts
  FE/src/components/ChartSlider/Chart/index.tsx
  FE/src/components/ChartSlider/ChartSlider.stories.tsx
  FE/src/components/ChartSlider/RangeSlider/RangeSlider.style.ts
  FE/src/components/ChartSlider/RangeSlider/index.tsx
  FE/src/components/ChartSlider/index.tsx
  FE/src/components/Footer/FooterContent.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/MainContent/MainSection.tsx
  FE/src/components/SearchBar/Modal/Modal.style.ts
  FE/src/components/SearchBar/Modal/PriceModal.tsx
  FE/src/components/SearchBar/PeriodArea.tsx
  FE/src/components/SearchBar/PriceArea.tsx
  FE/src/components/SearchBar/SearchBar.style.ts
  FE/src/components/SearchBar/constants.ts
  FE/src/components/SearchBar/index.tsx
  FE/src/components/common/Icon/index.tsx
  FE/src/components/common/Modal/Modal.style.ts
  FE/src/components/common/Modal/index.tsx
  FE/src/constants/api.js
  FE/src/constants/index.js
  FE/src/context/calendar/Provider.tsx
  FE/src/context/price/Provider.tsx
  FE/src/data/index.ts
  FE/src/data/rangeData.ts
  FE/src/data/searchBarData.ts
  FE/src/hoc/WithProvider.tsx
  FE/src/lib/hooks/useAxios.ts
  FE/src/lib/hooks/useCanvas.ts
  FE/src/lib/hooks/useContext.ts
  FE/src/lib/hooks/useModal.tsx
  FE/src/mocks/handlers.js
  FE/tsconfig.path.json
Labels: review-FE

#276 [Team-02][Kai] 달력 검색화면 구현및 네트워크 구현시도
  Airbnb/Airbnb/DataLayer/Network/DataMapping/SearchAccomadationResponseDTO.swift
  Airbnb/Airbnb/DataLayer/Network/NetworkError.swift
  Airbnb/Airbnb/DataLayer/Network/NetworkManager.swift
  Airbnb/Airbnb/DataLayer/Service/HTTPMethod.swift
  Airbnb/Airbnb/DataLayer/Service/HTTPTask.swift
  Airbnb/Airbnb/DomainLayer/UseCases/SearchAccomadationUseCase.swift
  Airbnb/Airbnb/Helpers/DateFormatter.swift
  Airbnb/Airbnb/Helpers/FlowLayoutMaker.swift
  Airbnb/Airbnb/PresentationLayer/Filter/Model/FilterCategory.swift
  Airbnb/Airbnb/PresentationLayer/Filter/View/CalendarViewController.swift
  Airbnb/Airbnb/PresentationLayer/Filter/View/ContainerCell.swift
  Airbnb/Airbnb/PresentationLayer/Filter/View/DayRangeIndicatorView.swift
  Airbnb/Airbnb/PresentationLayer/Filter/View/FilterListCell.swift
  Airbnb/Airbnb/PresentationLayer/Filter/View/FilterViewController.swift
  Airbnb/Airbnb/PresentationLayer/Filter/ViewModel/FilterListCellViewModel.swift
  Airbnb/Airbnb/PresentationLayer/Filter/ViewModel/FilterListViewModel.swift
  Airbnb/Airbnb/PresentationLayer/Home/Model/CategoryType.swift
  Airbnb/Airbnb/PresentationLayer/Home/Model/City.swift
  Airbnb/Airbnb/PresentationLayer/Home/Model/Hero.swift
  Airbnb/Airbnb/PresentationLayer/Home/Model/RandomSite.swift
  Airbnb/Airbnb/PresentationLayer/Home/Model/Time.swift
  Airbnb/Airbnb/PresentationLayer/Home/View/CityCell.swift
  Airbnb/Airbnb/PresentationLayer/Home/View/HeroCell.swift
  Airbnb/Airbnb/PresentationLayer/Home/View/HomeViewController.swift
  Airbnb/Airbnb/PresentationLayer/Home/View/RandomSiteCell.swift
  Airbnb/Airbnb/PresentationLayer/Home/View/SectionHeader.swift
  Airbnb/Airbnb/PresentationLayer/Home/ViewModel/CityCellViewModel.swift
  Airbnb/Airbnb/PresentationLayer/Home/ViewModel/HeroCellViewModel.swift
  Airbnb/Airbnb/PresentationLayer/Home/ViewModel/HomeViewModel.swift
  Airbnb/Airbnb/PresentationLayer/Home/ViewModel/RandomSiteCellViewModel.swift
  Airbnb/Airbnb/PresentationLayer/Search/View/SearchViewController.swift
  Airbnb/Airbnb/PresentationLayer/Search/ViewModel/SearchHeaderViewModel.swift
  Airbnb/Airbnb/PresentationLayer/Search/ViewModel/SearchViewModel.swift
  Airbnb/Airbnb/PresentationLayer/Search/model/SearchHeader.swift
  Airbnb/Airbnb/PresentationLayer/SearchResult/View/SearchResultViewController.swift
  Airbnb/Airbnb/PresentationLayer/SearchResult/ViewModel/ResultViewModel.swift
  Airbnb/Airbnb/PresentationLayer/TabBarController.swift
  Airbnb/Airbnb/Screens/Filter/View/ContainerCell.swift
  Airbnb/Airbnb/Screens/Filter/View/FilterViewController.swift
  Airbnb/Airbnb/Screens/Filter/ViewModel/FilterListCellViewModel.swift
Labels: review-iOS

#273 [TEAM-22][FE] 도비 & JS 3주차 수요일 PR
  fe/.gitignore
  fe/public/index.html
  fe/src/components/Calender/Day.tsx
  fe/src/components/Calender/index.tsx
  fe/src/components/Header/SearchBar/MiniSearchBar/index.tsx
  fe/src/components/Header/SearchBar/Period.tsx
  fe/src/components/Header/SearchBar/Personnel.tsx
  fe/src/components/Header/SearchBar/Price.tsx
  fe/src/components/Header/SearchBar/SearchButton.tsx
  fe/src/components/Header/SearchBar/common/ResetButton.tsx
  fe/src/components/Header/SearchBar/index.tsx
  fe/src/components/Header/SearchBar/searchBar.styled.ts
  fe/src/components/Header/SearchWrapper.tsx
  fe/src/components/Header/UserMenu.tsx
  fe/src/components/Header/index.tsx
  fe/src/components/HotelList/Hotel.tsx
  fe/src/components/HotelList/index.tsx
  fe/src/components/Map/index.tsx
  fe/src/components/Modals/Login.tsx
  fe/src/components/Modals/PeriodModal.tsx
  fe/src/components/Modals/Personnel/PersonnelCounter.tsx
  fe/src/components/Modals/Personnel/index.tsx
  fe/src/components/Modals/PersonnelModalWrap.tsx
  fe/src/components/Modals/Price/Chart.tsx
  fe/src/components/Modals/Price/RangeChart.tsx
  fe/src/components/Modals/Price/RangeSlider.tsx
  fe/src/components/Modals/Price/index.tsx
  fe/src/components/Modals/Price/types.ts
  fe/src/components/Modals/Reservation/Cost.tsx
  fe/src/components/Modals/Reservation/ReservationInfo.tsx
  fe/src/components/Modals/Reservation/index.tsx
  fe/src/contexts/ModalContext.tsx
  fe/src/contexts/PersonnelContext.tsx
  fe/src/contexts/PriceContext.tsx
  fe/src/contexts/periodContext.tsx
  fe/src/hooks/useModal.tsx
  fe/src/hooks/usePeriod.tsx
  fe/src/hooks/usePersonnel.tsx
  fe/src/hooks/usePrice.tsx
  fe/src/images/FE_숙소예약서비스/Property 1=pause-circle.svg
  fe/src/images/FE_숙소예약서비스/pause-circle.svg
  fe/src/pages/Layout.tsx
  fe/src/pages/Result.tsx
  fe/src/utils/util.tsx
Labels: review-FE

#257 [team-07] sally + zzangmin 3주차 첫번째 PR
  .github/workflows/zzangminzzang.yml
  .idea/.gitignore
  .idea/airbnb.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  BE/airbnb/README.md
  BE/airbnb/build.gradle
  BE/airbnb/src/main/java/team07/airbnb/address/Address.java
  BE/airbnb/src/main/java/team07/airbnb/authentification/GithubAccessToken.java
  BE/airbnb/src/main/java/team07/airbnb/authentification/JwtProvider.java
  BE/airbnb/src/main/java/team07/airbnb/authentification/LoginResponse.java
  BE/airbnb/src/main/java/team07/airbnb/authentification/OauthController.java
  BE/airbnb/src/main/java/team07/airbnb/authentification/OauthProperties.java
  BE/airbnb/src/main/java/team07/airbnb/authentification/OauthService.java
  BE/airbnb/src/main/java/team07/airbnb/config/AppConfiguration.java
  BE/airbnb/src/main/java/team07/airbnb/config/RequestLoggingFilterConfig.java
  BE/airbnb/src/main/java/team07/airbnb/image/ImageRepository.java
  BE/airbnb/src/main/java/team07/airbnb/interceptor/RequestLogInterceptor.java
  BE/airbnb/src/main/java/team07/airbnb/interceptor/WebMvcConfig.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/Period.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationApiController.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationService.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/calculation/DiscountPolicy.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/calculation/FeeOrTax.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/calculation/ReservationCalculator.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/calculation/ReservationFee.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/calculation/ReservationFeeAndTax.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/calculation/ReservationReport.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/calculation/RoomCleaningFee.java
  BE/airbnb/src/main/java/team07/airbnb/reservation/calculation/WeeklyDiscountPolicy.java
  BE/airbnb/src/main/java/team07/airbnb/room/Room.java
  BE/airbnb/src/main/java/team07/airbnb/room/RoomRepository.java
  BE/airbnb/src/main/java/team07/airbnb/search/SearchApiController.java
  BE/airbnb/src/main/java/team07/airbnb/search/SearchDto.java
  BE/airbnb/src/main/java/team07/airbnb/search/SearchParam.java
  BE/airbnb/src/main/java/team07/airbnb/search/SearchPrice.java
  BE/airbnb/src/main/java/team07/airbnb/search/SearchRepository.java
  BE/airbnb/src/main/java/team07/airbnb/search/SearchRepositoryImpl.java
  BE/airbnb/src/main/java/team07/airbnb/search/SearchReservationRoomDto.java
  BE/airbnb/src/main/java/team07/airbnb/search/SearchRoomDto.java
  BE/airbnb/src/main/java/team07/airbnb/search/SearchService.java
  BE/airbnb/src/main/java/team07/airbnb/user/User.java
  BE/airbnb/src/main/java/team07/airbnb/wishlist/Wishlist.java
  BE/airbnb/src/main/java/team07/airbnb/wishlist/WishlistRepository.java
  BE/airbnb/src/main/java/team07/airbnb/wishlist/WishlistResponse.java
  BE/airbnb/src/main/java/team07/airbnb/wishlist/WishlistService.java
  BE/airbnb/src/main/java/team07/airbnb/wishlist/WishlistsResponse.java
  BE/airbnb/src/main/resources/application-deploy.properties
  BE/airbnb/src/main/resources/application-oauth.yml
  BE/airbnb/src/main/resources/application.properties
  BE/airbnb/src/main/resources/data.sql
  BE/airbnb/src/main/resources/schema.sql
  BE/airbnb/src/test/java/team07/airbnb/reservation/calculation/ReservationCalculatorTest.java
  BE/airbnb/src/test/java/team07/airbnb/search/SearchRepositoryImplTest.java
Labels: review-BE

#256 [Team-01] [FE/호이] 3주차 첫번째 PR
  fe/.gitignore
  fe/public/index.html
  fe/src/App.tsx
  fe/src/Asset/heart.svg
  fe/src/Asset/mockPhoto.svg
  fe/src/Components/Accommodation/Accommodation.styled.ts
  fe/src/Components/Accommodation/Accommodation.tsx
  fe/src/Components/Calendar/Calendar.styled.ts
  fe/src/Components/Gnb/Gnb.styled.ts
  fe/src/Components/Gnb/Gnb.tsx
  fe/src/Components/HeadCount/TicketBox/TicketBox.styled.ts
  fe/src/Components/HeadCount/TicketBox/TicketBox.tsx
  fe/src/Components/Login/Login.styled.ts
  fe/src/Components/Login/Login.tsx
  fe/src/Components/Map/Map.styled.ts
  fe/src/Components/Map/Map.tsx
  fe/src/Components/PriceChart/PriceChart.styled.ts
  fe/src/Components/PriceChart/PriceChart.tsx
  fe/src/Components/RangeSlider/RangeSlider.styled.ts
  fe/src/Components/RangeSlider/RangeSlider.tsx
  fe/src/Components/SearchBar/MiniSearchBar.tsx
  fe/src/Components/SearchBar/SearchBar.styled.ts
  fe/src/Components/SearchBar/SearchBar.tsx
  fe/src/Context/PriceProvider.tsx
  fe/src/Helpers/constant.js
  fe/src/Helpers/interface.ts
  fe/src/Helpers/utils.tsx
  fe/src/Hook/useOutsideClick.ts
  fe/src/Hook/usePriceModal.ts
  fe/src/Pages/Common/HeadCountModal/HeadCountModal.tsx
  fe/src/Pages/Common/PriceModal/PriceModal.styled.ts
  fe/src/Pages/Common/PriceModal/PriceModal.tsx
  fe/src/Pages/Common/SearchView.styled.ts
  fe/src/Pages/Common/SearchView.tsx
  fe/src/Pages/Home/Home.styled.tsx
  fe/src/Pages/Home/Home.tsx
  fe/src/Pages/SearchResult/SearchResult.styled.ts
  fe/src/Pages/SearchResult/SearchResult.tsx
Labels: review-FE

#290 [team-2][Miller] 가격 범위 조회 기능 추가 및 PR 리뷰 반영
  backend/src/main/java/com/codesquad/airbnb/auth/JwtFactory.java
  backend/src/main/java/com/codesquad/airbnb/auth/JwtFilter.java
  backend/src/main/java/com/codesquad/airbnb/auth/controller/GithubAuthController.java
  backend/src/main/java/com/codesquad/airbnb/config/WebMvcConfig.java
  backend/src/main/java/com/codesquad/airbnb/core/charge/ChargeBill.java
  backend/src/main/java/com/codesquad/airbnb/core/charge/ChargeManager.java
  backend/src/main/java/com/codesquad/airbnb/core/charge/discount/DiscountPolicy.java
  backend/src/main/java/com/codesquad/airbnb/core/charge/discount/WeeklyDiscountPolicy.java
  backend/src/main/java/com/codesquad/airbnb/core/common/embeddable/GuestGroup.java
  backend/src/main/java/com/codesquad/airbnb/core/common/embeddable/Location.java
  backend/src/main/java/com/codesquad/airbnb/core/common/embeddable/StayDate.java
  backend/src/main/java/com/codesquad/airbnb/core/district/DistrictController.java
  backend/src/main/java/com/codesquad/airbnb/core/reservation/ReservationService.java
  backend/src/main/java/com/codesquad/airbnb/core/reservation/repository/ReservationRepositoryCustom.java
  backend/src/main/java/com/codesquad/airbnb/core/reservation/repository/ReservationRepositoryCustomImpl.java
  backend/src/main/java/com/codesquad/airbnb/core/room/RoomController.java
  backend/src/main/java/com/codesquad/airbnb/core/room/RoomService.java
  backend/src/main/java/com/codesquad/airbnb/core/room/domain/LocationCluster.java
  backend/src/main/java/com/codesquad/airbnb/core/room/domain/PriceRange.java
  backend/src/main/java/com/codesquad/airbnb/core/room/domain/Radius.java
  backend/src/main/java/com/codesquad/airbnb/core/room/dto/request/RoomSearCondition.java
  backend/src/main/java/com/codesquad/airbnb/core/room/dto/response/PriceRangeResponse.java
  backend/src/main/java/com/codesquad/airbnb/core/room/dto/response/RoomSearchResponse.java
  backend/src/main/java/com/codesquad/airbnb/core/room/entity/Room.java
  backend/src/main/java/com/codesquad/airbnb/core/room/repository/RoomRepositoryCustom.java
  backend/src/main/java/com/codesquad/airbnb/core/room/repository/RoomRepositoryCustomImpl.java
  backend/src/test/java/com/codesquad/airbnb/core/reservation/ReservationServiceTest.java
  backend/src/test/java/com/codesquad/airbnb/core/room/RoomServiceTest.java
  backend/src/test/java/com/codesquad/airbnb/core/wish/WishServiceTest.java
Labels: review-BE

#279 [Team-04][BE][테리 & Sammy] 5번째 PR
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/org/team4/airbnb/accommodation/Accommodation.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationController.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationImage.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationRepository.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationService.java
  BE/src/main/java/org/team4/airbnb/accommodation/RoomFeature.java
  BE/src/main/java/org/team4/airbnb/accommodation/dto/AccommodationSearchElement.java
  BE/src/main/java/org/team4/airbnb/accommodation/dto/AccommodationSearchParams.java
  BE/src/main/java/org/team4/airbnb/accommodation/dto/AccommodationSearchRequest.java
  BE/src/main/java/org/team4/airbnb/accommodation/dto/AccommodationSearchResponse.java
  BE/src/main/java/org/team4/airbnb/auth/LoginResponse.java
  BE/src/main/java/org/team4/airbnb/auth/OAuthController.java
  BE/src/main/java/org/team4/airbnb/auth/OAuthService.java
  BE/src/main/java/org/team4/airbnb/auth/config/MemoryProviderRepository.java
  BE/src/main/java/org/team4/airbnb/auth/config/OauthAdapter.java
  BE/src/main/java/org/team4/airbnb/auth/config/OauthConfig.java
  BE/src/main/java/org/team4/airbnb/auth/config/OauthProperties.java
  BE/src/main/java/org/team4/airbnb/auth/config/OauthProvider.java
  BE/src/main/java/org/team4/airbnb/auth/dto/OauthTokenResponse.java
  BE/src/main/java/org/team4/airbnb/auth/dto/UserProfile.java
  BE/src/main/java/org/team4/airbnb/customer/Customer.java
  BE/src/main/java/org/team4/airbnb/customer/CustomerService.java
  BE/src/main/java/org/team4/airbnb/customer/dto/AccommodationForWishListResponse.java
  BE/src/main/java/org/team4/airbnb/domain/Geolocation.java
  BE/src/main/java/org/team4/airbnb/domain/TargetArea.java
  BE/src/main/java/org/team4/airbnb/exception/WishNotFoundException.java
  BE/src/main/java/org/team4/airbnb/reservation/Reservation.java
  BE/src/main/java/org/team4/airbnb/reservation/ReservationController.java
  BE/src/main/java/org/team4/airbnb/reservation/ReservationService.java
  BE/src/main/java/org/team4/airbnb/reservation/dto/ReservationElement.java
  BE/src/main/java/org/team4/airbnb/reservation/dto/ReservationRequest.java
  BE/src/main/java/org/team4/airbnb/reservation/dto/ReservationResponse.java
  BE/src/main/java/org/team4/airbnb/wish/Wish.java
  BE/src/main/java/org/team4/airbnb/wish/WishController.java
  BE/src/main/java/org/team4/airbnb/wish/WishRepository.java
  BE/src/main/java/org/team4/airbnb/wish/WishService.java
  BE/src/main/java/org/team4/airbnb/wish/dto/WishRequest.java
  BE/src/main/java/org/team4/airbnb/wish/dto/WishResponse.java
  BE/src/main/resources/application-local.yml
  BE/src/test/java/org/team4/airbnb/auth/OAuthRepositoryUseTest.java
  BE/src/test/java/org/team4/airbnb/customer/CustomerRepositoryTest.java
  BE/src/test/java/org/team4/airbnb/util/EntityCreator.java
  BE/src/test/java/org/team4/airbnb/wish/WishRepositoryTest.java
  BE/src/test/resources/logback-test.xml
Labels: review-BE

#266 [Team 18 - Android] - 숙소 검색 결과, 지도, 상세 화면 + 예약 화면 + 피드백
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/todo/airbnb/common/components/ToastMessage.kt
  app/src/main/java/com/example/todo/airbnb/data/SearchResult.kt
  app/src/main/java/com/example/todo/airbnb/data/model/date/DatesSelected.kt
  app/src/main/java/com/example/todo/airbnb/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/example/todo/airbnb/domain/model/AccommodationResult.kt
  app/src/main/java/com/example/todo/airbnb/domain/model/Personnel.kt
  app/src/main/java/com/example/todo/airbnb/domain/model/Reservation.kt
  app/src/main/java/com/example/todo/airbnb/domain/model/Search.kt
  app/src/main/java/com/example/todo/airbnb/domain/repository/MainRepository.kt
  app/src/main/java/com/example/todo/airbnb/presentation/main/MainActivity.kt
  app/src/main/java/com/example/todo/airbnb/presentation/main/components/BottomBar.kt
  app/src/main/java/com/example/todo/airbnb/presentation/main/components/MainScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/reservation/ReservationViewModel.kt
  app/src/main/java/com/example/todo/airbnb/presentation/reservation/components/DetailedReservationScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/reservation/components/ReservationScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/SearchViewModel.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/date/DateViewModel.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/date/components/Calendar.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/date/components/DateScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/date/components/DatesSelectedState.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/detail/DetailScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/detail/DetailUiState.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/detail/DetailViewModel.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/detail/components/DetailScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/detail/components/ReservationDialog.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/fare/components/Fare.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/fare/components/FareScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/main/SearchScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/main/TravelScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/personnel/PersonnelUiState.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/personnel/PersonnelViewModel.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/personnel/components/PersonnelScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/searchmap/SearchMapScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/searchmap/components/SearchMapScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/searchresult/ResultViewModel.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/searchresult/components/SearchResultScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/search/serachcondition/SearchConditionScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/wishlist/components/WishListScreen.kt
  app/src/main/java/com/example/todo/airbnb/presentation/wishlist/components/WishListViewModel.kt
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review-android

#242 [Team 14] 선택한 날짜 정보 하단에 표시 & 툴바로 건너뛰기/다음 & 슬라이더로 가격 선택할 수 있음
  iOS/Podfile
  iOS/Podfile.lock
  iOS/Targets/Cherrybnb/Sources/Common/Calendar+Extension.swift
  iOS/Targets/Cherrybnb/Sources/Common/Font+Extension.swift
  iOS/Targets/Cherrybnb/Sources/Common/PlaceFactory.swift
  iOS/Targets/Cherrybnb/Sources/Common/QueryParameter.swift
  iOS/Targets/Cherrybnb/Sources/Network/HTTPSearchService.swift
  iOS/Targets/Cherrybnb/Sources/Network/SearchManager.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Controller/CalendarPickerViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Controller/SearchDateViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Model/CalendarFactory.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Model/CalendarPicker.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Model/Month+Day.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/Model/Month.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/View/CalendarPickerViewCell.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/View/CalendarPickerViewSectionHeader.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/View/QueryParameterFormatter.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/View/QueryParameterStackView.swift
  iOS/Targets/Cherrybnb/Sources/Search_Date/View/SearchNavigationToolbar.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/DetailSearchDataSource.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/DetailSearchDelegate.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/RecommendationDataSource.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Controller/SearchLocationViewController.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Model/DefaultRecommendator.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Model/HTTPRecommandService.swift
  iOS/Targets/Cherrybnb/Sources/Search_Location/Model/RecommandDelegate.swift
  iOS/Targets/Cherrybnb/Sources/Search_Price/Model/PriceHistogram.swift
  iOS/Targets/Cherrybnb/Sources/Search_Price/View/PriceSettingView.swift
  iOS/Targets/Cherrybnb/Sources/Search_Price/ViewController/PriceSettingViewController.swift
Labels: review-iOS

#318 [Team-03] 3주차 두번째 PR
  fe/.eslintrc
  fe/.gitignore
  fe/public/index.html
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/Period/Callendar/Callendar.tsx
  fe/src/components/Modal/Personnel/Personnel.tsx
  fe/src/components/Modal/Price/Price.styled.ts
  fe/src/components/Modal/Price/Price.tsx
  fe/src/components/SearchBar/Price/Price.tsx
  fe/src/components/SearchBar/SearchBar.tsx
  fe/src/components/SearchBar/SearchList/SearchList.tsx
  fe/src/components/SearchBar/types.ts
  fe/src/context/SearchProvider.tsx
  fe/src/img/svg/pause-circle.svg
  fe/src/pages/Search/Search.tsx
  fe/tsconfig.json
Labels: review-FE

#302 [team-03] Coordinator 패턴 적용
  ios/AirBnb/AirBnb.xcodeproj/project.pbxproj
  ios/AirBnb/AirBnb/Application/Coordinator/AppFlowCoordinator.swift
  ios/AirBnb/AirBnb/Application/Coordinator/Coordinator.swift
  ios/AirBnb/AirBnb/Application/Coordinator/TabBarCoordinator.swift
  ios/AirBnb/AirBnb/Application/DI Container/AppDIContainer.swift
  ios/AirBnb/AirBnb/Application/DI Container/DIContainer.swift
  ios/AirBnb/AirBnb/Application/DI Container/TabBarDIContainer.swift
  ios/AirBnb/AirBnb/Application/SceneDelegate.swift
  ios/AirBnb/AirBnb/Data/Network/DefaultImageService.swift
  ios/AirBnb/AirBnb/Data/Repositories/DefaultImageRepository.swift
  ios/AirBnb/AirBnb/Domain/UseCases/FetchImageUseCase.swift
  ios/AirBnb/AirBnb/Presentation/HomeTabScene/Flows/HomeSceneDIContainer.swift
  ios/AirBnb/AirBnb/Presentation/HomeTabScene/Flows/HomeSceneFlowCoordinator.swift
  ios/AirBnb/AirBnb/Presentation/HomeTabScene/Home/HomeViewController.swift
  ios/AirBnb/AirBnb/Presentation/HomeTabScene/Home/View/HeroCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/HomeTabScene/Home/View/NearCityCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/HomeTabScene/Home/View/RecommendationCollectionViewCell.swift
  ios/AirBnb/AirBnb/Presentation/HomeTabScene/Home/View/TitleSupplementaryView.swift
  ios/AirBnb/AirBnb/Presentation/HomeTabScene/Home/ViewModel/HomeViewModel.swift
  ios/AirBnb/AirBnb/Presentation/HomeTabScene/Search/LocationSearchController.swift
  ios/AirBnb/AirBnb/Presentation/HomeTabScene/Search/SearchResultViewController.swift
  ios/AirBnb/AirBnb/Presentation/ReservationTabScene/Flows/ReservationSceneDIContainer.swift
  ios/AirBnb/AirBnb/Presentation/ReservationTabScene/Flows/ReservationSceneFlowCoordinator.swift
  ios/AirBnb/AirBnb/Presentation/ReservationTabScene/Reservation/ReservationViewController.swift
  ios/AirBnb/AirBnb/Presentation/WishTabScene/Flows/WishSceneDIContainer.swift
  ios/AirBnb/AirBnb/Presentation/WishTabScene/Flows/WishSceneFlowCoordinator.swift
  ios/AirBnb/AirBnb/Presentation/WishTabScene/WishList/WishListViewController.swift
  ios/AirBnb/Toolbox/Package.swift
Labels: review-iOS

#320 [Team-13][iOS][Dale&Mase] 숙소 검색조건 완성 (ViewModel로직 & View 출력)
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.pbxproj
  iOS/AirbnbApp/AirbnbApp/Info.plist
  iOS/AirbnbApp/AirbnbApp/Source/Extension/Date+Extenstion.swift
  iOS/AirbnbApp/AirbnbApp/Source/Extension/NumberFormatter+Extension.swift
  iOS/AirbnbApp/AirbnbApp/Source/Extension/UIFont+Extension.swift
  iOS/AirbnbApp/AirbnbApp/Source/Model/Model/API/MockAPI/PriceRangeMockAPI.json
  iOS/AirbnbApp/AirbnbApp/Source/Model/Model/API/SearchHomeEndPoint.swift
  iOS/AirbnbApp/AirbnbApp/Source/Model/Model/PriceRangeEntity.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Common/CityViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/Calender/CalendarCollectionViewDataSource.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/Calender/CalendarCollectionViewDelegate.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/Calender/CalendarHeaderView.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/Calender/CalendarViewController.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/Calender/ViewModel/MonthViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/Calender/ViewModel/YearViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/Calender/WeekDaysStackView.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/FilteringCondition.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/FilteringViewController.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/FilteringViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/HeadCount/Age.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/HeadCount/AgeCountStackView.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/HeadCount/HeadCountButton.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/HeadCount/HeadCountItemView.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/HeadCount/HeadCountItemViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/HeadCount/HeadCountView.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/HeadCount/HeadCountViewController.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/HeadCount/HeadCountViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/HeadCount/TotalCountViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/NextStepView.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/PriceRange/Histogram.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/PriceRange/PriceRangeViewController.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Filtering/PriceRange/PriceRangeViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Search/SearchBarDelegate.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/SearchHomeViewController.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/ViewModel/SearchHomeViewModel.swift
  iOS/AirbnbApp/AirbnbApp/Source/Repository/Common/NetworkContainer.swift
  iOS/AirbnbApp/AirbnbApp/Source/Repository/LocationRepository.swift
  iOS/AirbnbApp/AirbnbApp/Source/Repository/PriceRangeRepository.swift
  iOS/AirbnbApp/AirbnbApp/Source/Repository/PriceRangeRepositoryImpl.swift
  iOS/AirbnbApp/AirbnbApp/Source/Support/Constant.swift
Labels: review-iOS

#232 [Team-20 BE] Airbnb 프로젝트 3주차(수요일) 리뷰 요청
  be/README.md
  be/build.gradle
  be/src/main/java/codesquad/airbnb/config/MvcConfig.java
  be/src/main/java/codesquad/airbnb/config/RedisConfig.java
  be/src/main/java/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/codesquad/airbnb/controller/AuthController.java
  be/src/main/java/codesquad/airbnb/controller/ExceptionController.java
  be/src/main/java/codesquad/airbnb/controller/OAuthController.java
  be/src/main/java/codesquad/airbnb/domain/Reservation.java
  be/src/main/java/codesquad/airbnb/domain/ReservationPrice.java
  be/src/main/java/codesquad/airbnb/domain/Schedule.java
  be/src/main/java/codesquad/airbnb/dto/LoginResponse.java
  be/src/main/java/codesquad/airbnb/dto/ReservationForm.java
  be/src/main/java/codesquad/airbnb/dto/ResponseMessage.java
  be/src/main/java/codesquad/airbnb/interceptor/AuthInterceptor.java
  be/src/main/java/codesquad/airbnb/jwt/JwtConstant.java
  be/src/main/java/codesquad/airbnb/jwt/JwtManager.java
  be/src/main/java/codesquad/airbnb/jwt/JwtProvider.java
  be/src/main/java/codesquad/airbnb/jwt/JwtUtil.java
  be/src/main/java/codesquad/airbnb/jwt/JwtValidator.java
  be/src/main/java/codesquad/airbnb/repository/MemberRepository.java
  be/src/main/java/codesquad/airbnb/repository/ReservationRepository.java
  be/src/main/java/codesquad/airbnb/repository/ScheduleRepository.java
  be/src/main/java/codesquad/airbnb/service/AccommodationService.java
  be/src/main/java/codesquad/airbnb/service/OAuthService.java
  be/src/main/java/codesquad/airbnb/service/TokenService.java
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: review-BE

#234 [Team-05][BE] 비씨 & 노리 airbnb 프로젝트 3주차 첫번째 PR
  Backend/.gitcommit_be
  Backend/build.gradle
  Backend/src/main/java/project/airbnb/bnb/Bnb.java
  Backend/src/main/java/project/airbnb/bnb/BnbController.java
  Backend/src/main/java/project/airbnb/bnb/BnbRepository.java
  Backend/src/main/java/project/airbnb/bnb/BnbRepositoryCustom.java
  Backend/src/main/java/project/airbnb/bnb/BnbRepositoryImpl.java
  Backend/src/main/java/project/airbnb/bnb/BnbService.java
  Backend/src/main/java/project/airbnb/bnb/dto/BnbSimpleDto.java
  Backend/src/main/java/project/airbnb/bnb/dto/SearchQueryDto.java
  Backend/src/main/java/project/airbnb/data/DataProcessor.java
  Backend/src/main/java/project/airbnb/response/BnbSearchResponse.java
  Backend/src/main/resources/application-bc.yml
  Backend/src/main/resources/sql/data.sql
  Backend/src/test/java/project/airbnb/TestDataBuilder.java
  Backend/src/test/java/project/airbnb/bnb/BnbControllerSearchTest.java
  Backend/src/test/java/project/airbnb/bnb/BnbControllerTest.java
Labels: review-BE

#296 [Team03][BE] 마지막 PR입니다
  be/build.gradle
  be/src/main/java/teamproject/airbnb/InMemoryProviderRepository.java
  be/src/main/java/teamproject/airbnb/LoginResponse.java
  be/src/main/java/teamproject/airbnb/OauthAdapter.java
  be/src/main/java/teamproject/airbnb/OauthConfig.java
  be/src/main/java/teamproject/airbnb/OauthProperties.java
  be/src/main/java/teamproject/airbnb/OauthProvider.java
  be/src/main/java/teamproject/airbnb/controller/MemberController.java
  be/src/main/java/teamproject/airbnb/controller/RoomController.java
  be/src/main/java/teamproject/airbnb/controller/RoomQuantityResponseDto.java
  be/src/main/java/teamproject/airbnb/controller/RoomSearchInfoRequestDto.java
  be/src/main/java/teamproject/airbnb/controller/RoomSimpleInfoResponseDto.java
  be/src/main/java/teamproject/airbnb/domain/Image.java
  be/src/main/java/teamproject/airbnb/domain/Location.java
  be/src/main/java/teamproject/airbnb/domain/Member.java
  be/src/main/java/teamproject/airbnb/domain/Reservation.java
  be/src/main/java/teamproject/airbnb/domain/Review.java
  be/src/main/java/teamproject/airbnb/domain/Room.java
  be/src/main/java/teamproject/airbnb/service/RoomQuantityDto.java
  be/src/main/java/teamproject/airbnb/service/RoomService.java
  be/src/main/java/teamproject/airbnb/service/RoomSimpleInfoDto.java
  be/src/main/resources/application-oauth.yml
  be/src/main/resources/sql/data.sql
  be/src/main/resources/sql/dummy_room_images.csv
  be/src/main/resources/sql/dummy_rooms.csv
  be/src/main/resources/sql/schema.sql
Labels: review-BE

#307 [Team-12] 동기 & 루이 3주차 2번째 PR입니다.
  BE/build.gradle
  BE/src/main/java/louie/dong/airbnb/accommodation/Accommodation.java
  BE/src/main/java/louie/dong/airbnb/accommodation/AccommodationController.java
  BE/src/main/java/louie/dong/airbnb/accommodation/AccommodationImage.java
  BE/src/main/java/louie/dong/airbnb/accommodation/AccommodationRepository.java
  BE/src/main/java/louie/dong/airbnb/accommodation/AccommodationService.java
  BE/src/main/java/louie/dong/airbnb/accommodation/CustomAccommodationRepository.java
  BE/src/main/java/louie/dong/airbnb/accommodation/CustomAccommodationRepositoryImpl.java
  BE/src/main/java/louie/dong/airbnb/accommodation/DiscountPolicy.java
  BE/src/main/java/louie/dong/airbnb/accommodation/dto/AccommodationDetailPriceResponse.java
  BE/src/main/java/louie/dong/airbnb/accommodation/dto/AccommodationDetailResponse.java
  BE/src/main/java/louie/dong/airbnb/accommodation/dto/AccommodationResponse.java
  BE/src/main/java/louie/dong/airbnb/accommodation/dto/AccommodationSearchRequest.java
  BE/src/main/java/louie/dong/airbnb/accommodation/dto/AccommodationSearchResponse.java
  BE/src/main/java/louie/dong/airbnb/book/Book.java
  BE/src/main/java/louie/dong/airbnb/book/BookService.java
  BE/src/main/java/louie/dong/airbnb/book/dto/BookSaveRequest.java
  BE/src/main/java/louie/dong/airbnb/config/JpaQueryConfig.java
  BE/src/main/java/louie/dong/airbnb/wishlist/WishService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/test/java/louie/dong/airbnb/accommodation/CustomAccommodationRepositoryImplTest.java
  BE/src/test/java/louie/dong/airbnb/config/JpaQueryTestConfig.java
  BE/src/test/java/louie/dong/airbnb/integration/AccommodationIntegrationTest.java
  BE/src/test/java/louie/dong/airbnb/integration/BookIntegrationTest.java
Labels: review-BE

#315 [Team-15][BE] 포키&나단의 airbnb 프로젝트 PR5
  backend/src/main/java/team15/airbnb/accommodation/application/AccommodationService.java
  backend/src/main/java/team15/airbnb/accommodation/infrastructure/AccommodationRepository.java
  backend/src/main/java/team15/airbnb/accommodation/presentation/controller/AccommodationController.java
  backend/src/main/java/team15/airbnb/accommodation/presentation/dto/AccommodationDetailsResponse.java
  backend/src/main/java/team15/airbnb/accommodation/presentation/dto/AccommodationSimpleInfoResponse.java
  backend/src/main/java/team15/airbnb/reservation/application/ReservationService.java
  backend/src/main/java/team15/airbnb/reservation/infrastructure/ReservationRepository.java
  backend/src/main/java/team15/airbnb/reservation/presentation/controller/ReservationController.java
  backend/src/main/resources/data.sql
Labels: review-BE

#322 [TEAM-22][FE] 도비 & JS 3주차 마지막 PR
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/components/Calender/Day.tsx
  fe/src/components/Calender/index.tsx
  fe/src/components/Header/SearchBar/SearchButton.tsx
  fe/src/components/Header/SearchBar/index.tsx
  fe/src/components/Header/index.tsx
  fe/src/components/HotelList/Filter.tsx
  fe/src/components/HotelList/Hotel.tsx
  fe/src/components/HotelList/index.tsx
  fe/src/components/Map/index.tsx
  fe/src/components/Modals/Price/RangeChart.tsx
  fe/src/components/Modals/Price/RangeSlider.tsx
  fe/src/components/Modals/Price/index.tsx
  fe/src/components/Modals/Reservation/index.tsx
  fe/src/components/Skeleton/HotelList.tsx
  fe/src/components/Skeleton/LoadingSpinners.tsx
  fe/src/contexts/PriceContext.tsx
  fe/src/hooks/useFetch.tsx
  fe/src/hooks/usePrice.tsx
  fe/src/utils/util.tsx
Labels: review-FE

#311 [team-29][아울 & 난정] 3주차 금요일 PR
  mockData.json
  package-lock.json
  package.json
  src/App.jsx
  src/assets/pause.svg
  src/components/header/modal/CalendarModal.jsx
  src/components/header/modal/GuestModal.jsx
  src/components/header/modal/GuestTab.jsx
  src/components/header/modal/Modal.js
  src/components/header/modal/PriceGraph.jsx
  src/components/header/modal/PriceModal.jsx
  src/components/header/modal/RangeSlider.jsx
  src/components/header/searchBar/GuestBox.jsx
  src/components/header/searchBar/PriceBox.jsx
  src/components/main/searchMain/AccomodationHeader.tsx
  src/components/main/searchMain/AccomodationList.jsx
  src/components/main/searchMain/AccomodationList.tsx
  src/components/main/searchMain/AccomodationListItem.tsx
  src/contexts/OptionProvider.jsx
  src/contexts/PriceProvider.jsx
  src/helper/mockData.js
  src/helper/util.js
  src/icon.d.ts
  src/pages/Home.jsx
  src/temp.ts
  tsconfig.json
Labels: review-FE

#325 [team-2][BB] Airbnb 3주차 PR
  frontend/.gitignore
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/Header/ChildNodes.tsx
  frontend/src/components/Header/Header.style.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/SearchBar/ModalInnerItems/ReservationFeeModal/PriceChart.tsx
  frontend/src/components/Header/SearchBar/ModalInnerItems/ReservationFeeModal/PriceSelectArea.tsx
  frontend/src/components/Header/SearchBar/ModalInnerItems/ReservationFeeModal/ReservationFeeModal.style.ts
  frontend/src/components/Header/SearchBar/SearchBar.style.ts
  frontend/src/components/Header/SearchBar/SearchBar.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/ButtonArea/ButtonArea.style.ts
  frontend/src/components/Header/SearchBar/SelectItemArea/ButtonArea/ButtonArea.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/CheckInOut.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/PeopleCount.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/ReservationFee.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/SelectItem.style.ts
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItem/SelectItem.tsx
  frontend/src/components/Header/SearchBar/SelectItemArea/SelectItemArea.tsx
  frontend/src/components/Header/UserMenu/UserMenu.style.ts
  frontend/src/components/Main/Main.tsx
  frontend/src/components/Main/SearchResult/AccomodationsList/AccomodationsList.tsx
  frontend/src/components/Main/SearchResult/AccomodationsList/Filter/Filter.style.ts
  frontend/src/components/Main/SearchResult/AccomodationsList/Filter/Filter.tsx
  frontend/src/components/Main/SearchResult/AccomodationsList/Filter/Item.tsx
  frontend/src/components/Main/SearchResult/AccomodationsList/ListItemCard/ListItemCard.tsx
  frontend/src/components/Main/SearchResult/MapArea/MapArea.style.ts
  frontend/src/components/Main/SearchResult/MapArea/MapArea.tsx
  frontend/src/components/Main/SearchResult/SearchResult.style.ts
  frontend/src/components/Main/SearchResult/SearchResult.tsx
  frontend/src/components/NotFound/NotFound.tsx
  frontend/src/contexts/QueryContexts.tsx
  frontend/src/contexts/SearchBar.tsx
  frontend/src/contexts/contexts.ts
  frontend/src/index.tsx
  frontend/src/router/Contexts.ts
  frontend/src/router/Link.tsx
  frontend/src/router/index.d.ts
  frontend/src/router/pages.tsx
  frontend/src/router/router.tsx
  frontend/src/styles/theme.ts
  frontend/src/utils/utils.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: review-FE

#309 [Team 32] [J, 럼카] 3주차 2번째 PR 요청드립니다.
  src/assets/404.PNG
  src/assets/reservationSuccess.PNG
  src/components/Accommodations/AccommodationItem.jsx
  src/components/App.jsx
  src/components/Header/index.jsx
  src/components/Modal/ReservationModal.jsx
  src/components/Notice.jsx
  src/components/PriceModal/index.jsx
  src/components/SearchBar/MiniSearchBar.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchButton.jsx
  src/pages/NoMatch.jsx
  src/pages/ReservationSuccess.jsx
  src/pages/SearchResult.jsx
  src/store/AccommodationContext.jsx
  src/store/ReservationContext.jsx
Labels: review-FE

#314 [FE][Team-30] 3주차 마지막 PR
  airbnb/public/index.html
  airbnb/src/App.tsx
  airbnb/src/Components/CustomerCounter/Counter.tsx
  airbnb/src/Components/CustomerCounter/CounterLabel.tsx
  airbnb/src/Components/CustomerCounter/CustomerCounter.style.tsx
  airbnb/src/Components/CustomerCounter/CustomerCounter.tsx
  airbnb/src/Components/CustomerCounter/index.ts
  airbnb/src/Components/Map/Map.Style.ts
  airbnb/src/Components/Map/NaverMap.tsx
  airbnb/src/Components/Map/PriceMarker.tsx
  airbnb/src/Components/PriceGraph/PriceGraph.tsx
  airbnb/src/Components/PriceGraph/priceGraph.style.ts
  airbnb/src/Components/SearchBar/SearchBar.style.tsx
  airbnb/src/Components/SearchBar/SearchBar.tsx
  airbnb/src/Components/SearchBar/SearchButton.tsx
  airbnb/src/Contexts/Searching/reducer.ts
  airbnb/src/Contexts/Searching/types.ts
  airbnb/src/Pages/Search.tsx
  airbnb/src/Pages/index.ts
  airbnb/src/mocks/coord.js
  airbnb/src/mocks/handlers.js
Labels: review-FE

#316 [Team-22][BE][벅픽&Lee] 3주차 2번째 PR - Oauth, JWT를 활용한 로그인 구현 및 검색 쿼리 수정
  .github/workflows/prod-deploy-be.yml
  be/.gitignore
  be/build.gradle
  be/src/main/java/kr/codesquad/airbnb/AirbnbApplication.java
  be/src/main/java/kr/codesquad/airbnb/configuration/FilterConfig.java
  be/src/main/java/kr/codesquad/airbnb/configuration/JwtConfig.java
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/controller/JwtTokenController.java
  be/src/main/java/kr/codesquad/airbnb/controller/OauthController.java
  be/src/main/java/kr/codesquad/airbnb/domain/member/Member.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/filter/LoginValidateFilter.java
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/kr/codesquad/airbnb/service/OauthService.java
  be/src/main/java/kr/codesquad/airbnb/token/TokenProvider.java
  be/src/main/resources/application.yml
Labels: review-BE

#294 [Team-09][BE][Dave&K] - 3주차 첫번째 PR
  build.gradle
  src/main/java/kr/codesquad/airbnb/AirbnbApplication.java
  src/main/java/kr/codesquad/airbnb/config/JpaQueryConfig.java
  src/main/java/kr/codesquad/airbnb/config/WebConfig.java
  src/main/java/kr/codesquad/airbnb/controller/BookingController.java
  src/main/java/kr/codesquad/airbnb/controller/LodgingController.java
  src/main/java/kr/codesquad/airbnb/controller/LoginController.java
  src/main/java/kr/codesquad/airbnb/controller/MainController.java
  src/main/java/kr/codesquad/airbnb/controller/WishController.java
  src/main/java/kr/codesquad/airbnb/domain/Address.java
  src/main/java/kr/codesquad/airbnb/domain/Lodging.java
  src/main/java/kr/codesquad/airbnb/domain/Members.java
  src/main/java/kr/codesquad/airbnb/domain/Reservation.java
  src/main/java/kr/codesquad/airbnb/domain/Wish.java
  src/main/java/kr/codesquad/airbnb/dto/BookingDetailResponse.java
  src/main/java/kr/codesquad/airbnb/dto/BookingResponse.java
  src/main/java/kr/codesquad/airbnb/dto/EventResponse.java
  src/main/java/kr/codesquad/airbnb/dto/GitHubUser.java
  src/main/java/kr/codesquad/airbnb/dto/LodgingDetailResponse.java
  src/main/java/kr/codesquad/airbnb/dto/LodgingResponse.java
  src/main/java/kr/codesquad/airbnb/dto/LoginResponse.java
  src/main/java/kr/codesquad/airbnb/dto/PriceRangeResponse.java
  src/main/java/kr/codesquad/airbnb/dto/SearchLodgingsResponse.java
  src/main/java/kr/codesquad/airbnb/dto/TokenRequest.java
  src/main/java/kr/codesquad/airbnb/dto/TokenRespond.java
  src/main/java/kr/codesquad/airbnb/dto/WishListRequest.java
  src/main/java/kr/codesquad/airbnb/dto/WishResponse.java
  src/main/java/kr/codesquad/airbnb/exception/AccessTokenNotFoundException.java
  src/main/java/kr/codesquad/airbnb/jwt/Jwt.java
  src/main/java/kr/codesquad/airbnb/jwt/JwtInterceptor.java
  src/main/java/kr/codesquad/airbnb/jwt/JwtProvider.java
  src/main/java/kr/codesquad/airbnb/jwt/OauthUtils.java
  src/main/java/kr/codesquad/airbnb/repository/BookingRepository.java
  src/main/java/kr/codesquad/airbnb/repository/CustomLodgingRepositoryImpl.java
  src/main/java/kr/codesquad/airbnb/repository/MemberRepository.java
  src/main/java/kr/codesquad/airbnb/repository/WishRepository.java
  src/main/java/kr/codesquad/airbnb/request/BookingRequest.java
  src/main/java/kr/codesquad/airbnb/request/SearchLodgingRequest.java
  src/main/java/kr/codesquad/airbnb/service/BookingService.java
  src/main/java/kr/codesquad/airbnb/service/GithubOAuthService.java
  src/main/java/kr/codesquad/airbnb/service/LodgingService.java
  src/main/java/kr/codesquad/airbnb/service/MainService.java
  src/main/java/kr/codesquad/airbnb/service/MemberService.java
  src/main/java/kr/codesquad/airbnb/service/WishService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/oauth.yml
  src/main/resources/templates/index.html
  src/test/java/kr/codesquad/airbnb/repository/ImageRepositoryTest.java
Labels: review-BE

#298 [Team-01/BE] 숙소예약 서비스 프로젝트 3주차 2차 리뷰
  be/src/main/java/com/codesquad/airbnb/auth/JwtTokenProvider.java
  be/src/main/java/com/codesquad/airbnb/auth/JwtTokenResolver.java
  be/src/main/java/com/codesquad/airbnb/auth/interceptor/AuthenticationInterceptor.java
  be/src/main/java/com/codesquad/airbnb/config/WebConfig.java
  be/src/main/java/com/codesquad/airbnb/reservation/service/ReservationService.java
  be/src/main/java/com/codesquad/airbnb/reservation/web/ReservationController.java
  be/src/main/java/com/codesquad/airbnb/reservation/web/dto/ReservationListResponseDto.java
  be/src/main/java/com/codesquad/airbnb/reservation/web/dto/ReservationPriceResponseDto.java
  be/src/main/java/com/codesquad/airbnb/user/service/JwtTokenProvider.java
  be/src/main/java/com/codesquad/airbnb/user/service/LoginService.java
  be/src/main/java/com/codesquad/airbnb/user/web/dto/LoginRequestDto.java
  be/src/main/java/com/codesquad/airbnb/wishlist/domain/WishList.java
  be/src/main/java/com/codesquad/airbnb/wishlist/domain/WishListCrudRepository.java
  be/src/main/java/com/codesquad/airbnb/wishlist/service/WishListService.java
  be/src/main/java/com/codesquad/airbnb/wishlist/web/WishListController.java
  be/src/main/java/com/codesquad/airbnb/wishlist/web/dto/WishListResponseDto.java
  be/src/main/resources/application-develop.yml
  be/src/main/resources/application-prod.yml
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/main/resources/static/schema2.sql
Labels: review-BE

#321 [Team23 땃쥐] airbnb 6차 PR
  BE/doc/ExceptionHandling.md
  BE/doc/images/spring-request-lifecycle.jpg
  BE/src/main/java/codesquad/airbnb/accommodation/dto/AccommodationSearchCondition.java
  BE/src/main/java/codesquad/airbnb/accommodation/service/AccommodationQueryService.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/AccommodationController.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationListElement.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationListRequest.java
  BE/src/main/java/codesquad/airbnb/accommodation/web/dto/AccommodationListResponse.java
  BE/src/main/java/codesquad/airbnb/booking/domain/BookingPeriod.java
  BE/src/main/java/codesquad/airbnb/exception/InvalidPriceRangeException.java
  BE/src/main/java/codesquad/airbnb/exception/InvalideLatitudeRangeException.java
  BE/src/main/java/codesquad/airbnb/exception/InvalideLongitudeRangeException.java
  BE/src/main/java/codesquad/airbnb/exception/handler/ExceptionControllerAdvice.java
  BE/src/test/java/codesquad/airbnb/booking/domain/BookingPeriodTest.java
Labels: review-BE

#293 [Team-24][BE] airbnb 프로젝트 PR #5
  be/build.gradle
  be/src/main/java/kr/codesquad/airbnb/AuthenticationFilter.java
  be/src/main/java/kr/codesquad/airbnb/config/JasyptConfig.java
  be/src/main/java/kr/codesquad/airbnb/config/WebConfig.java
  be/src/main/java/kr/codesquad/airbnb/controller/BookingController.java
  be/src/main/java/kr/codesquad/airbnb/controller/RoomController.java
  be/src/main/java/kr/codesquad/airbnb/domain/CategorizedPrice.java
  be/src/main/java/kr/codesquad/airbnb/domain/RoomDiscountTaxDetail.java
  be/src/main/java/kr/codesquad/airbnb/domain/RoomPriceStatistic.java
  be/src/main/java/kr/codesquad/airbnb/dto/AmenityDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/BookingRoomRequest.java
  be/src/main/java/kr/codesquad/airbnb/dto/DiscountTaxDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/MemberDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomPriceStatisticDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/RoomSearchResponse.java
  be/src/main/java/kr/codesquad/airbnb/exception/ErrorCode.java
  be/src/main/java/kr/codesquad/airbnb/repository/CustomRoomRepositoryImpl.java
  be/src/main/java/kr/codesquad/airbnb/service/BookingService.java
  be/src/main/java/kr/codesquad/airbnb/service/MemberService.java
  be/src/main/java/kr/codesquad/airbnb/service/RoomService.java
  be/src/main/resources/application-dev.properties
  be/src/main/resources/application-prod.properties
  be/src/main/resources/application.properties
  be/src/test/java/kr/codesquad/airbnb/config/TestConfig.java
  be/src/test/java/kr/codesquad/airbnb/controller/RoomControllerTest.java
  be/src/test/java/kr/codesquad/airbnb/repository/RoomRepositoryTest.java
  be/src/test/java/kr/codesquad/airbnb/service/RoomServiceTest.java
  be/src/test/resources/application.properties
Labels: review-BE

#291 [Team-07][iOS] 단위 테스트 작성, 예약하기 POST 요청 확인
  iOS/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Entity/Reservation.swift
  iOS/Airbnb/Entity/RoomDetail.swift
  iOS/Airbnb/Entity/RoomPosition.swift
  iOS/Airbnb/Entity/SearchCondition.swift
  iOS/Airbnb/Home/HomeViewController.swift
  iOS/Airbnb/Home/View/HomeHeaderLabel.swift
  iOS/Airbnb/ImageAssets.xcassets/image_background.imageset/Contents.json
  iOS/Airbnb/ImageAssets.xcassets/image_background.imageset/background.png
  iOS/Airbnb/PositionSearch/PositionSearchUseCase.swift
  iOS/Airbnb/PositionSearch/PositionSearchViewController.swift
  iOS/Airbnb/Reservation/PriceCalculator.swift
  iOS/Airbnb/Reservation/ReservationRepository.swift
  iOS/Airbnb/Reservation/ReservationUseCase.swift
  iOS/Airbnb/Reservation/ReservationViewController.swift
  iOS/Airbnb/Resources/roomDetail.json
  iOS/Airbnb/Resources/roomList.json
  iOS/Airbnb/RoomDetail/RoomDetailRepository.swift
  iOS/Airbnb/RoomDetail/RoomDetailRepositoryProtocol.swift
  iOS/Airbnb/RoomDetail/RoomDetailUseCase.swift
  iOS/Airbnb/RoomDetail/RoomDetailViewController.swift
  iOS/Airbnb/RoomDetail/View/RoomDetailCarouselImagesView.swift
  iOS/Airbnb/RoomDetail/View/RoomDetailReservateView.swift
  iOS/Airbnb/RoomList/RoomListUseCase.swift
  iOS/Airbnb/RoomList/RoomListViewController.swift
  iOS/Airbnb/RoomList/View/SearchResultRoomsHeaderView.swift
  iOS/Airbnb/RoomPositionMap/RoomPositionMapRepository.swift
  iOS/Airbnb/RoomPositionMap/RoomPositionMapViewController.swift
  iOS/Airbnb/SearchFilter/SearchFilterUseCase.swift
  iOS/Airbnb/SearchFilter/SearchFilterViewController.swift
  iOS/Airbnb/SearchFilter/View/SearchFilterTableViewCell.swift
  iOS/Airbnb/Server/MockNetworkHandler.swift
  iOS/Airbnb/Server/MockNetworkServiceManager.swift
  iOS/Airbnb/Server/NetworkServiceManager.swift
  iOS/Airbnb/Server/Resource/EndPoint.swift
  iOS/AirbnbTests/PositionSearchModelTest.swift
  iOS/AirbnbTests/Reservation/ReservationModelTest.swift
  iOS/AirbnbTests/Reservation/ReservationUseCaseTest.swift
  iOS/AirbnbTests/Reservation/ReservationViewModelTest.swift
  iOS/AirbnbTests/RoomDetail/RoomDetailUseCaseTest.swift
  iOS/AirbnbTests/RoomList/RoomListUseCaseTest.swift
  iOS/AirbnbTests/RoomPositionMap/RoomPositionMapUseCaseTest.swift
Labels: review-iOS

#303 [Team-16][BE][Yanse] airbnb 프로젝트 2주차 PR#5
  BE/.gitignore
  BE/Dockerfile
  BE/build.gradle
  BE/src/main/generated/yanse/airbnb/domain/image/QImage.java
  BE/src/main/generated/yanse/airbnb/domain/image/QRoomImage.java
  BE/src/main/generated/yanse/airbnb/domain/member/QMembers.java
  BE/src/main/generated/yanse/airbnb/domain/reservation/QDetailFee.java
  BE/src/main/generated/yanse/airbnb/domain/reservation/QReservation.java
  BE/src/main/generated/yanse/airbnb/domain/room/QAddress.java
  BE/src/main/generated/yanse/airbnb/domain/room/QRoom.java
  BE/src/main/generated/yanse/airbnb/domain/room/QRoomInfo.java
  BE/src/main/generated/yanse/airbnb/domain/wish/QWish.java
  BE/src/main/java/yanse/airbnb/auth/AuthController.java
  BE/src/main/java/yanse/airbnb/auth/AuthService.java
  BE/src/main/java/yanse/airbnb/auth/LoginService.java
  BE/src/main/java/yanse/airbnb/auth/annotation/AccessTokenHeader.java
  BE/src/main/java/yanse/airbnb/auth/annotation/AccessTokenResolver.java
  BE/src/main/java/yanse/airbnb/auth/dto/AccessToken.java
  BE/src/main/java/yanse/airbnb/auth/dto/AccessTokenRequest.java
  BE/src/main/java/yanse/airbnb/auth/github/GithubUser.java
  BE/src/main/java/yanse/airbnb/auth/jwt/JwtInterceptor.java
  BE/src/main/java/yanse/airbnb/auth/jwt/JwtUtils.java
  BE/src/main/java/yanse/airbnb/config/WebConfig.java
  BE/src/main/java/yanse/airbnb/domain/image/Image.java
  BE/src/main/java/yanse/airbnb/domain/member/Members.java
  BE/src/main/java/yanse/airbnb/domain/member/repository/MembersRepository.java
  BE/src/main/java/yanse/airbnb/domain/reservation/Reservation.java
  BE/src/main/java/yanse/airbnb/domain/reservation/repository/ReservationRepository.java
  BE/src/main/java/yanse/airbnb/domain/reservation/repositroy/ReservationRepository.java
  BE/src/main/java/yanse/airbnb/domain/room/Room.java
  BE/src/main/java/yanse/airbnb/domain/room/repository/RoomRepositoryCustom.java
  BE/src/main/java/yanse/airbnb/domain/room/repository/RoomRepositoryImpl.java
  BE/src/main/java/yanse/airbnb/service/MainService.java
  BE/src/main/java/yanse/airbnb/service/MembersService.java
  BE/src/main/java/yanse/airbnb/service/ReservationService.java
  BE/src/main/java/yanse/airbnb/service/SearchService.java
  BE/src/main/java/yanse/airbnb/web/controller/MainController.java
  BE/src/main/java/yanse/airbnb/web/controller/ReservationController.java
  BE/src/main/java/yanse/airbnb/web/controller/SearchController.java
  BE/src/main/java/yanse/airbnb/web/dto/ResponseDto.java
  BE/src/main/java/yanse/airbnb/web/dto/image/ImageDto.java
  BE/src/main/java/yanse/airbnb/web/dto/image/RoomImageDto.java
  BE/src/main/java/yanse/airbnb/web/dto/reservation/RequestReservationDto.java
  BE/src/main/java/yanse/airbnb/web/dto/reservation/ReservationDetailDto.java
  BE/src/main/java/yanse/airbnb/web/dto/reservation/ReservationDto.java
  BE/src/main/java/yanse/airbnb/web/dto/reservation/ResponseReservationDto.java
  BE/src/main/java/yanse/airbnb/web/dto/room/RequestRoomSearchDto.java
  BE/src/main/java/yanse/airbnb/web/dto/room/ResponseRoomDto.java
  BE/src/main/java/yanse/airbnb/web/dto/room/RoomDetailDto.java
  BE/src/main/resources/application-oauth.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
Labels: review-BE

#289 [Team 12][iOS] searchView와 popularLocationView에 RxSwift와 MVVM 적용
  airbnb/airbnb.xcodeproj/project.pbxproj
  airbnb/airbnb/Info.plist
  airbnb/airbnb/Model/Domain/ImageItem.swift
  airbnb/airbnb/Model/Entity/AccommodationDetail.swift
  airbnb/airbnb/Model/Entity/AccommodationPriceDetail.swift
  airbnb/airbnb/Model/Entity/AccommodationPrices.swift
  airbnb/airbnb/Model/Entity/FilteredAccommodationPrices.swift
  airbnb/airbnb/Model/Entity/HeroImage.swift
  airbnb/airbnb/Model/Entity/PopularLocation.swift
  airbnb/airbnb/Model/Entity/Request/ReservationRequest.swift
  airbnb/airbnb/Model/Entity/Request/WishRequest.swift
  airbnb/airbnb/Model/Entity/ReservationDetail.swift
  airbnb/airbnb/Model/Entity/ReservationList.swift
  airbnb/airbnb/Model/Entity/SearchRegion.swift
  airbnb/airbnb/Model/Entity/WishList.swift
  airbnb/airbnb/Network/HTTPManager.swift
  airbnb/airbnb/Network/HTTPMethod.swift
  airbnb/airbnb/Network/ImageCacheManager.swift
  airbnb/airbnb/Network/ImageDataCacheManager.swift
  airbnb/airbnb/Network/JSONConverter.swift
  airbnb/airbnb/Network/NetworkManager.swift
  airbnb/airbnb/Repository/NetworkResult.swift
  airbnb/airbnb/Repository/RemoteRepository.swift
  airbnb/airbnb/Utility/UIImageExtension.swift
  airbnb/airbnb/View/PopularLocationView.swift
  airbnb/airbnb/View/SearchView.swift
  airbnb/airbnb/ViewController/SearchView/LocationSearchViewController.swift
  airbnb/airbnb/ViewController/SearchView/SearchViewController.swift
  airbnb/airbnb/ViewModel/PopularLocationViewModel.swift
  airbnb/airbnb/ViewModel/SearchViewModel.swift
  airbnb/airbnb/ViewModel/ViewModelType.swift
Labels: review-iOS

#331 [team04][iOS] 마지막 PR
  iOS/airbnb.xcodeproj/project.pbxproj
  iOS/airbnb.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/airbnb/App/SceneDelegate.swift
  iOS/airbnb/Common/Extension/UIViewController+Extension.swift
  iOS/airbnb/Common/MockDataModel.swift
  iOS/airbnb/Common/Model/Constant.swift
  iOS/airbnb/Common/View/CommonCollectionViewCell.swift
  iOS/airbnb/Common/View/LayoutManager.swift
  iOS/airbnb/Present/Main/Calendar/CalendarCollectionViewDataSource.swift
  iOS/airbnb/Present/Main/Calendar/CalendarDiffableDataSource.swift
  iOS/airbnb/Present/Main/Calendar/CalendarManager.swift
  iOS/airbnb/Present/Main/Calendar/CalendarViewController.swift
  iOS/airbnb/Present/Main/Calendar/Model/CalendarItem.swift
  iOS/airbnb/Present/Main/Calendar/Model/CalendarModel.swift
  iOS/airbnb/Present/Main/Calendar/Model/WeekdayModel.swift
  iOS/airbnb/Present/Main/Calendar/View/CalendarCollectionViewCell.swift
  iOS/airbnb/Present/Main/Calendar/View/CalendarHeaderView.swift
  iOS/airbnb/Present/Main/Calendar/View/ReservationInfoInputView.swift
  iOS/airbnb/Present/Main/Calendar/ViewModel/CalendarViewModel.swift
  iOS/airbnb/Present/Main/Calendar/WeekdayCollectionViewDataSource.swift
  iOS/airbnb/Present/Main/MainViewController.swift
  iOS/airbnb/Present/Main/Search/Model/SearchLocationResponseData.swift
  iOS/airbnb/Present/WishList/Model/WishListModel.swift
  iOS/airbnb/Present/WishList/Model/WishListResponseData.swift
  iOS/airbnb/Present/WishList/View/WishListCollectionViewCell.swift
  iOS/airbnb/Present/WishList/WishListCollectionViewDataSource.swift
  iOS/airbnb/Present/WishList/WishListViewController.swift
  iOS/airbnb/Present/WishList/WishListViewModel.swift
  iOS/airbnb/SupportingFiles/Assets.xcassets/images/img_gosim.imageset/Contents.json
  iOS/airbnb/SupportingFiles/Assets.xcassets/images/img_gosim.imageset/img_gosim.png
  iOS/airbnb/SupportingFiles/Info.plist
  iOS/airbnb/Utility/Observable.swift
Labels: review-iOS

#306 [team-33 포키 & bangtae] 마지막 pr보냅니다.
  airbnb-app/package-lock.json
  airbnb-app/package.json
  airbnb-app/public/assets/hero-img.png
  airbnb-app/public/assets/thumb.svg
  airbnb-app/src/component/header/Header.jsx
  airbnb-app/src/component/header/modal/calender/Calender.jsx
  airbnb-app/src/component/header/modal/calender/CalenderButton.jsx
  airbnb-app/src/component/header/modal/calender/NextButton.jsx
  airbnb-app/src/component/header/modal/calender/PrevButton.jsx
  airbnb-app/src/component/header/modal/personnel/ControllerButtons.jsx
  airbnb-app/src/component/header/modal/personnel/Personnel.jsx
  airbnb-app/src/component/header/modal/personnel/PersonnelController.jsx
  airbnb-app/src/component/header/modal/personnel/PersonnelSelectBox.jsx
  airbnb-app/src/component/header/modal/price/Price.jsx
  airbnb-app/src/component/header/modal/price/PriceSlider.jsx
  airbnb-app/src/component/header/search-bar/SearchBar.jsx
  airbnb-app/src/component/header/search-bar/SearchInput.jsx
  airbnb-app/src/component/header/search-bar/SearchInputModal.jsx
  airbnb-app/src/component/main-banner/MainBanner.jsx
  airbnb-app/src/constants/calenderText.js
  airbnb-app/src/constants/priceText.js
  airbnb-app/src/context/CalenderDateProvider.jsx
  airbnb-app/src/context/PriceProvider.jsx
  airbnb-app/src/context/SearchBarProvider.jsx
  airbnb-app/src/mock-data/priceData.js
  airbnb-app/src/styled-component/ModalContainer.js
  airbnb-app/src/styled-component/Title.js
  airbnb-app/src/utils/utils.js
Labels: review-FE

#300 [team-31][FE] Muffin & Park 3주차 금요일
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/assets/star_img.png
  src/assets/wish_img.png
  src/common/util.ts
  src/components/Chart/Graph.tsx
  src/components/Chart/index.tsx
  src/components/Header/BigSearchBar/BigMenu.tsx
  src/components/Header/BigSearchBar/SearchButton.tsx
  src/components/Header/BigSearchBar/index.tsx
  src/components/Header/UserInfo.tsx
  src/components/Loading.tsx
  src/components/Main/CategoryLocations.tsx
  src/components/Main/NearLocations.tsx
  src/components/Main/SkeletonNearLocations.tsx
  src/components/OAuthCallback.tsx
  src/components/SearchResult/Room.tsx
  src/components/SearchResult/RoomModal.tsx
  src/components/SearchResult/Rooms.tsx
  src/contexts/HeaderProvider.tsx
  src/contexts/PriceProvider.tsx
  src/hooks/useFetch.tsx
  src/hooks/useThrottle.jsx
  src/index.tsx
  src/pages/MainPage.tsx
  src/pages/SearchResultPage.tsx
  src/server/browser.ts
  src/server/dummyData/categoryLocations.js
  src/server/dummyData/nearLocations.js
  src/server/dummyData/roomDetail.js
  src/server/dummyData/roomList.js
  src/server/handlers.ts
  tsconfig.json
  webpack.config.js
Labels: review-FE

#317 [Team-01] [FE/호이] 3주차 두번째 PR
  fe/src/Components/Accommodation/Accommodation.tsx
  fe/src/Components/Calendar/Month/Month.tsx
  fe/src/Components/Gnb/Gnb.tsx
  fe/src/Components/HeadCount/TicketBox/TicketBox.styled.ts
  fe/src/Components/HeadCount/TicketBox/TicketBox.tsx
  fe/src/Components/Map/Map.tsx
  fe/src/Components/SearchBar/MiniSearchBar.tsx
  fe/src/Components/SearchBar/SearchBar.tsx
  fe/src/Helpers/utils.tsx
  fe/src/Pages/Common/PriceModal/PriceModal.tsx
  fe/src/Pages/SearchResult/SearchResult.tsx
Labels: review-FE

#323 [FE][Team23][Millie & Oliver] 여섯 번째 PR
  FE/src/components/Calendar/ArrowButtons/ArrowButtons.style.ts
  FE/src/components/Calendar/ArrowButtons/index.tsx
  FE/src/components/Calendar/Calendar.style.ts
  FE/src/components/Calendar/DateCell/index.tsx
  FE/src/components/Calendar/DatePicker/index.tsx
  FE/src/components/Calendar/DaysOfTheWeek/index.tsx
  FE/src/components/Calendar/Month/index.tsx
  FE/src/components/Calendar/OptionButton/OptionButton.style.ts
  FE/src/components/Calendar/OptionButton/index.tsx
  FE/src/components/Calendar/Week/index.tsx
  FE/src/components/Calendar/index.tsx
  FE/src/components/GuestSelector/GuestSelector.style.ts
  FE/src/components/GuestSelector/index.tsx
  FE/src/components/RangeSlider/AirbnbSlider.style.ts
  FE/src/components/RangeSlider/RangeSlider.style.ts
  FE/src/components/RangeSlider/index.tsx
  FE/src/constants/actions.ts
  FE/src/constants/calendar.ts
  FE/src/context/CalendarProvider.tsx
  FE/src/context/index.tsx
  FE/src/styles/commonStyle.ts
  FE/src/utils/calendar.ts
  FE/src/utils/rangeSlider.ts
Labels: review-FE

#239 [Team-26][FE][이든-도리] 3주차 PR 요청
  FE/package-lock.json
  FE/package.json
  FE/public/svg/pauseCircle.svg
  FE/src/App.tsx
  FE/src/components/Calendar/index.tsx
  FE/src/components/Calendar/style.js
  FE/src/components/CalendarModal/index.tsx
  FE/src/components/CalendarModal/style.js
  FE/src/components/Chart/index.tsx
  FE/src/components/Modal/Potal.tsx
  FE/src/components/Modal/index.tsx
  FE/src/components/Modal/style.ts
  FE/src/components/PriceChart/constants.js
  FE/src/components/PriceChart/index.tsx
  FE/src/components/PriceChart/mixins.js
  FE/src/components/PriceChart/style.js
  FE/src/components/SearchBox/CalendarArea/CalendarCourousel/Calendar/index.tsx
  FE/src/components/SearchBox/CalendarArea/CalendarCourousel/Calendar/style.ts
  FE/src/components/SearchBox/CalendarArea/CalendarCourousel/constants.ts
  FE/src/components/SearchBox/CalendarArea/CalendarCourousel/index.tsx
  FE/src/components/SearchBox/CalendarArea/CalendarCourousel/style.ts
  FE/src/components/SearchBox/CalendarArea/index.tsx
  FE/src/components/SearchBox/PeopleArea/index.tsx
  FE/src/components/SearchBox/PriceArea/PriceChart/Chart/index.tsx
  FE/src/components/SearchBox/PriceArea/PriceChart/Chart/util.ts
  FE/src/components/SearchBox/PriceArea/PriceChart/MultiRangerSlider/index.tsx
  FE/src/components/SearchBox/PriceArea/PriceChart/MultiRangerSlider/style.ts
  FE/src/components/SearchBox/PriceArea/PriceChart/PriceInfo/index.tsx
  FE/src/components/SearchBox/PriceArea/PriceChart/constants.js
  FE/src/components/SearchBox/PriceArea/PriceChart/index.tsx
  FE/src/components/SearchBox/PriceArea/PriceChart/style.ts
  FE/src/components/SearchBox/PriceArea/index.tsx
  FE/src/components/SearchBox/index.tsx
  FE/src/components/SearchBox/style.ts
  FE/src/components/WindowModal/Portal/index.tsx
  FE/src/components/WindowModal/index.tsx
  FE/src/components/WindowModal/style.js
  FE/src/context/Modals/actions.ts
  FE/src/context/Modals/index.tsx
  FE/src/data/chartData.ts
  FE/src/hoc/WithModal.tsx
  FE/src/hooks/useScrollLock.ts
  FE/src/style/index.js
  FE/src/utils/index.ts
  FE/tsconfig.json
Labels: review-FE

#278 [Team-34] 베르&쥬 3주차 수요일 PR
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  public/fakeDB.json
  src/App.jsx
  src/assets/minus-icon.svg
  src/assets/plus-icon.svg
  src/components/Calendar/CalendarDate/index.tsx
  src/components/Calendar/CalendarDate/style.ts
  src/components/Calendar/index.tsx
  src/components/SearchBar/Period/Calendar/CalendarDate/index.tsx
  src/components/SearchBar/Period/Calendar/CalendarDate/style.ts
  src/components/SearchBar/Period/Calendar/CalendarPage/index.tsx
  src/components/SearchBar/Period/Calendar/CalendarPage/style.ts
  src/components/SearchBar/Period/Calendar/DateItem/index.tsx
  src/components/SearchBar/Period/Calendar/DateItem/style.ts
  src/components/SearchBar/Period/Calendar/index.tsx
  src/components/SearchBar/Period/Calendar/style.ts
  src/components/SearchBar/Period/index.tsx
  src/components/SearchBar/Period/style.ts
  src/components/SearchBar/Personnel/InputGuest/index.tsx
  src/components/SearchBar/Personnel/InputGuest/style.ts
  src/components/SearchBar/Personnel/index.tsx
  src/components/SearchBar/Personnel/style.ts
  src/components/SearchBar/Price/PriceRangeGraph/index.tsx
  src/components/SearchBar/Price/PriceRangeGraph/style.tsx
  src/components/SearchBar/Price/index.tsx
  src/components/SearchBar/Price/style.ts
  src/components/SearchBar/SearchButton/index.tsx
  src/components/SearchBar/SearchButton/style.ts
  src/components/SearchBar/index.tsx
  src/components/SearchBar/style.ts
  src/components/common/Modal/index.jsx
  src/components/common/TextBox/index.tsx
  src/components/common/TextBox/style.ts
  src/constants/calendar.ts
  src/constants/constants.ts
  src/contexts/CalendarProvider.tsx
  src/contexts/InputGuestProvider.tsx
  src/contexts/PriceProvider.tsx
  src/contexts/SearchModalProvider.tsx
  src/hooks/useModal.ts
  src/pages/Main/index.tsx
  src/types/calendar.ts
  src/types/inputGuest.ts
  src/types/searchModal.ts
  src/utils/calendar.ts
  src/utils/index.js
  tsconfig.paths.json
Labels: review-FE

#288 [Team-08][BE][후&아더] 서버 DB 환경 구축, 기능 일부 구현, OAuth 연동
  BE/build.gradle
  BE/src/main/java/com/ahoo/airbnb/AirbnbApplication.java
  BE/src/main/java/com/ahoo/airbnb/config/QuerydslConfig.java
  BE/src/main/java/com/ahoo/airbnb/entity/BaseEntity.java
  BE/src/main/java/com/ahoo/airbnb/entity/Coordinate.java
  BE/src/main/java/com/ahoo/airbnb/entity/Member.java
  BE/src/main/java/com/ahoo/airbnb/entity/OAuth.java
  BE/src/main/java/com/ahoo/airbnb/entity/Room.java
  BE/src/main/java/com/ahoo/airbnb/entity/Wish.java
  BE/src/main/java/com/ahoo/airbnb/exception/ExceptionMessage.java
  BE/src/main/java/com/ahoo/airbnb/exception/InValidTokenException.java
  BE/src/main/java/com/ahoo/airbnb/member/MemberRepository.java
  BE/src/main/java/com/ahoo/airbnb/oauth/JwtTokenProvider.java
  BE/src/main/java/com/ahoo/airbnb/oauth/OAuthAttributes.java
  BE/src/main/java/com/ahoo/airbnb/oauth/OAuthController.java
  BE/src/main/java/com/ahoo/airbnb/oauth/OAuthService.java
  BE/src/main/java/com/ahoo/airbnb/oauth/ProviderRepository.java
  BE/src/main/java/com/ahoo/airbnb/oauth/dtos/OAuthTokenResponse.java
  BE/src/main/java/com/ahoo/airbnb/oauth/dtos/SignInResponse.java
  BE/src/main/java/com/ahoo/airbnb/oauth/dtos/UserProfileResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationController.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationService.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/AccommodationChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/AccommodationTaxChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/CleaningChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ServiceChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/WeeklyDiscountChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/room/MockRoomService.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomController.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomCustomRepository.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomRepository.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomRepositoryImpl.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomService.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomResponse.java
  BE/src/main/java/com/ahoo/airbnb/wish/MockWishService.java
  BE/src/main/java/com/ahoo/airbnb/wish/WishController.java
  BE/src/main/java/com/ahoo/airbnb/wish/WishRepository.java
  BE/src/main/java/com/ahoo/airbnb/wish/WishService.java
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application-prod.yml
  BE/src/main/resources/sql/schema.sql
  BE/src/main/resources/static/index.html
  BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
Labels: review-BE

#329 [Team-04][BE][테리 & Sammy] 6번째 PR
  BE/.gitignore
  BE/build.gradle
  BE/docs/airbnb_table_create.sql
  BE/src/main/java/org/team4/airbnb/AirbnbApplication.java
  BE/src/main/java/org/team4/airbnb/accommodation/Accommodation.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationImage.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationImages.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationService.java
  BE/src/main/java/org/team4/airbnb/accommodation/AccommodationType.java
  BE/src/main/java/org/team4/airbnb/accommodation/Accommodations.java
  BE/src/main/java/org/team4/airbnb/accommodation/dto/AccommodationSearchElement.java
  BE/src/main/java/org/team4/airbnb/auth/JwtTokenProvider.java
  BE/src/main/java/org/team4/airbnb/auth/LoginController.java
  BE/src/main/java/org/team4/airbnb/auth/LoginResponse.java
  BE/src/main/java/org/team4/airbnb/auth/OAuthController.java
  BE/src/main/java/org/team4/airbnb/auth/OAuthService.java
  BE/src/main/java/org/team4/airbnb/auth/domain/JwtPayload.java
  BE/src/main/java/org/team4/airbnb/auth/dto/LoginResponse.java
  BE/src/main/java/org/team4/airbnb/auth/dto/UserProfile.java
  BE/src/main/java/org/team4/airbnb/customer/Customer.java
  BE/src/main/java/org/team4/airbnb/customer/CustomerController.java
  BE/src/main/java/org/team4/airbnb/customer/CustomerRepository.java
  BE/src/main/java/org/team4/airbnb/customer/Wish.java
  BE/src/main/java/org/team4/airbnb/customer/WishController.java
  BE/src/main/java/org/team4/airbnb/customer/WishRepository.java
  BE/src/main/java/org/team4/airbnb/customer/WishService.java
  BE/src/main/java/org/team4/airbnb/customer/dto/AccommodationForWishListResponse.java
  BE/src/main/java/org/team4/airbnb/customer/dto/WishRequest.java
  BE/src/main/java/org/team4/airbnb/customer/dto/WishResponse.java
  BE/src/main/java/org/team4/airbnb/domain/BaseCreated.java
  BE/src/main/java/org/team4/airbnb/exception/GithubInfoNotFoundException.java
  BE/src/main/java/org/team4/airbnb/exception/InValidException.java
  BE/src/main/java/org/team4/airbnb/exception/TokenExpiredException.java
  BE/src/main/java/org/team4/airbnb/exception/TokenInValidateException.java
  BE/src/main/java/org/team4/airbnb/filter/AuthCheckFilter.java
  BE/src/main/java/org/team4/airbnb/reservation/ReservationService.java
  BE/src/main/java/org/team4/airbnb/reservation/Reservations.java
  BE/src/main/java/org/team4/airbnb/reservation/dto/ReservationElement.java
  BE/src/main/java/org/team4/airbnb/reservation/dto/ReservationRequest.java
  BE/src/main/java/org/team4/airbnb/reservation/dto/ReservationResponse.java
  BE/src/test/java/org/team4/airbnb/accommodation/AccommodationRepositoryTest.java
  BE/src/test/java/org/team4/airbnb/customer/CustomerRepositoryTest.java
  BE/src/test/java/org/team4/airbnb/util/EntityCreator.java
  BE/src/test/java/org/team4/airbnb/wish/WishRepositoryTest.java
Labels: review-BE

#330 [team-36 | dony & yellow]3주차 2번째 PR 요청드립니다.
  public/assets/pause-circle.svg
  src/components/Calendar/index.jsx
  src/components/Modal/PriceModal.style.tsx
  src/components/Modal/PriceModal.tsx
  src/components/SearchBar/SearchInputButton.tsx
  src/components/SearchBar/index.tsx
  src/constants/type.ts
  src/contexts/ReservationInfoProvider.tsx
  src/contexts/SelectedModalNameProvider.tsx
  src/mocks/accommodations.js
  src/utils/util.ts
Labels: review-FE
